      SUBROUTINE UDATE(ADATE)
C
C     DATE IS FACOM BUILTIN SERVICE ROUTINE TO RETURN CURRENT DATE
C     ADATE(OUTPUT) : CURRENT DATE IN 8-BYTE
C                     EX. '95-02-09' IF WRITE ADATE IN A8 FORMAT
C
      CHARACTER*8 ADATE
      CALL DATE(ADATE)
      RETURN
      END
