CKNSD-VP-112 ***CITATION*** FLUX CALCULATION CONTROL FOR 3-D /CF-KLUX
C
CHH
      SUBROUTINE KNSD(SCATE,P2E,DCONBE,DCONRE,DCONBK,PTSAE,SOURE,NRGNE,
     & XII,SCAC,P1E,E1,IVX,JVX,KBVX,KVX,IVXP1,JVXP1,KBVXP1,LVX, JIVX,
     & JIP1VX,JP1IXZ,IOVX,IOVZ,SPAR,BIEMS,NCRP,NSPA, SIG,PVOL,NCOMP,MVX,
     &  AIO,IX3738,XLAMDA,XI,XL,B2,IOADJ,IOFS,KGP1,
CNN  & WSC,WPT,WDC,P2F,P2N,WKS,JVXW)
     & WSC,WPT,WDC,P2F,P2N,WKS,JVXW,WORK1,NVPHZ1,NVPHZ2,
CITJMOD
     & NVPHZ3,NVPHZ4,NVPHZ5,NVPHZ6,NVPHZ7,NVPHZ8,NVPHZ,JP5K,BBND)
C    & NVPHZ3,NVPHZ4,NVPHZ5,NVPHZ6,NVPHZ7,NVPHZ8,NVPHZ,JP5K)
CITJMOD
CHH   SUBROUTINE KNSD(SCATE,P2E,DCONBE,DCONRE,DCONBK,PTSAE,SOURE,NRGNE,
C    & XII,SCAC,P1E,E1,IVX,JVX,KBVX,KVX,IVXP1,JVXP1,KBVXP1,LVX, JIVX,
C    & JIP1VX,JP1IXZ,IOVX,IOVZ,SPAR,BIEMS,NCRP,NSPA, SIG,PVOL,NCOMP,MVX,
CHH  &  AIO,IX3738,XLAMDA,XI,XL,B2,IOADJ,IOFS,KGP1)
C
CDEL  INTEGER RGX , MSX , ZNEX , ZDX , WZX
CDEL  PARAMETER ( RGX=100, MSX=211, ZDX=200, ZNEX=1000, WZX=100 )
      INCLUDE  'CITPMINC'
C
      REAL*8 XII
      REAL*8 XLAMDA
      REAL*8 SUMXI,TPTSA,XADB,XPDB,XS1DB,XS2DB, TL,XRDB,CS1S,CS2S,XLL1,
     & D8,XADX,YADX, XLL2,XLL3,XLL4,XLL5,XLL6,XLEK,B2LK,B3LK,B4LK,B5LK,
     & D1,D2,D3,D4,D5, D6,D7,YADB,YPDB,YLEK,YS1S,YS2S,YS1DB,YS2DB,YRDB,
     & SPR50,XLAST
CCCC
C     COMMON / XXXXX / CKNSDA,CKNSDB,CKTRIA,CKTRIB,CKINSA,CKINSB
CCCC
C
      COMMON/ADUBP/SUMXI(ZNEX)
     &                  ,TPTSA,XADB,XPDB,XS1DB,XS2DB, TL,XRDB,CS1S,CS2S,
     &  XLL1,D8,XADX,YADX, XLL2,XLL3,XLL4,XLL5,XLL6,XLEK,B2LK,B3LK,B4LK,
     &  B5LK,D1,D2,D3,D4,D5, D6,D7,YADB,YPDB,YLEK,YS1S,YS2S,YS1DB,YS2DB,
     &  YRDB,SPR50,XLAST
      COMMON/ALSUB/BLSUB(30),TITL1(18),TITL2(18),IMAX,JMAX,KBMAX,KMAX,
     & LMAX,MMAX, NMAX,IMXP1,JMXP1,KBMXP1,NSETMX,NTO,MM1VX,KM1VX,IOIN,
     & IOUT,IOSIG,IOFLX,IO1,IO2,IO3,IO4,IO7,NER(100), IX(200),INNO(100),
     &  NGC(24),IEDG(24),ITMX(24),TIMX(6), GLIM(6),NDPL(24),IEDP1(24),
     & IEDP2(24),IEDP3(24), DPLH(6),NUAC(24),EPI(6),XMIS(6),NSRH(24),
     & XSRH1(6), XTR1(WZX),XTR2(WZX),NXTR1(WZX),NXTR2(WZX),SPARE(200),
     & IXPUT(200),XPUT(200)
      COMMON/AFLUX/BFLUX(30),KXMN8,NIT,NIIT,NIIIT,JXP1,KSCT1,KSCT2,
     & ISTART,IEP, VRGP1,VRGP2,VRGP3,VRG1,VRG2,VRGK1,VRGK2,XABS,PROD,
     & XELK,RMX,RMN,XKEF1,XKEF2,XKEF3,EXFC1,EXFC2,EXFC3, NI3,IEXTR,
     & IRECV,VRGABS,LO3,LO4,XLAMDB,EPI1,EPI2, BETTA,SAMXI,IX25,IX28,I,J,
     &  KB,K,ITMAX,ITIME, BET(MSX),DEL(MSX)
C
CITJMOD
      DIMENSION BBND(KVX)
CITJMOD
      DIMENSION E1(LVX,KVX)
      DIMENSION TSOUR(MSX)
      DIMENSION SPAR(NCRP,NSPA),BIEMS(KVX)
      DIMENSION SIG(KVX,MVX,10),PVOL(LVX),NCOMP(LVX)
      DIMENSION AIO(IX3738),XI(KVX,MVX),XL(6,KVX),B2(MVX,KVX)
CC    DIMENSION SCATE(JVX,IVX,KBVX), P2E(JIVX ,KBVX,KVX),DCONBE(JIP1VX ,
CC   &  KBVX,IOVX),DCONRE(JP1IXZ ,KBVX,IOVZ),DCONBK(JIVX , KBVXP1,IOVX),
CC   &  PTSAE(JIVX ,KBVX,IOVX),SOURE(JVX,IVX,KBVX), NRGNE(JVX,IVX,KBVX),
CC   &  XII(KVX),SCAC(KVX,MVX,KVX),P1E(JIVX,KBVX)
      DIMENSION DCONBE(JIP1VX,KBVX,IOVX),DCONRE(JP1IXZ,KBVX,IOVZ)
      DIMENSION DCONBK(JIVX,KBVXP1,IOVX),PTSAE(JIVX,KBVX,IOVX)
      DIMENSION XII(KVX,MVX),SCAC(KVX,MVX,KVX)
      REAL      SCATE(JIVX*KBVX),P2E(JIVX*KBVX,KVX),SOURE(JIVX*KBVX)
      REAL      P1E(JIVX*KBVX)
      INTEGER   NRGNE(JIVX*KBVX)
CHHHH
      REAL*8  XLAMD
      REAL    WSC(0:JVXW,IVXP1,KBVX),WPT(0:JVXW,IVXP1,KBVX)
      REAL    WDC(0:JVXW,IVXP1,0:KBVXP1,3)
      REAL    P2F(0:JVXW,IVXP1,0:KBVXP1),P2N(0:JVXW,IVXP1)
      REAL    WKS(JIVX*KBVX)
CNN
      DIMENSION NVPHZ1(JP5K,3),NVPHZ2(JP5K,3),
     1          NVPHZ3(JP5K,3),NVPHZ4(JP5K,3),
     2          NVPHZ5(JP5K,3),NVPHZ6(JP5K,3),
     3          NVPHZ7(JP5K,3),NVPHZ8(JP5K,3),
     4          NVPHZ(8)
      DIMENSION WORK1(1)
CNN
      LOGICAL LFIRST
CMOD  DATA    LFIRST/.TRUE./
      COMMON  /CITLOG/   LFIRST
CHHHH
C
CCCCC ********* SUBSCRIPT DEFINITIONS (KNSD E-061) ********* CCCCC
C    NEW         OLD            NEW         OLD
C     N1         J,I
C     N2         1,I             N5      JMAX,I
C     N3 *       1,I             N7         J,IMXP1
C     N4 *   JMXP1,I             N8         J,IMAX
C                                 J         J,1
C
C     INRB = 1  ORDINARY
C     INRB = 2  PERIODIC(REPEATING)
C     INRB = 3  90 DEGREE ROTATIONAL
C     INRB = 4  180 DEGREE ROTATIONAL
C
      INRB = IX(72) + 1
      IO19 = IX(86)
      IF (IX(135).EQ.1) REWIND IO19
      RMX = 1.0
      RMN = 1.0
      IX37 = IX(37)
      JIKBXX=JIVX*KBVX
      IF( NUAC(5).NE.14 ) THEN
        JP2=(JVX/2)*2+3
        ELSE
        JP2=JVX+2
      ENDIF
      JIM1=JP2*IVXP1-1
C
      IF( LFIRST ) THEN
        DO 50 KB=0,KBVXP1
        DO 50 I =1,IVXP1
        DO 50 J =0,JVXW
          WDC(J,I,KB,1)=0.0
          WDC(J,I,KB,2)=0.0
          WDC(J,I,KB,3)=0.0
   50   CONTINUE
C
        DO 60 KB=1,KBVX
        DO 60 I =1,IVXP1
        DO 60 J =0,JVXW
          WSC(J,I,KB)=0.0
          WPT(J,I,KB)=1.0
   60   CONTINUE
C
        DO 70 I =1,IVXP1
        DO 70 J =0,JVXW
          P2F(J,I,0)     =0.0
          P2F(J,I,KBVXP1)=0.0
   70   CONTINUE
        LFIRST=.FALSE.
      ENDIF
C
      DO 152 KT1 = 1,KVX
C
      IF(IX37.EQ.0) THEN
        IF(IX(24).GT.0) THEN
          K=KGP1-KT1
          ELSE
            K=KT1
        ENDIF
        IX(20)=K
        ELSE
C
          READ(IOADJ) AIO
C
          IF(IX(71).GT.0) THEN
            K=KGP1-KT1
            ELSE
              K=KT1
          ENDIF
          IX(20)=1
      ENDIF
C
C
      IF (IX(5).EQ.(-5)) GO TO 112
      IF (IX(24).EQ.0) GO TO 106
      IF (IX(17).GE.1) GO TO 108
C
  106 CONTINUE
      IF(IX(24).EQ.0.OR.IX(17).NE.-2.OR.IX(71).LE.0) THEN
        XLAMD=XLAMDA
        ELSE
          XLAMD=1.0D0
      ENDIF
      DO 200 L=1,LVX
  200 E1(L,K)=SIG(K,NCOMP(L),5)*PVOL(L)*XLAMD
C
  108 CONTINUE
      IF(IX(24).GT.0) GO TO 113
      IF(IX(5).EQ.0.OR.IX(5).GE.2) THEN
        DO 1108 M = 1 , MMAX
        XII(K,M)=XI(K,M)*XLAMDA
 1108   CONTINUE
        ELSE
        DO 1109 M = 1 , MMAX
          XII(K,M)=XI(K,M)/SPARE(50)
 1109   CONTINUE
      ENDIF
      GO TO 113
C
  112 CONTINUE
      IF(IX(132).GT.0) READ(IOFS) SPAR
      BIEMS(K)=XLAMDA*XI(K,1)
C
  113 CONTINUE
      IF(IX(24).GT.0) THEN
        KSCT1=MIN0(K,KXMN8)
        IF(K.LT.IRECV) KSCT1=1
        KSCT2=MIN0(K+IX28,KVX)
      ELSE
        KSCT1=MAX0(K-IX28,1)
        IF(K.GE.KXMN8) THEN
          KSCT2=KVX
          ELSE
            KSCT2=MAX0(K-1,1)
        ENDIF
        IF(K.LT.IRECV) KSCT2=IRECV
      ENDIF
C
C
      DO 210 IH=1,JIKBXX
  210 P1E(IH)=P2E(IH,K)
C
      IF(IX(24).EQ.0) THEN
      DO 212 IH=1,JIKBXX
  212 WKS(IH)=0.0D0
      DO 116 KK=KSCT1,KSCT2
      DO 216 IH=1,JIKBXX
  216 WKS(IH)=SCAC(KK,NCOMP(NRGNE(IH)),K)*P2E(IH,KK)+WKS(IH)
  116 CONTINUE
      DO 218 IH=1,JIKBXX
      M=NCOMP( NRGNE(IH) )
  218 SCATE(IH)=WKS(IH)*PVOL(NRGNE(IH))+SOURE(IH)*XII(K,M)
C
      ELSE
      DO 220 IH=1,JIKBXX
  220 WKS(IH)=SOURE(IH)*SIG(K,NCOMP(NRGNE(IH)),4)
      DO 118 KK=KSCT1,KSCT2
      DO 224 IH=1,JIKBXX
  224 WKS(IH)=SCAC(K,NCOMP(NRGNE(IH)),KK)*P2E(IH,KK)+WKS(IH)
  118 CONTINUE
      DO 226 IH=1,JIKBXX
  226 SCATE(IH)=WKS(IH)*PVOL(NRGNE(IH))
      ENDIF
C
      DO 230 IH=1,JIKBXX
  230 WKS(IH)=0.0D0
C
C
      IF(IX(5).EQ.-5) THEN
        DO 123 IH=1,JIKBXX
  123     SCATE(IH)=BIEMS(K)*SPAR(IH,1)+SCATE(IH)
      ENDIF
C
      IF (IX(135).EQ.1) WRITE(IO19) P1E
C
CBUG FIX SCALOR ROUTINE
      IF (NUAC(5).EQ.14) GO TO 500
      IF (IX(72).EQ.1) GO TO 600
      IF (NUAC(5).EQ.13) GO TO 600
  500 CONTINUE
CBUG FIX SCALOR ROUTINE
      N=IX(20)
      JNN=0
*VOCL LOOP,NOVREC
      DO 400 KB=1,KBVX
      DO 400 I =1,IVX
        NN1=(I-1)*JVX
        NNR=(I-1)*JVXP1
      DO 400 J =1,JVX
        JNN=JNN+1
        WDC(J,I,KB,1)=DCONRE(J+NNR,KB,N)
        WDC(J,I,KB,2)=DCONBE(J+NN1,KB,N)
        WDC(J,I,KB,3)=DCONBK(J+NN1,KB,N)
        WSC(J,I,KB)  =SCATE(JNN)
        WPT(J,I,KB)  =PTSAE(J+NN1,KB,N)+E1(NRGNE(JNN),K)
  400 CONTINUE
C
C
      DO 420 KB=1,KBVX
      DO 410 I =1,IVX
  410   WDC(JVXP1,I,KB,1)=DCONRE(JVXP1*I,KB,N)
      DO 420 J =1,JVX
  420   WDC(J,IVXP1,KB,2)=DCONBE(J+JIVX,KB,N)
C
      DO 430 I=1,IVX
        NN1=(I-1)*JVX
      DO 430 J=1,JVX
  430   WDC(J,I,KBVXP1,3)=DCONBK(J+NN1,KBVXP1,N)
C
      DO 440 KB=1,KBVX
      DO 440 I =1,IVX
        NN1=(I-1)*JVX+(KB-1)*JIVX
      DO 440 J =1,JVX
  440   P2F(J,I,KB)=P2E(J+NN1,K)
C
      DO 450 KB=0,KBVXP1
      DO 450 J =0,JVXW
  450   P2F(J,IVXP1,KB)=0.0
C
      IF( NUAC(5).NE.14.AND.(JVX/2)*2.EQ.JVX ) THEN
        DO 460 KB=0,KBVXP1
        DO 460 I =1,IVXP1
  460     P2F(JVXW,I,KB)=0.0
      ENDIF
C
CBUG FIX SCALOR ROUTINE
  600 CONTINUE
      NOINNR=NUAC(23)
*VOCL LOOP,SCALAR
      DO 130 INNR=1,NOINNR
      IF (NUAC(5).EQ.14) GO TO 129
      IF (IX(72).EQ.1) GO TO 128
      IF (NUAC(5).EQ.13) GO TO 127
CHH
      CALL KWRD(SCATE,P2E,DCONBE,DCONRE,DCONBK,PTSAE,TSOUR, NRGNE,E1,
     & LVX, IVX,JVX,KBVX,KVX,IVXP1,JVXP1,KBVXP1, JIVX,JIP1VX,JP1IXZ,
     & IOVX,IOVZ,WSC,WPT,WDC,P2F,P2N,JIM1)
CHH   CALL KWRD(SCATE,P2E,DCONBE,DCONRE,DCONBK,PTSAE,TSOUR, NRGNE,E1,
C    & LVX, IVX,JVX,KBVX,KVX,IVXP1,JVXP1,KBVXP1, JIVX,JIP1VX,JP1IXZ,
CHH  & IOVX,IOVZ)
CITJMOD
C     IF (IX(72).GT.1) GO TO 130
C LINE RELAXAATION VP VERSION ROWS ONLY FOR 3D
C
C     IF (NUAC(20).GT.-1) GO TO 130
C     CALL KXRD(SCATE,P2E,DCONBE,DCONRE,DCONBK,PTSAE,TSOUR, NRGNE,E1,
C    & LVX, IVX,JVX,KBVX,KVX,IVXP1,JVXP1,KBVXP1, JIVX,JIP1VX,JP1IXZ,
C    & IOVX,IOVZ)
C     IF (NUAC(20).NE.-1) GO TO 130
C     CALL KZRD(SCATE,P2E,DCONBE,DCONRE,DCONBK,PTSAE,TSOUR, NRGNE,E1,
C    & LVX, IVX,JVX,KBVX,KVX,IVXP1,JVXP1,KBVXP1, JIVX,JIP1VX,JP1IXZ,
C    & IOVX,IOVZ)
CITJMOD
      GO TO 130
  127 CONTINUE
      CALL MWRD(SCATE,P2E,DCONBE,DCONRE,DCONBK,PTSAE,TSOUR, NRGNE,E1,
     & LVX, IVX,JVX,KBVX,KVX,IVXP1,JVXP1,KBVXP1, JIVX,JIP1VX,JP1IXZ,
     & IOVX,IOVZ)
CBUG FIX FOR SCALOR ROUTINE
C     GO TO 130
      GO TO 700
CBUG FIX FOR SCALOR ROUTINE
  128 CALL KPER(SCATE,P2E,DCONBE,DCONRE,DCONBK,PTSAE,TSOUR, NRGNE, E1,
     & LVX, IVX,JVX,KBVX,KVX,IVXP1,JVXP1,KBVXP1, JIVX,JIP1VX,JP1IXZ,
     & IOVX,IOVZ)
CBUG FIX FOR SCALOR ROUTINE
C     GO TO 130
      GO TO 700
CBUG FIX FOR SCALOR ROUTINE
  129 CONTINUE
CCCC
C     CALL CLOCKV( ATIME,BTIME,2,1)
CCCC
      CALL KTRI(SCATE,P2E,DCONBE,DCONRE,DCONBK,PTSAE,TSOUR, NRGNE,E1,
     & LVX, IVX,JVX,KBVX,KVX,IVXP1,JVXP1,KBVXP1, JIVX,JIP1VX,JP1IXZ,
     & IOVX,IOVZ,WSC,WPT,WDC,P2F,P2N,JIM1)
CCCC
C     CALL CLOCKV( CTIME,DTIME,2,1 )
C     CKTRIA = CKTRIA + CTIME - ATIME
C     CKTRIB = CKTRIB + DTIME - BTIME
CCCC
CHH   CALL KTRI(SCATE,P2E,DCONBE,DCONRE,DCONBK,PTSAE,TSOUR, NRGNE,E1,
C    & LVX, IVX,JVX,KBVX,KVX,IVXP1,JVXP1,KBVXP1, JIVX,JIP1VX,JP1IXZ,
CHH  & IOVX,IOVZ)
  130 CONTINUE
C
      DO 480 KB=1,KBVX
      DO 480 I =1,IVX
        NN1=(I-1)*JVX+(KB-1)*JIVX
      DO 480 J =1,JVX
  480   P2E(J+NN1,K)=P2F(J,I,KB)
C
C
CBUG FIX FOR SCALOR ROUTINE
  700 CONTINUE
      IF ((NUAC(3).GT.0).OR.(IX(24).GT.0)) GO TO 147
C
      DO 131 M=1,MMAX
  131   B2(M,K) = 0.0
C
C
      N=IX(20)
      XLL1 = 0.0
      XLL2 = 0.0
      XLL3 = 0.0
      XLL4 = 0.0
      XLL5 = 0.0
      XLL6 = 0.0
C
      DO 300 KB=1,KBVX
      NLL1=(KB-1)*JIVX+1-JVX
      DO 300 I=1,IVX
  300 XLL1=XLL1+P2E(JVX*I+NLL1,K)*DCONRE(JVXP1*I-JVX,KB,N)
C
      DO 302 KB=1,KBVX
      NLL3=(KB-1)*JIVX
      DO 302 I=1,IVX
      T1=DCONRE(JVXP1*I,KB,N)
      IF(T1.NE.4096.0E-13) XLL3=XLL3+P2E(JVX*I+NLL3,K)*T1
  302 CONTINUE
C
      DO 306 KB=1,KBVX
      NLL2=(KB-1)*JIVX
      DO 306 J=1,JVX
  306 XLL2=XLL2+P2E(J+NLL2,K)*DCONBE(J,KB,N)
C
      IF(NUAC(5).NE.14) THEN
        DO 310 KB=1,KBVX
        NLL4=JIVX*KB-JVX
        DO 310 J=1,JVX
        T1=DCONBE(J+JIVX,KB,N)
        IF(T1.NE.4096.0E-13) XLL4=XLL4+P2E(J+NLL4,K)*T1
  310   CONTINUE
        ELSE
          DO 312 KB=1,KBVX
          NLL4=JIVX*KB-JVX
          DO 312 J=2,JVX
          T1=DCONBE(J+JIVX-1,KB,N)
          IF(T1.NE.4096.0E-13) XLL4=XLL4+P2E(J+NLL4,K)*T1
  312     CONTINUE
      ENDIF
C
      DO 316 JI=1,JIVX
  316 XLL5=XLL5+P2E(JI,K)*DCONBK(JI,1,N)
C
      NLL6=JIVX*KBVX-JIVX
      DO 318 JI=1,JIVX
        T1=DCONBK(JI,KBVXP1,N)
        IF(T1.NE.4096.0E-13) XLL6=XLL6+P2E(JI+NLL6,K)*T1
  318 CONTINUE
C
C
      GO TO (141,142,143,144),INRB
  141 XLEK = XLEK + XLL1 + XLL2 + XLL3 + XLL4 + XLL5 + XLL6
      GO TO 145
  142 XLEK = XLEK + XLL2 + XLL4 + XLL5 + XLL6
      XLL1 = XLL1 - XLL3
      XLL3 = (-XLL1)
      GO TO 145
  143 XLEK = XLEK + XLL1 + XLL2 + XLL5 + XLL6
      XLL4 = (-XLL3)
      GO TO 145
  144 XLEK = XLEK + XLL1 + XLL2 + XLL4 + XLL5 + XLL6
      XLL3 = 0.0
  145 CONTINUE
      XL(1,K) = XLL1
      XL(2,K) = XLL2
      XL(3,K) = XLL3
      XL(4,K) = XLL4
      XL(5,K) = XLL5
      XL(6,K) = XLL6
      IF (NUAC(17).LE.0) GO TO 146
CCCC
C     CALL CLOCKV( ATIME,BTIME,2,1)
CCCC
CITJMOD
      IF (XMIS(2).LT.0.AND.BBND(K).EQ.0.0) GO TO 146
CITJMOD
      CALL KINS(P2E,B2,NRGNE,DCONBE,DCONRE,DCONBK,SCAC,XL, IVX, JVX,
     & KBVX,KVX,LVX,JVXP1,KBVXP1,JIVX,JIP1VX,JP1IXZ,IOVX,IOVZ, PVOL,
CNN  & NCOMP,MVX,IVXP1,WKS,P2E,NRGNE,NRGNE)
     & NCOMP,MVX,IVXP1,P2E,NRGNE,NRGNE,WORK1,WORK1,NVPHZ1,NVPHZ2,
     & NVPHZ3,NVPHZ4,NVPHZ5,NVPHZ6,NVPHZ7,NVPHZ8,NVPHZ,JP5K)
CCCC
C     CALL CLOCKV( CTIME,DTIME,2,1 )
C     CKINSA = CKINSA + CTIME - ATIME
C     CKINSB = CKINSB + DTIME - BTIME
CCCC
CHH   CALL KINS(P2E,B2,NRGNE,DCONBE,DCONRE,DCONBK,SCAC,XL, IVX, JVX,
C    & KBVX,KVX,LVX,JVXP1,KBVXP1,JIVX,JIP1VX,JP1IXZ,IOVX,IOVZ, PVOL,
CHH  & NCOMP,MVX,IVXP1)
  146 CONTINUE
  147 CONTINUE
C
C
      DO 320 IH=1,JIKBXX
      IF(P1E(IH).NE.0.0) THEN
        RATO=P2E(IH,K)/P1E(IH)
CH      ELSE
CH        RATO=1.0
      RMX=AMAX1(RMX,RATO)
      RMN=AMIN1(RMN,RATO)
      ENDIF
  320 CONTINUE
C
C
  152 CONTINUE
C
      IF(IX(135).EQ.1) REWIND IO19
      RETURN
      END
