C             OUTPT3              LEVEL=1        DATE=81.11.14
      SUBROUTINE OUTPT3
C
      COMMON /TW1C/ DD(1),LIM1,IA(210)
      COMMON /WORK/AAA(1),LIM2,AA(130)
      DIMENSION D(212),A(132)
      EQUIVALENCE (D(1),DD(1)),(AAA(1),A(1))
      EQUIVALENCE (D(150),IEDOPS),(D(107),IGCDMP),(D(134),IFO),
     &(D(159),NDUMP1),(D(151),NEXTER)
C
      DIMENSION IDMP03(4)
C
C
C     FOR DUMP
C
      EQUIVALENCE (IA(4),IGM),(IA(24),IANG),(IA(31),IEDOPT),(IA(58),NM),
     &(IA(66),ITJT),(A(8),JCONV),(A(23),ICONV),(A(29),TIN),(D(85),IANGPR
     &),(A(50),TIMACC)
C
CSASA REAL*8 IDMP03
      CHARACTER*8 IDMP03
C
      DATA IDMP03/'*FINAL*D','UMP TAKE','N ON UNI','T       '/
C
C     CONTROLS PRINTS, INTERFACE FILE OUTPUT AND EDITS
C
C     CHECK ERROR EXIT
      IF (NEXTER.NE.0) GO TO 110
      IF (IEDOPS.LT.0) IGCDMP=0
      IF (IABS(IEDOPS).NE.5) GO TO 100
      IEDOPT=0
      IEDOPS=0
C     CHECK TIME LIMIT DUMP ALREADY PROCESSED
  100 CONTINUE
      IF (IGCDMP.NE.0) GO TO 110
C
C     OBTAIN FINAL DUMP
C
      ITEMP1=ICONV
      ITEMP2=JCONV
      ICONV=0
      JCONV=0
      CALL SECOND (TIME)
      TIMACC=TIME-TIN+TIMACC
      TIN=TIME
      IOP=0
      IF (IANG.NE.0) IOP=IGM
      CALL DUMPER (NDUMP1,IOP)
      CALL ERROR (5,IDMP03,4)
      ICONV=ITEMP1
      JCONV=ITEMP2
C
C     PROCESS FINAL PRINT
C
  110 CONTINUE
      CALL OUTT31
      IF (NEXTER.NE.0) GO TO 130
      IF (IGCDMP.NE.0) GO TO 130
      IF ((IFO.EQ.0).AND.(IANGPR.GE.0)) GO TO 120
C
C     PROCESS ANGULAR FLUX AND STANDARD INTERFACE FILES
C
      CALL IFOUT
C
C     PROCESS EDIT SUMMARY
C
  120 CONTINUE
      IF (IEDOPT.EQ.0) GO TO 130
      CALL OUTT32
  130 CONTINUE
      RETURN
      END
