C             SECOND              LEVEL=1        DATE=81.11.14
      SUBROUTINE SECOND ( TIME )
C
C     TIME IN FLOATING POINT REPLACEMENT ROUTINE
C
CKSK  CALL CLOCKM(IIII)
      CALL UCLCKM(IIII)
      TIME = ( IIII+500 ) / 1000.
      RETURN
      END
