      SUBROUTINE TWTRN2 (NMAT,MTNAME,NGR)
      DIMENSION MTNAME(2,NMAT)
      COMMON /TW1C/ DD(1),LIM1,IA(210)
      COMMON /WORK/AAA(1),LIM2,AA(1)
      COMMON /MAINC/ KKKK(1000)
      COMMON   /CITKXY/ ITHRU
CM
      DIMENSION D(212),A(132)
      EQUIVALENCE (D(1),DD(1)),(A(1),AAA(1)),(KKKK(96),MEMORY)
      EQUIVALENCE (D(135),TIMBDP),(D(136),TIMSLD),(D(107),IGCDMP),
     1            (D(151),NEXTER),(D(157),NOUT),
     2            (D(159),NDUMP1),(D(160),NDUMP2)
C
      EQUIVALENCE (A(29),TIN),(A(50),TIMACC)
C
      EQUIVALENCE (IA(  5), IM)
      EQUIVALENCE (IA(32),IGEOM)
C
      COMMON /APU/ Z(2100)
      EQUIVALENCE  (IA(64),IT) , (IA( 81),NN)
      EQUIVALENCE  (Z(  1),KZ1),(Z(  2),KZ2),(Z(  3),KZ3),(Z(  4),KZ4),
     1(Z(  5),KZ5),(Z(  6),KZ6),(Z(  7),KZ7),(Z(  8),KZ8),(Z(  9),KZ9),
     2(Z( 10),KZA),(Z( 11),KZB),(Z( 12),KZC),(Z( 13),KZ), (Z(14),MMAX),
     3(Z( 15),KZD),(Z( 16),KZE),(Z( 17),KZF),(Z( 18),KZG),(Z( 19),KZH),
     4(Z( 20),KZI)
C
C     ASSIGN MAXIMUM LENGTH OF BLOCKS A, FWBGN1, AND IA
C
      LIM2=MEMORY-2
C
      ITHRU = 1
C
C     INITIALIZE UNITS
C
      CALL REED (NDUMP1,0,0.0,0,4)
      CALL REED (NDUMP2,0,0.0,0,4)
C
C     INITIALIZE DUMP AND ERROR INDICATORS
C
      TIMBDP=600.0
      CALL SECOND (TIMSLD)
      IGCDMP=0
C    NERROR=0
      NEXTER=0
C
C
C     PROCESS CASE INPUT
C
      CALL INPUTW (NMAT,MTNAME,NGR)
      MMAX=NN*(1+NN)/2
C
      KZ =2100
      KZ1=21
      KZ2=KZ1+IT
      KZ3=KZ2+IT
      KZ4=KZ3+IT
      KZ5=KZ4+IT
      KZ6=KZ5+IT
      KZ7=KZ6+     IT
      KZ8=KZ7+MMAX
      KZ9=KZ8+MMAX
      KZA=KZ9+MMAX
      KZB=KZA+IT
      KZC=KZB+IT
      KZD=KZC+MMAX*IT
      KZE=KZD+IT
      KZF=KZE+IT
      KZG=KZF+IT
      KZH=KZG+IT
      KZI=KZH+IT
      KLM=KZI+1-KZ
      IF(KLM.LE.0) GO TO 1100
      WRITE(6,1120) KLM
 1120 FORMAT('   ***   WORK AREA FOR APU WAS ' ,I5,' WORDS SHOET   ***')
      STOP 1120
 1100 CONTINUE
      CALL INOUT( Z(KZ7),Z(KZ8),Z(KZ9),Z(KZA),MMAX)
11111 CONTINUE
C
C     PROCESS COMPUTATIONAL SECTION
C
      CALL GRIND2
C
C     PROCESS FINAL PRINT AND EDIT SUMMARIES
C
      CALL OUTPT3
      T=TIN
      CALL SECOND (TIN)
      T=(TIN-T+TIMACC)/60.0
      WRITE (NOUT,110)T
C
C     RETURN FOR NEXT CASE
C
      RETURN
  110 FORMAT (1H0//////41H0***** TOTAL EXECUTION TIME IN MINUTES = 1PE12
     1.4)
CKH   STOP
      END
