CIMXS  60.3 ***CITATION*** INPUT SECTION 038  / CF-IPTM
C
      SUBROUTINE IMXS(BBND,KVX)
C
      WRITE(6,6000) 'IMXS'
 6000 FORMAT(10X,'**** ERROR THIS SUBROUTINE IS OMITTED ** ',A4)
      STOP
      END
