CLVMX --028 ***CITATION*** READS INPUT SECTION 004/ CF-IPTM
C
      SUBROUTINE LVMX
C
CDEL  INTEGER RGX , MSX , ZNEX , ZDX , WZX
CDEL  PARAMETER ( RGX=100, MSX=211, ZDX=200, ZNEX=1000, WZX=100 )
      INCLUDE  'CITPMINC'
C
      COMMON/ALSUB/BLSUB(30),TITL1(18),TITL2(18),IMAX,JMAX,KBMAX,KMAX,
     & LMAX,MMAX, NMAX,IMXP1,JMXP1,KBMXP1,NSETMX,NTO,MM1VX,KM1VX,IOIN,
     & IOUT,IOSIG,IOFLX,IO1,IO2,IO3,IO4,IO7,NER(100), IX(200),INNO(100),
     &  NGC(24),IEDG(24),ITMX(24),TIMX(6), GLIM(6),NDPL(24),IEDP1(24),
     & IEDP2(24),IEDP3(24), DPLH(6),NUAC(24),EPI(6),XMIS(6),NSRH(24),
     & XSRH1(6), XTR1(WZX),XTR2(WZX),NXTR1(WZX),NXTR2(WZX),SPARE(200),
     & IXPUT(200),XPUT(200)
      COMMON/AMESH/BMESH(30),NREGI,NREGJ,NREGKB,XSHI(RGX),XSHJ(RGX),
     & XSHKB(RGX), MSHI(RGX),MSHJ(RGX),MSHKB(RGX),Y(MSX),YY(MSX), X(MSX)
     &  ,XX(MSX),Z(MSX),ZZ(MSX), ZONVOL(ZNEX),AVZPD(ZNEX),PDI(MSX),
     & PDJ(MSX) , PDK(MSX)
C
      DIMENSION NX(6),TX(6)
C
  100 NREGJ = 0
      IMAX = 1
      KBMAX = 1
      NREGI = 1
      NREGKB = 1
      XSHI(1) = 1.0
      XSHKB(1) = 1.0
      MSHI(1) = 1
      MSHKB(1) = 1
      NDIM = IX(25)
      NGEM = IX(26)
      MGEM = 0
      IF (NGEM-8) 102,101,102
  101 MGEM = 8
      GO TO 103
  102 IF (NGEM-12) 103,101,103
  103 READ(IOIN,1000)(NX(I),TX(I),I=1,6)
      DO 105 I = 1,6
      IF (NX(I)) 106,106,104
  104 NREGJ = NREGJ+1
C
      IF( NREGJ . GE . RGX) THEN
      WRITE(6,'(1X,A)')
     &' ** MESSAGE FORM NREGJ IN SUBROUTINE LVMX. **'
      WRITE(6,'(1X,A)')
     &'INSUFFICIENT REGION AREA NUMBER FOR RGX.'
      WRITE(6,'(1X,A,I5)')
     &'CURRENT NUMBER FOR RGX IS ',RGX
      WRITE(6,'(1X,A)')
     &'COULD YOU PLEASE CHECK YOUR NUMBER IN INCLUDE FILE IMMEDIATERY.'
      WRITE(6,'(1X,A)')
     &'I AM WILLING TO YOUR QUICK RESPONCE. THANK YOU.'
      STOP
      ENDIF
C
      MSHJ(NREGJ) = NX(I)
      XSHJ(NREGJ) = TX(I)
  105 CONTINUE
      GO TO 103
  106 IF (NDIM-2) 116,107,107
  107 NREGI = 0
  108 READ(IOIN,1000)(NX(I),TX(I),I=1,6)
      DO 110 I = 1,6
      IF (NX(I)) 111,111,109
  109 NREGI = NREGI+1
C
      IF( NREGI . GE . RGX) THEN
      WRITE(6,'(1X,A)')
     &' ** MESSAGE FORM NREGI IN SUBROUTINE LVMX. **'
      WRITE(6,'(1X,A)')
     &'INSUFFICIENT REGION AREA NUMBER FOR RGX.'
      WRITE(6,'(1X,A,I5)')
     &'CURRENT NUMBER FOR RGX IS ',RGX
      WRITE(6,'(1X,A)')
     &'COULD YOU PLEASE CHECK YOUR NUMBER IN INCLUDE FILE IMMEDIATERY.'
      WRITE(6,'(1X,A)')
     &'I AM WILLING TO YOUR QUICK RESPONCE. THANK YOU.'
      STOP
      ENDIF
C
      MSHI(NREGI) = NX(I)
      XSHI(NREGI) = TX(I)
  110 CONTINUE
      GO TO 108
  111 IF (NDIM-2) 116,116,112
  112 NREGKB = 0
  113 READ(IOIN,1000)(NX(I),TX(I),I=1,6)
      DO 115 I = 1,6
      IF (NX(I)) 116,116,114
  114 NREGKB = NREGKB+1
C
      IF( NREGKB. GE . RGX) THEN
      WRITE(6,'(1X,A)')
     &' ** MESSAGE FORM NREGKB IN SUBROUTINE LVMX. **'
      WRITE(6,'(1X,A)')
     &'INSUFFICIENT REGION AREA NUMBER FOR RGX.'
      WRITE(6,'(1X,A,I5)')
     &'CURRENT NUMBER FOR RGX IS ',RGX
      WRITE(6,'(1X,A)')
     &'COULD YOU PLEASE CHECK YOUR NUMBER IN INCLUDE FILE IMMEDIATERY.'
      WRITE(6,'(1X,A)')
     &'I AM WILLING TO YOUR QUICK RESPONCE. THANK YOU.'
      STOP
      ENDIF
C
      MSHKB(NREGKB) = NX(I)
      XSHKB(NREGKB) = TX(I)
  115 CONTINUE
      GO TO 113
  116 LMAX = NREGJ*NREGI*NREGKB
      RETURN
 1000 FORMAT(6(I3,E9.0))
      END
