C     THIS ROUTINE IS USED ONLY IN SRAC-CITATION AND NOT USED IN COREBN
C     PERTURBATION INPUT
C
      SUBROUTINE PERTI1(SAMPLE,IOPT  ,IDOPT ,BKLE  ,XYZ  ,
     &                  LBKLGP,P     ,IXYZ  ,
     &                  ICASE ,NOUT2 ,MEMPET,LAST         )
C
      DIMENSION SAMPLE(2,ICASE),IOPT(ICASE),IDOPT(ICASE),BKLE(ICASE),
     &          XYZ(2,3,ICASE),IXYZ(2,3,ICASE),LBKLGP(ICASE),P(MEMPET)
      DIMENSION IDUM(6),DUM(6)
      EQUIVALENCE (IDUM(1),DUM(1))
C
      WRITE(NOUT2,2000)
      NGPP = 0
      DO 180 I = 1,ICASE
      CALL REAM(SAMPLE(1,I),IDUM,DUM(3),2,2,1)
      IOPT(I) = IDUM(1)
      IDOPT(I)= IDUM(2)
      BKLE(I) = DUM(3)
      IF(IOPT(I).GT.0) GO TO 120
      IF(IOPT(I).LT.0) GO TO 110
      WRITE(NOUT2,3000) (SAMPLE(J,I),J=1,2),IOPT(I),IDOPT(I),BKLE(I)
      STOP
  110 CONTINUE
      WRITE(NOUT2,2010) (SAMPLE(J,I),J=1,2),IOPT(I),IDOPT(I),BKLE(I)
      GO TO 140
  120 CONTINUE
      IF(IOPT(I).GT.1) GO TO 130
      CALL REAM(DDD,IXYZ(1,1,I),DDD,0,6,0)
      WRITE(NOUT2,2020) (SAMPLE(J,I),J=1,2),IOPT(I),IDOPT(I),BKLE(I),
     &                  ((IXYZ(K,J,I),K=1,2),J=1,3)
      GO TO 140
  130 CONTINUE
      CALL REAM(DDD,DDDD,XYZ(1,1,I),0,0,6)
      WRITE(NOUT2,2030) (SAMPLE(J,I),J=1,2),IOPT(I),IDOPT(I),BKLE(I),
     &                  ((XYZ(K,J,I),K=1,2),J=1,3)
  140 CONTINUE
      IF(IDOPT(I).GT.0.AND.IDOPT(I).LE.8) GO TO 150
      WRITE(NOUT2,3010)
      STOP
  150 CONTINUE
      IF(BKLE(I).GE.0) GO TO 180
      NGP = ABS(BKLE(I)) + .5
      IF (NGPP.EQ.0 .OR. NGP.EQ.NGPP) GO TO 160
      WRITE(NOUT2,3020)
      STOP
  160 CONTINUE
      NGPP = NGP
      LBKLGP(I) = LAST
      LAST = LAST + NGP
      IF (LAST-1.LE.MEMPET) GO TO 170
      WRITE(NOUT2,3030) LAST,MEMPET
      STOP
  170 CONTINUE
      CALL REAM(DDD,DDD,P(LBKLGP(I)),0,0,NGP)
      WRITE(NOUT2,2040) (P(K),K=LBKLGP(I),LBKLGP(I)+NGP-1)
  180 CONTINUE
      RETURN
 2000 FORMAT(1H0,6X,'SAMPLE   IOPT   IDOPT  BUCKLING        PERTURBED ',
     &       'REGION SPECIFICATION'/
     &       6X,8('-'),2(1X,6('-')),7(1X,11('-')) /                    )
 2010 FORMAT(6X,2A4,I5,I7,2X,1PE12.5,6X,'ZONE NUMBER SPECIFIED (!IOPT!',
     &       ')'                                                       )
 2020 FORMAT(6X,2A4,I5,I7,2X,1PE12.5,I7,5I12                           )
 2030 FORMAT(6X,2A4,I5,I7,2X,1P7E12.5                                  )
 2040 FORMAT(11X,'GROUP DEPENDENT BUCKLING',6X,1P7E12.5/(40X,1P7E12.5) )
 3000 FORMAT(6X,2A4,I5,I7,2X,1PE12.5,' ***ERROR*** IOPT(I) .EQ. 0'     )
 3010 FORMAT('0***ERROR*** IDOPT(I) <= 0 OR IDOPT(I) > 8 '             )
 3020 FORMAT('0***ERROR*** NUMBER OF GROUP IS DIFFERENT BY CASE' )
 3030 FORMAT('0***ERROR*** USED STORAGE =',I7,' ALLOCATED STORAGE =',I7,
     &       ' COMMON /PERTCM/'                                        )
      END
