CRODI --42.1 ***CITATION*** SECTION 030 INPUT ROUTINE     /CF-IPTM
C
      SUBROUTINE RODI(NRGNE,NCOMP,JVX,IVX,KBVX,LVX,MJJR,NSETVX)
C
      WRITE(6,6000) 'RODI'
 6000 FORMAT(10X,'**** ERROR THIS SUBROUTINE IS OMITTED ** ',A4)
      STOP
      END
