CRODO --60.5 ***CITATION*** TRANSFERS SECTION 030 DATA   /CF-IPTM,RSTR
C                           FROM IO10 TO IO35 AND ADDS NCOMP
C
      SUBROUTINE RODO(NCOMP,LVX)
C
      WRITE(6,6000) 'RODO'
 6000 FORMAT(10X,'**** ERROR THIS SUBROUTINE IS OMITTED ** ',A4)
      STOP
      END
