      SUBROUTINE READ(MEMBER,RAREA,N)
C
      INCLUDE  'READPINC'
C
      CHARACTER*8     CZMEMB,SCMEMB,FLMODE,DATAKP,MEMBER
      CHARACTER*12    DDNAME,FILENM
      CHARACTER*68    PATHNM
      INTEGER*4       ECODE,TEMP,PATH
C
      COMMON /PDSPDS/ DDNAME(125),IST(15),IRW(15),IOS(35),NC(5,20),
     &                IFLSW,FILENM,ECODE,TEMP
C
      COMMON /PDSWK3/ PATHNM(15),FLMODE(15),DATAKP(15),CZMEMB(MAXMEM),
     1                SCMEMB(MAXMEM)
      COMMON /PDSWK2/ IZWRIT,IZMXDT,IZWCNT,IZDWTL,ICNTMX,
     1                LENPAT(15),INCORE(15),ICNTSC,
     2                IZDTLN(MAXMEM),IZDTTL(MAXMEM),IDUMZ,
     3                IPOSDD(MAXMEM),IPOSSC(MAXMEM),
     4                RZDATA(MXWORK)
      COMMON /PDSWK4/ WKREAD(LENWRK)
C
      DIMENSION RAREA(1)
C
C
C     WRITE(6,*) ' FILENM CALLED FOR PDSRD =',FILENM(1:8)
C
      PATH  = 3
      ECODE = 0
      CALL FILSRC(NFILE,FILENM)
C
      IF(N.EQ.0) THEN
              WRITE(6,*) ' ** MEMBER LENGTH 0 ORDERED TO BE READ FOR ',
     *           MEMBER,' ON DD=',DDNAME(NFILE),' **'
                 ECODE=4
                 GO TO 300
                 ENDIF
C
      IF(IOS(NFILE).EQ.0)  THEN
                    WRITE(6,*) ' *** FILE NOT OPENED DD=',DDNAME(NFILE)
                    STOP
                    ENDIF
C
C
C
      NC(2,NFILE)=NC(2,NFILE)+1
C
C
      IF(  INCORE(NFILE) .EQ. 1 ) THEN
           DO 100 I=ICNTMX,1,-1
           IF( IPOSDD(I).EQ.NFILE .AND. CZMEMB(I).EQ.MEMBER) GO TO 200
  100      CONTINUE
C
C **** CASE FOR NOT FOUND DATA IN ICORE ARRAY
C
        ECODE  = 0
        LENG   = 0
CFACOMS
CM      CALL PDSLEN(DDNAME(NFILE),MEMBER,LENG,ECODE)
CFACOME
CUNIXS
      CALL PDSLEN( PATHNM(NFILE),LENPAT(NFILE),MEMBER,LENG,ECODE )
CUNIXE
        IF(ECODE.GT.0) GO TO 300
CEND
        IF(LENG.GT.LENWRK*4) THEN
                             ECODE = 24
                             GO TO 300
                             ENDIF
C
CFACOMS
CM      CALL PDSRD (DDNAME(NFILE),MEMBER,WKREAD,LENG,ECODE)
CFACOME
CUNIXS
      CALL PDSRD(PATHNM(NFILE),LENPAT(NFILE),MEMBER,WKREAD,LENG,ECODE)
CUNIXE
C
        CALL COPYDT( WKREAD , RAREA , N )
        IZWCNT = IZWCNT + 1
        IZDWTL = IZDWTL + LENG/4
C
C  *** STORE DATA IN INCORE ARRAY
C
        IF(IZWCNT .GT. IZWRIT .OR. IZDWTL .GT. IZMXDT) THEN
          ELSE
          ICNTMX         = ICNTMX + 1
          IPOSDD(ICNTMX) = NFILE
          CZMEMB(ICNTMX) = MEMBER
          LENG           = LENG/4
          IZDTLN(ICNTMX) = LENG
          IZDTTL(ICNTMX+1) = IZDTTL(ICNTMX) + LENG
          NOW              = IZDTTL(ICNTMX)
C
          CALL COPYDT( WKREAD , RZDATA(NOW+1) , LENG )
          ENDIF
C
C *** CASE FOR NOT INCORE MODE PDS FILES
C     CASE FOR DIRECT FILE I/O PDS FILES
C
      ELSE
      ECODE  = 0
      LENG   = 4*N
CFACOMS
CM    CALL PDSRD (DDNAME(NFILE),MEMBER,RAREA,LENG,ECODE)
CFACOME
CUNIXS
CMOD  CALL PDSRD(PATHNM(NFILE),LENPAT(NFILE),MEMBER,RAREA,LENG,ECODE)
      CALL PDSRD(PATHNM(NFILE),LENPAT(NFILE),MEMBER,WKREAD,LENG,ECODE)
      CALL COPYDT(WKREAD,RAREA,N)
CUNIXE
      ENDIF
C
      IF(ECODE.NE.0) THEN
                     CALL PDSERR(ECODE,MEMBER,PATH,DDNAME(NFILE))
                     ENDIF
      RETURN
C
C *** CASE FOR MEMBER ALREADY STORED IN RZDATA ARRAY
C
  200 NOW = IZDTTL(I)
      CALL COPYDT( RZDATA(NOW+1) , RAREA ,  N )
      ECODE = 0
      RETURN
C
  300 CONTINUE
      CALL PDSERR(ECODE,MEMBER,PATH,DDNAME(NFILE))
C
      RETURN
      END
