      SUBROUTINE D2OCHK(IOPT,NMAT,NISO,IDENT,LISO,ID2O)
C
C *** TEST D2O IN CALCULATION REGION
C
      COMMON /TUD1C/ ITUD(50),IIT(500)
      EQUIVALENCE (ITUD(2),NMPT),(ITUD(36),LCMTM)
CM    COMMON /CIT1C/ ICIT(9),ICT(1000)
      COMMON /CIT1C/ ICIT(19),ICT(1000)
      EQUIVALENCE (ICIT(1),NMC),(ICIT(5),LCNMC)
      COMMON /PIJ2C/ PIJ(50),PAA(950)
      EQUIVALENCE (PIJ(33),NMP),(PIJ(50),LCMATD)
      COMMON /SN1C/ ISA(1000)
      EQUIVALENCE (ISA(79),NMPA),(ISA(80),LCNMPA)
      COMMON /TW1C/ TWTRN(4000)
      EQUIVALENCE (TWTRN(170),NMPW),(TWTRN(205),LZRDUC)
C
      DIMENSION IOPT(12),NISO(NMAT),IDENT(2,1),LISO(NMAT)
C
C *** START OF PROCESS
C
      IF (IOPT(2).EQ.1.OR.IOPT(12).EQ.1) THEN
      CALL D2OCK1(NMAT,NMP,ID2O,NISO,LISO,IDENT,PAA(LCMATD))
                                         ENDIF
      IF (IOPT(2).EQ.2.OR.IOPT(12).EQ.2) THEN
      CALL D2OCK1(NMAT,NMPA,ID2O,NISO,LISO,IDENT,ISA(LCNMPA))
                                         ENDIF
      IF (IOPT(2).EQ.3.OR.IOPT(12).EQ.3) THEN
      CALL D2OCK1(NMAT,NMPW,ID2O,NISO,LISO,IDENT,TWTRN(LZRDUC))
                                         ENDIF
      IF (IOPT(2).EQ.4.OR.IOPT(12).EQ.4) THEN
      CALL D2OCK1(NMAT,NMPT,ID2O,NISO,LISO,IDENT,IIT(LCMTM))
                                         ENDIF
      IF (IOPT(2).EQ.5.OR.IOPT(12).EQ.5) THEN
      CALL D2OCK1(NMAT,NMC,ID2O,NISO,LISO,IDENT,ICT(LCNMC))
                                         ENDIF
C
      RETURN
      END
