C             ECHECK              LEVEL=1        DATE=81.11.14
      SUBROUTINE ECHECK (VEC,ICOUNT,IOP)
C
C     IOP EQUALITY INDICATOR ( -1/0/1 EQUAL TO ZERO/NOT EQUAL/EQUAL BUT
C         NON ZERO )
C
      DIMENSION VEC(1)
C
      IOP=0
      IF (ICOUNT.GT.0) GO TO 110
  100 CONTINUE
      RETURN
C
C     CHECK ENTRIES FOR EQUALITY
C
  110 CONTINUE
      DO 120 IDXX=1,ICOUNT
      IF (VEC(1).NE.VEC(IDXX)) GO TO 100
  120 CONTINUE
C
C     CHECK TO SEE IF ALL ENTRIES ARE ZERO
C
      IOP=1
      IF (VEC(1).EQ.0.0) IOP=-1
      GO TO 100
      END
