      SUBROUTINE FREACT(ITHERM,FGS,SIGMA,PHMVM,PHXVX,
     1                  VM,VX,FLUX,R,ISKIP,IGMAXC,IMIX)
C
C     CALUCULATE REACTION RATE OF NUCLIDE
C
C      IMIX : M-REGION AND X-REGION ADJUST INDICATOR SETTED IN REACT
C
      DIMENSION FGS(IGMAXC),SIGMA(IGMAXC),PHMVM(IGMAXC)
      DIMENSION PHXVX(IGMAXC),FLUX(IGMAXC)
C
      ISKIP=0
      IF(FLUX(1).LT.-1.0E10) GO TO 2000
C
      DO 1000 I=1,IGMAXC
          PHG=PHMVM(I)/PHXVX(I)
          IF (IMIX.EQ.1) PHG = 1.0
          VXM=VX/VM
          IF (IMIX.EQ.1) VXM = 1.0
          IF(ITHERM.NE.0) GO TO 100
          FACT=FGS(I)
          GO TO 150
  100     FACT=1.0-FGS(I)
  150     R=R+FACT*SIGMA(I)*PHG*VXM*FLUX(I)
 1000 CONTINUE
      GO TO 3000
C
 2000 CONTINUE
      ISKIP=4
 3000 CONTINUE
      RETURN
      END
