C **********************************************************************
               SUBROUTINE   INPUT2
C **********************************************************************
C     SUBPROGRAM TO READ AND CHECK THE MATERIAL COMPOSITIONS
C
CDEL  PARAMETER   (MXLISO= 2000)
      INCLUDE  'MATDTINC'
C
      COMMON /MAINC/ IOPT(36)
     1    ,IUPSCT   ,IBSPCT   ,ISCT     ,IFIXS    ,ICTOT    ,ICOND
     2    ,IP1C     ,IFF1     ,LCXIWT   ,IBKSCH   ,MXINP2   ,IDUM45(5)
     3    ,NEFL     ,NETL     ,NEF      ,NET      ,NERF     ,NERT
     4    ,NMAT     ,NETL1    ,BSQ      ,NIN1     ,NIN2     ,NOUT1
     4    ,NOUT2    ,I66(11)  ,ITYPE    ,IMCEF    ,I79(2)
     5    ,LCNEGF   ,LCNEGT   ,LCNECF   ,LCNECT   ,LCMTNM   ,LCNISO
     6    ,LCTEMP   ,LCXL     ,LCXCDC   ,LCLISO   ,LCIDNT   ,LCDN
     7    ,LCIRES   ,LCIXMC   ,I95(6)
     8    ,CASEID(2),TITLE(18)
     9    ,AA(1880)
C
      COMMON /NEWDAN/  DANNEW(MXLISO)
C
CM    CHARACTER*12 DDNAME,FILENM
CM    COMMON /PDSPDS/ DDNAME(135),IOS(135),IFLSW,FILENM,ECODE,TEMPRY
CM    COMMON /PDSPDS/ DDNAME(125),IST(15),IRW(15),IOS(35),NC(5,20),
CM   &                IFLSW,FILENM,ECODE,TEMP
C
      DIMENSION IDUMY(10),ADUMY(100),II(880)
C
      EQUIVALENCE (AA(1),II(1))
C
C     START OF PROCESS
C
      CALL CLEA(DANNEW,MXLISO, 1.0)
C     IMCEF INDEX TO REQUIRE EFFECTIVE MICRO-X-SECTION
      IMCEF  = 0
      ISWMIC = 0
C     LCMTNM IS INITAL POSIONT OF NTNAME ARRAY IN /MAINC/ COMMON
      LCMTNM = LCNECT+NERT
C
C     WRITE(NOUT1,10)
C  10 FORMAT(' ENTER NO. OF MIXTURES')
C
      CALL REAM(NMAT,NMAT,NMAT,0,1,0)
C
      IF(NMAT.LT.0)  NMAT = -NMAT
C
      WRITE(NOUT2,15) NMAT
   15 FORMAT(/5X,'NO. OF MATERIALS USED IN THE CASE =',I3/)
C === SET INITAL POSITION OF MATERIAL SPECIFICATION DATA ARRAY
      LCNISO = LCMTNM + 2*NMAT
      LCTEMP = LCNISO + NMAT
      LCXL   = LCTEMP + NMAT
      LCXCDC = LCXL   + NMAT
      LCLISO = LCXCDC + NMAT
      LCXIWT = LCLISO + NMAT
CM    LCIDNT = LCLISO + NMAT
      LCIDNT = LCXIWT + NMAT*2
C     IPITCH = DUMMY LENGTH INSTEAD OF NTISO
      IPITCH = (MXINP2-LCIDNT)/5
      LCDN   = LCIDNT + IPITCH*2
      LCIRES = LCDN   + IPITCH
      LCIXMC = LCIRES + IPITCH
C     LISO: SEQUENTIAL ISOTOPE NUMBER
      LISO   = 1
C
C === LOOP OF MATERIALS
C
      DO 100 M = 1,NMAT
      JM       = LCMTNM+2*M-2
C
C     WRITE(NOUT1,20)
C  20 FORMAT(' ENTER MTNAME(8H),NCOM,NISO,TEMP,XL,DC IN FREE FORMAT')
C
      CALL REAM(AA(JM),IDUMY,ADUMY,2,2,3)
C
C     WRITE(NOUT2,30) M,AA(JM),AA(JM+1),IDUMY(1),IDUMY(2)
C    *              ,(ADUMY(I),I=1,3)
C  30 FORMAT(5X,'MATERIAL NO. =',I2,' MATNAME=',A4,A4,9X,
C    *          'NO. OF WORDS FOR COMMENT=',I3,' NO. OF NUCLEI MIXED =',
C    *           I2/20X,' TEMPERATURE =',F5.0,' MEAN CHORD LENGTH =',
C    *           E12.5,' DANCOFF COEF. =',E12.5)
C
C
      II(LCNISO+M-1) = IDUMY(2)
      AA(LCTEMP+M-1) = ADUMY(1)
      AA(LCXL  +M-1) = ADUMY(2)
      AA(LCXCDC+M-1) = ADUMY(3)
      DANCOF         = ADUMY(3)
      NCOM           = IDUMY(1)
      NISO           = IDUMY(2)
C === READ COMMENT CARD : NO MEANING IN PRESENT VERSION
      IF(NCOM.GT.0) THEN
                    CALL REAM(ADUMY,IDUMY,ADUMY,IDUMY(1),0,0)
                    ENDIF
C === STORE WEIGHTING FLUX NAME FOR FISSION SPECTRUM CALCULATION
      IF(NCOM.LT.0) THEN
                    CALL REAM(ADUMY,IDUMY,ADUMY,2,0,0)
                    AA(LCXIWT+(M-1)*2   ) = ADUMY(1)
                    AA(LCXIWT+(M-1)*2+1 ) = ADUMY(2)
                    ELSE
                    CALL ENCOD1(AA(LCXIWT+(M-1)*2),'ASYM','PTO.')
                    ENDIF
C
      II(LCLISO+M-1)=LISO
C
C     IF MTNAME = NEW
C     READ BLOCK 5
C
      IF ( NISO   .EQ.0) GO TO 100
C***********************************************************************
CADDED BY K.KANNEKO FOR NEW TREATMENT OF EFFECTIVE MICRO. X-SECTION
      IMCEF  = 1
C
      DO 90 ISO = 1,NISO
C
C     WRITE(NOUT1,40)
C  40 FORMAT(' ENTER NUCLEIDE I.D.(8H),IRES,IXMICR,DENSITY')
C
      IF(DANCOF.GE.0.0) THEN
      CALL REAM(AA(LCIDNT+LISO*2-2),II(LCIRES+LISO-1),AA(LCDN+LISO-1)
     *         ,2,2,1)
               DANNEW(LISO)=DANCOF
                        ELSE
      CALL REAM(AA(LCIDNT+LISO*2-2),II(LCIRES+LISO-1),ADUMY(1),2,2,2)
               AA(LCDN+LISO-1) = ADUMY(1)
               DANNEW(LISO)    = ADUMY(2)
                         ENDIF
C
      II(LCIXMC+LISO-1)=II(LCIRES+LISO)
C***********************************************************************
CDELETE BY K.KANNEKO FOR NEW TREATMENT OF EFFECTIVE MICRO. X-SECTION
C === IF IRES=1 READ GROUP CROSS SECTION FROM EFFECTIVE MICRO ===
C     IF(MOD(II(LCIRES+LISO-1),2).NE.0 .AND. MOD(IMCEF,2).EQ.0)
C    *                   IMCEF=IMCEF+1
C === IF IXMC=1 WRITE GROUP CROSS SECTION INTO EFFECTIVE MICRO ===
C     IF(MOD(II(LCIXMC+LISO-1),2).NE.0 .AND. MOD(IMCEF,2).EQ.0)
C    *                   IMCEF=IMCEF+1
C === IF IXMC=2 WRITE ULTRA-FINE CROSS SECTION INTO USER MCROSS ===
C     IF(II(LCIXMC+LISO-1).GE.2 .AND. IMCEF.LE.2)
C    *                   IMCEF=IMCEF+2
CEND *******************************************************************
C@ADD  IF IRES=1 , THEN IXMICR MUST BE 0  ** 10/25/1995 KANEKO ***
      IF(II(LCIRES+LISO-1).EQ.1)  II(LCIXMC+LISO-1)  = 0
C@END
C === IF IXMC=1 WRITE GROUP CROSS SECTION INTO EFFECTIVE MICRO ===
      IF(MOD(II(LCIXMC+LISO-1),2).NE.0 )  ISWMIC = 1
C
      LISO  = LISO + 1
C === CHECK OVERFLOW OF DANNEW ARRAY
CMOD  IF(LISO.GT.2000) GO TO 1020
      IF(LISO.GT.MXLISO) GO TO 1020
   90 CONTINUE
  100 CONTINUE
C
      NTISO = LISO-1
C === TRANSFER DN
      IDIF  = 2*IPITCH-2*NTISO
      LCDN  = LCIDNT+2*NTISO
      DO 110 ISO=1,NTISO
      AA(LCDN+ISO-1)=AA(LCDN+ISO-1+IDIF)
  110 CONTINUE
C === TRANSFER IRES
      IDIF  =3*(IPITCH-NTISO)
      LCIRES=LCDN  +NTISO
      DO 120 ISO=1,NTISO
      II(LCIRES+ISO-1)=II(LCIRES+ISO-1+IDIF)
  120 CONTINUE
C === TRANSFER IXMICR.
      IDIF  = 4*(IPITCH-NTISO)
      LCIXMC= LCIRES+NTISO
      DO 130 ISO=1,NTISO
      II(LCIXMC+ISO-1)=II(LCIXMC+ISO-1+IDIF)
  130 CONTINUE
C
      IF(IPITCH.LT.NTISO)  THEN
                           WRITE(NOUT1,140) NTISO
                           STOP
                           END IF
C === OPEN MICREF FILE
CM    IFLSW = 1
CM    IF(NTISO.GT.0.AND.(ISWMIC.EQ.1.OR.IOPT(20).GT.0) ) THEN
CM        FILENM=12HMICREF
CM        MPSPDS= 0
CM        CALL FILSRC(MPSPDS,FILENM)
CM        FILENM=DDNAME(MPSPDS)
CM        IF(IOS(MPSPDS).EQ.0) CALL OPNPDS(IRW(MPSPDS) )
CM        WRITE(6,*) ' FILENM IRW IST ; ',FILENM,IRW(MPSPDS),IST(MPSPDS)
C
CM        ELSE
CM        FILENM=12HMICREF
CM        MPSPDS= 0
CM        CALL FILSRC(MPSPDS,FILENM)
CM        FILENM=DDNAME(MPSPDS)
CM        IF(IOS(MPSPDS).NE.0) CALL CLSPDS(0)
CM        ENDIF
C
      RETURN
C
 1020 CONTINUE
      WRITE(NOUT1,1040) LISO
      STOP
C
  140 FORMAT(' *** DIMENSION OF MAINC OVER TO STORE ',I3,' NUCLEI')
 1040 FORMAT(' *** DIMENSION OF NEWDAN OVER TO STORE ',I3,'-TH NUCLEI')
C
      END
