C             S821                LEVEL=11       DATE=85.01.25
      SUBROUTINE S821(FD,FG,QG,XKE,XN,B,XJ,I1,IMJ1,IGM1,M1,CRX,IH1  ,V,
     &MA,MZ,DF,SG,VE)
C
C   *** S821 COMPUTES AND NORMALIZES FISSION SOURCE, ALSO NORMALIZES
C       FLUXES WHEN NECESSARY (CURRENTS ALSO)
C
      DIMENSION XN(I1,   1),B(M1,   1),XJ(IMJ1,   1),FG(1),FD(1),QG(1),
     &    VE(1),XKE(1),CRX(IH1,IGM1,1 ),V(1),MA(1),MZ(1),SG(1),DF(1)
C
      COMMON /SN1C/
     &              D(1),LIM1,LR,LW,LDSN,LMA,LMZ,LMB,LMC,LXMD,LFIX,LFLT,
     &       LJ5,LRM,LDF,LJ3,LJ4,LIGT,LART,LALFT,
     &LFGP,LFGG,LEND,LV,LAA,LWD,LMR,LPNC,
     &ID,ITH,ISCT,ISN,IGE,IBL,IBR,IZM,IM,IEVT,IGM,IHT,IHS,IHM,MS,MCR,MTP
     &,MT,IDFM,IPVT,IQM,IPM,IPP,IIM,ID1,ID2,ID3,ID4,ICM,IDAT1,IDAT2,IFG,
     &IFLU,IFN,IPRT,IXTR,
     &EV,EVM,EPS,BF,DY,DZ,DFM1,XNF,PV,RYF,XLAL,XLAH,EQL,XNPM,
     &T(12),NIN,NOU,NT1,NT2,NT3,NT4,NT5,NT6,NT7
C
      COMMON /WORK/ Z(1),LIM2,LXKI,LFD,LXN,LVE,LMTT,LCRX,LQ,LPA,
     &       LXJ,LCH,LCA,LCF,LCT,LCS,LTAB,
     &LXND,LSA,LSAT,LRAV,LRA,LXNN,LXNE,LXNR,LXNA,LSR,LST,LQG,LFG,LSG,
     &LXKE,LXNI,LXNO,LT3,LT5,LDA,LDB,LDC,LDS,LB,IGMP,IGMM,IIGG,NERR,IMJT
     &,IHG,IMP,MP,NDS,NUS,SDG,SCG,AG,XNLGG,XNLG,SNG,ALA,ASR,EAM,EPG,EQ,
     &E1,E2,E3,E4,E5,E6,E7,E8,E9,E10,E11,E12,E13,E14,E15,E16,E17,E18,E19
     &,E20,ESC,ESM,EVP,EVPP,FTP,IC,ICVT,IGP,IG,IHP,IIC,IIG,IP,IZP,I01,
     &I02,I03,I04,I05,I06,I07,I08,I09,I00,JT,LC,MG,MI,ML,MM,NFN,XITR,
     &XLAP,XLAPP,XLAR,XLA,XNIO,XNII,ZZ1,ZZ2,ZZ3,XNB,XKEP,XKIP,IH,I,K,L,
     &M,J,N,NN,ISV
C
C  **** START OF PROCESS *****
C
      E6=0.0
      IF(IFN+IC .EQ. 0)GO TO 21
      DO 20 I=1,IM
   20 FD(I)=0.0
      DO 24 IIG=1,IGM
      IIGG=IIG
      IGMP=IIG
      IF(IDAT1.EQ.0)GO TO 25
      IIGG=1
      IF(ITH.NE.0)GO TO 29
      READ (NT3) ((CRX(IH,1,M),IH=1,IHP),M=1,MT)
      IF(IEVT.EQ.0)READ (NT3)
   29 IF(IDAT1.NE.2)GO TO 25
      IGMP=1
      READ (NT1) (XN(I,1),I=1,IM)
      IF(ISCT.NE.0)READ (NT1)
   25 DO 26 I=1,IM
C   *** APPLY UPSCATTER SCALE FACTOR TO FISSION SOURCE CALCUTION
      E1=XN(I,IGMP)*SG(IIG)
      E4=1.0
      IF(IDFM.GT.0)E4=DF(I)
      K=MA(I)
      K=IABS(MZ(K))
      IF(IEVT.EQ.2)E6=E6 + E1*V(I)/VE(IIG)
      IF(ITH.EQ.0)GO TO 27
      FD(I)=FD(I) + XKE(IIG)*E1
      GO TO 26
   27 FD(I)=FD(I) + CRX(IHT-1,IIGG,K)*E1*E4
C     IF(FD(I).EQ.0) GO TO 9100
C     IF(FD(I).GT.1.E20.OR.FD(I).LT.1.E-20)
   26 CONTINUE
C     WRITE(6,525) IGMP
C 525 FORMAT('XN ',I3)
C     WRITE(6,*) (XN(I,IGMP),I=1,IM)
      IF(IDAT1.EQ.2)GO TO 24
C   *** APPLY UPSCATTER SCALE FACTOR TO BOUNDARY FLUXES
      DO 33 M=1,MM
   33 B(M,IIG)=B(M,IIG)*SG(IIG)
   24 CONTINUE
C     WRITE(6,526)
C 526 FORMAT(' FD')
C     WRITE(6,*) (FD(I),I=1,IM)
   21 FTP=FG(IGP)
      IF(ITH.EQ.0)GO TO 22
      DO 2 IIG=1,IGM
      FG(IIG)=0.0
      IIGG=IIG
      IF(IDAT1.EQ.0)GO TO 3
      IIGG=1
      READ(NT3) ((CRX(IH,IIGG,M),IH=1,IHP),M=1,MT)
      IF(IEVT.EQ.0)READ (NT3 )
    3 DO 2 I=1,IM
      E4=V(I)
      IF(IDFM.GT.0)E4=E4*DF(I)
      J=MA(I)
      J=IABS(MZ(J))
      FG(IIG)=FG(IIG) +   E4*FD(I)*CRX(IHT-1,IIGG,J)
    2 CONTINUE
      GO TO 1
   22 E1=0.0
      DO 4 I=1,IM
    4 E1=E1+FD(I)*V(I)
      DO 5 I=1,IGM
    5 FG(I)=E1*XKE(I)
    1 IF(IDAT1.NE.0)REWIND NT3
      IF(IDAT1.EQ.2)REWIND NT1
   28 FG(IGP)=0.0
      DO 6 I=1,IGM
    6 FG(IGP)=FG(IGP) + FG(I)
      IF(IEVT.EQ.0 .OR. FG(IGP).GT.0.0)GO TO  540
      WRITE(6,527)
  527 FORMAT('  FISSION ENERGY DISTRIBUTION')
      WRITE(6,528) (FG(I),I=1,IGP)
  528 FORMAT(10X,1P10E12.4)
C 528 FORMAT(' FGP')
C     WRITE(6,*) FG(IGP)
C     IF(FG(IGP).GT.0.) GO TO 530
C     DO 531 I=1,IGM
C 531 WRITE(6,529) I,(CRX(IH,I,1),IH=1,IHP)
C 529 FORMAT(I5,1P10E12.4/10X,10E12.4/10X,10E12.4/10X,10E12.4/
C    * 10X,10E12.4/10X,10E12.4/10X,10E12.4/10X,10E12.4)
C 530 CONTINUE
  540 IF(NFN.EQ.1 .AND. IC.NE.0)E2=FG(IGP)/E7
      E7=FG(IGP)
      IF(NFN.EQ.1)GO TO 7
      IF(IEVT.NE.1)GO TO 34
      XLAPP=XLAP
      XLAP=XLA
   34 XLA=(QG(IGP)+FG(IGP))/(QG(IGP)+FTP)
C
C     IF(IEVT.NE.0 .AND. FG(IGP).LE.0.0)CALL ERRO( 'FISS',0)
C
      IF(IEVT.NE.0 .AND. FG(IGP).LE.0.0) THEN
               WRITE(NOU,3000)
               STOP 7
               ENDIF
 3000 FORMAT('0***ERROR*** IEVT NOT EQUAL TO 0 AND TOTAL FISSION SOURCE'
     &      ,' IS 0.0 OR NEGATIVE')
C
      IF(IEVT.NE.1)GO TO 7
C
CMOD  IF((XLAP-1.0)/(XLA-1.0) .GT. 0.0   .AND.   (XLAPP-XLAP)/(XLAP-XLA)
CMOD & .GT.0.0   .OR.   IC.LE.7)GO TO 31
C
      IF( IC.LE.7 ) GO TO 31
C
      SAVE  = XLAP - XLA
      IF(ABS(SAVE).LT.1.0E-5)  GO TO   31
C
      IF( (XLAPP-XLAP)/(XLAP-XLA) .GT.0.0 ) THEN
                         SAVE  = 1.0
                         IF( XLA .EQ. 1.0 ) SAVE = 1.0001
                         IF((XLAP-SAVE)/(XLA-SAVE).GT.0.0) GO TO 31
                                            ENDIF
C
C   *** EV OSCILLATOR PREVENTOR    RARELY USED BUT SOMETIMES NEEDED
C
      XLA=0.5*(XLA + XLAP)
      NFN=1
C
   31 DO 8 I=1,IGM
      FG(I)=FG(I)/XLA
    8 XKE(I)=XKE(I)/XLA
      XKEP=XKEP/XLA
      FG(IGP)=FG(IGP)/XLA
      IF(ITH.EQ.0)GO TO 32
      DO 9 I=1,IM
    9 FD(I)=FD(I)/XLA
   32 IF(NFN.EQ.0)GO TO 10
    7 IF(IEVT.EQ.0 .OR. XNF.LE.0.0)GO TO 10
      E1=XNF/FG(IGP)
      IF(IC.EQ.0 .OR. IEVT.EQ.1)E2=E1
      DO 11 IIG=1,IGM
      IF(NFN.EQ.0)GO TO 17
      IIGG=IIG
      IF(IDAT1.NE.2)GO TO 12
      IIGG=1
      READ (NT1) (XN(I,1),I=1,IM),(B(M,1),M=1,MM)
      IF(ISCT.GT.0)READ (NT1) (XJ(I,1),I=1,IMJT)
   12 DO 13 I=1,IM
   13 XN(I,IIGG)=XN(I,IIGG)*E2
      DO 14 M=1,MM
   14 B(M,IIGG)=B(M,IIGG)*E2
      IF(ISCT.EQ.0)GO TO 16
      DO 15 I=1,IMJT
   15 XJ(I,IIGG)=XJ(I,IIGG)*E2
   16 IF(IDAT1.NE.2)GO TO 17
      WRITE (NT2) (XN(I,1),I=1,IM),(B(M,1),M=1,MM)
      IF(ISCT.GT.0)WRITE (NT2) (XJ(I,1),I=1,IMJT)
   17 FG(IIG)=FG(IIG)*E1
   11 CONTINUE
      FG(IGP)=FG(IGP)*E1
      DO 18 I=1,IM
   18 FD(I)=FD(I)*E1
      IF(IDAT1.NE.2)GO TO 19
      REWIND NT1
      REWIND NT2
      IF(NFN.NE.0)GO TO 19
   10 I00=NT1
      NT1=NT2
      NT2=I00
   19 E2=RYF*ABS(1.0-ALA)/EPS
      IF(IEVT.EQ.0)E2=1.0
      E2=AMAX1(1.0,E2)
      E2=AMIN1(E2, 20.0)
      EPG=(QG(IGP)+FG(IGP))*E2*EPS/FLOAT(IGM)
      NFN=0
C
C   *** END OF PROCESS ****
C
      RETURN
      END
