      SUBROUTINE UTSD1( AI,BI,EXFUN, EPST, X, ICON )
C
C     TSD1 IS A SSL-II ROUTINE FOR SOLUTION OF A TRANSCENDENTAL
C     EQUATION F(X) = 0
C
C     AI(INPUT)   : LOWER LIMIT OF INTERVAL (A,B)
C     BI(INPUT)   : UPPER LIMIT OF INTERVAL (A,B)
C     EXFUN(INPUT): FUNCTION NAME OF F(X) DECLARED AS EXTERNAL
C     EPST(INPUT) : TOLERANCE OF THE SOLUTION ACCURACY (>=0.0)
C     X(OUTPUT)   : APPROXIMATE SOLUTION FOUND IN THE INTERVAL (A,B)
C     ICON(OUTPUT): CONDITION CODE
C                   ICON=0: NORMAL END
C                   ICON=30000: F(A)*F(B)>0 OR EPST<0.0
C     LN1         : SIZE OF ARRAY X,Y
C     LN2         : SIZE OF ARRAY C,D,E
C
C      TO
C======================================================================
C  ... NONLINEAR EQUATION SOLVER ...
C
C THIS PROGRAM MODULE IS ASSEMBLED FOR PIJ PART OF THE SRAC CODE.
C A KERNEL PROGRAM IS QUOTED FROM A PUBLISHED SUBROUTINE
C LIBRARY [REF.2] AND INTERFACES TO SSL2 ARE ATTACHED BY M.SASAKI,
C (THE JAPAN RESEARCH INST. LTD.).
C
C  REFERENCE
C
C    1. "USERS GUIDE OF SSLII" , FUJITSU 1980
C    2. "NUMERICAL CALCULATION SOFTWARE WITH FORTRAN77",
C       T.WATANABE,M.NATORI,T.OGUNI, MARUZEN 1989
C
C----------------------------------------------------------------------
C
C  FIRST VERSION: 21 JUNE 1994 (UNTESTED !!)
C  LAST UPDATED:
C  UNIX  VERSION: 13 FEB  1996 (COMPARED WITH MSP SSL2)
C
C----------------------------------------------------------------------
C
C
C      AI,BI : LOWER & UPPER LIMIT OF SOLUTION
C      EXFUN : FUNTION NAME ( SOLVE FUN(X) = 0 )
C      EPST  : CONVERGENCE CRITERION
C      X     : SOLUTION
C      ICON  : CONDITION CODE
C
      EXTERNAL EXFUN
      DOUBLE PRECISION DX, DAI,DBI
C
      DAI = AI
      DBI = BI
C
      CALL NLBIT( DX, EXFUN, DAI, DBI, DBLE(EPST), 1000, IR, IER )
      ICON = 0
      IF( IER.NE.0 ) ICON = 30000
C
      X = DX
      RETURN
      END
