CCHAN --045 ***CITATION*** READS INPUT SECTION 036/ CF-IPTM
C
      SUBROUTINE CHAN(HOL,MJJR, HOX,NFO,NNFO,NIC,NVX,NSETVX)
C
CMSASA ... DATA WITH INITIALIZATION IS NOT PORTABLE
C     CHARACTER*4 SUBN/'CHAN'/
      CHARACTER*4 SUBN
      DATA SUBN /'CHAN'/
      WRITE(6,6000) SUBN
 6000 FORMAT(10X,'**** ERROR THIS SUBROUTINE IS OMITTED ** ',A4)
      STOP
      END
