CCPNC --056 ***CITATION*** PRINTS NUCLIDE CLASSIFICATION DATA/ CF-IPTM
C
      SUBROUTINE CPNC
C
      WRITE(6,6000) 'CPNC'
 6000 FORMAT(10X,'**** ERROR THIS SUBROUTINE IS OMITTED ** ',A4)
      STOP
      END
