CDENS --038 ***CITATION*** READS INPUT SECTION 020/ CF-IPTM
C
C     INDTOR = 0 - INITIAL INPUT,   INDTOR = 1 - PERTURBATION
C
      SUBROUTINE DENS(CONC,ZONEN,MJJR,NJJR,IDTOR, MVX,NVX,NSETVX,NVO,
     & NUO)
C
      WRITE(6,6000) 'DENS'
 6000 FORMAT(10X,'**** ERROR THIS SUBROUTINE IS OMITTED ** ',A4)
      STOP
      END
