CSSZU --128 ***CITATION*** UPDATE SUB-ZONE CONCENTRATIONS / CF-CALR
C                          AFTER NUCLIDE SEARCHES
C
      SUBROUTINE SSZU(CONC,ZONEN,NJJR,RATE,MVX,NVX,NSETVX,NVO)
C
      WRITE(6,6000) 'SSZU'
 6000 FORMAT(10X,'**** ERROR THIS SUBROUTINE IS OMITTED ** ',A4)
      STOP
      END
