CTSCL --132 ***CITATION*** TIME STEP CONTROL/ CF-CALR
C
      SUBROUTINE TSCL(A,KVX,MVX,NVX,NSETVX,NVO,IVO)
C
      WRITE(6,6000) 'TSCL'
 6000 FORMAT(10X,'**** ERROR THIS SUBROUTINE IS OMITTED ** ',A4)
      STOP
      END
