CUDTE --100 ***CITATION*** SIGMA UPDATE FOR 1,2-D/ CF-FLUX
C
      SUBROUTINE UDTE(CONC,SS1,SS2,SS3,SS4,SS5,SSC,SIG,HOL,ONEOV, SCAC,
     & NJJR,BND,BBND,ZONEN,NNXTRA,XI,XLAMDA,RATE, MVX,NVX,KVX,NSETVX,
     & NVO)
C
      WRITE(6,6000) 'UDTE'
 6000 FORMAT(10X,'**** ERROR THIS SUBROUTINE IS OMITTED ** ',A4)
      STOP
      END
