C     THIS ROUTINE IS USED ONLY IN SRAC-CITATION AND NOT USED IN COREBN
C
      SUBROUTINE CITTOS(NM,IRN,IRN1,MAT,NXREG,MATR,VOL,RVOL,KCOMP,VOLM)
CM    SUBROUTINE CITTOS(NM,IRN,IRN1,MAT,NXREG,MATR,VOL,RVOL,KCOMP )
CM   *                  KNRGNE,RPVOL,NRGNE,PVOL,MESHT             )
C
      COMMON /MAINC/ III(1000)
      DIMENSION      MAT(1),NXREG(1),MATR(1),VOL(1),RVOL(1),KCOMP(1)
C    *              ,KNRGNE(MESHT),RPVOL(IRN1),NRGNE(MESHT),PVOL(IRN1)
      DIMENSION      VOLM(1)
C
      EQUIVALENCE   (III(65),NOUT2)
C
C     CALL REAI(MAT,NM,'MAT ',' NO.' )
C
      CALL REAM(DUM,MAT,DUM,0,NM,0)
      WRITE(NOUT2,6000) (MAT(I),I=1,NM)
      IF(III(2).NE.5.AND.III(12).NE.5.AND.III(14).EQ.1) GO TO 60
      IF(IRN.EQ.0) GO TO 60
C
C     CALL REAI(NXREG,IRN,'XREG',' NO.' )
C
      CALL REAM(DUM,NXREG,DUM,0,IRN,0)
      WRITE(NOUT2,6010) (NXREG(I),I=1,IRN)
      DO 10 I=1,IRN
      VOL(I) = RVOL(I)
   10 CONTINUE
C
CADD   DEFINITION OF VOLM FOR BURNUP : 11/27/1992
C
      CALL  CLEA( VOLM , NM , 0.0 )
C
      NMM     = 0
      DO 50 I = 1,IRN
      IMM     = KCOMP(I)
      VOLM(IMM) = VOLM(IMM) + VOL(I)
      IF(I .EQ. 1) GO TO 30
      IF(IMM .EQ. NMM) GO TO 50
      DO 20 J = 1,I-1
      JMM     = KCOMP(J)
      IF(IMM .EQ. JMM) GO TO 50
   20 CONTINUE
   30 CONTINUE
      DO 40 K = I,IRN
      IF(IMM .NE. KCOMP(K)) GO TO 40
      MATR(K) = MAT(IMM)
   40 CONTINUE
      NMM = IMM
   50 CONTINUE
C
   60 CONTINUE
      RETURN
C
 6000 FORMAT(10X,'MATERIAL NO.'/(10X,10I10))
 6010 FORMAT(10X,'X-REGION NO.'/(10X,10I10))
C
      END
