CEDIN --148 ***CITATION*** PRINT CONCENTRATIONS/ CF-CNRA
C
      SUBROUTINE EDIN(CONC,ZONEN,NJJR, MVX,NVX,NSETVX,NVO)
C
      WRITE(6,6000) 'EDIN'
 6000 FORMAT(10X,'**** ERROR THIS SUBROUTINE IS OMITTED ** ',A4)
      STOP
      END
