CKOMP --032 ***CITATION*** READS INPUT SECTION 005 FOR 3-D/ CF-IPTM
C
      SUBROUTINE KOMP(ISTEP,ISK,NRGNE,NCOMP, IVX,JVX,KBVX,LVX)
C
CDEL  INTEGER RGX , MSX , ZNEX , ZDX , WZX
CDEL  PARAMETER ( RGX=100, MSX=211, ZDX=200, ZNEX=1000, WZX=100 )
      INCLUDE  'CITPMINC'
C
      COMMON/ALSUB/BLSUB(30),TITL1(18),TITL2(18),IMAX,JMAX,KBMAX,KMAX,
     & LMAX,MMAX, NMAX,IMXP1,JMXP1,KBMXP1,NSETMX,NTO,MM1VX,KM1VX,IOIN,
     & IOUT,IOSIG,IOFLX,IO1,IO2,IO3,IO4,IO7,NER(100), IX(200),INNO(100),
     &  NGC(24),IEDG(24),ITMX(24),TIMX(6), GLIM(6),NDPL(24),IEDP1(24),
     & IEDP2(24),IEDP3(24), DPLH(6),NUAC(24),EPI(6),XMIS(6),NSRH(24),
     & XSRH1(6), XTR1(WZX),XTR2(WZX),NXTR1(WZX),NXTR2(WZX),SPARE(200),
     & IXPUT(200),XPUT(200)
      COMMON/AMESH/BMESH(30),NREGI,NREGJ,NREGKB,XSHI(RGX),XSHJ(RGX),
     & XSHKB(RGX), MSHI(RGX),MSHJ(RGX),MSHKB(RGX),Y(MSX),YY(MSX), X(MSX)
     &  ,XX(MSX),Z(MSX),ZZ(MSX), ZONVOL(ZNEX),AVZPD(ZNEX),PDI(MSX),
     & PDJ(MSX) , PDK(MSX)
C
      COMMON /CRBNC/ ICONV,ICRBN,NCBSTP,AVZAB(ZNEX)
C     ICRBN IS SET IN CIT1 IF SRAC, OR CRBN IF COREBN
C     ICRBN =0 : SRAC-CITATION, ICRBN=1 : COREBN
C     NCBSTP   : BURNUP STEP IN COREBN
C
      DIMENSION NRGNE(JVX,IVX,KBVX)
      DIMENSION NCOMP(LVX)
C
      IF(NREGJ .GE. WZX  ) THEN
      WRITE(6,'(A)')
     &'THIS IS MESSAGE FROM NREGJ IN SUBROUTIN KOMP.'
      WRITE(6,'(A)')
     &'INSUFFICIENT ZONE-WORKING WZX AREA MUMBER.'
      WRITE(6,'(A,I5)')
     &'CURRENT NUMBER FOR WZX IS ',WZX
      WRITE(6,'(A)')
     &'COULD YOU PLEASE CHECK YOUR NUMBER IMMEDIATERY.'
      WRITE(6,'(A)')
     &'I AM WILLING TO YOUR QUICK RESPONSE. THANK YOU.'
       STOP
      ENDIF
CKSK
      IF(ICRBN.EQ.0) THEN
        IPRNT = ISTEP
      ELSE
        IPRNT = NCBSTP
      ENDIF
CKSK
      IF (ISK) 100,105,100
  100 IF(IPRNT.EQ.1)WRITE(IOUT,1000)
      NRE = 0
      DO 104 KBR = 1,NREGKB
      IF(IPRNT.EQ.1)WRITE(IOUT,1001)KBR
      DO 103 IR = 1,NREGI
CKSK FOR MORE 1000 ZONES IN COREBN
      IF (ICRBN.EQ.1) THEN
        READ(IOIN,1004)(NXTR1(N),N=1,NREGJ)
      ELSE
        READ(IOIN,1002)(NXTR1(N),N=1,NREGJ)
      ENDIF
      IF(IPRNT.EQ.1)WRITE(IOUT,1003)(NXTR1(N),N=1,NREGJ)
      DO 102 JR = 1,NREGJ
      NRE = NRE+1
      NCOMP(NRE) = NXTR1(JR)
      IF (NCOMP(NRE)) 101,101,102
  101 NER(14) = 14
  102 CONTINUE
  103 CONTINUE
  104 CONTINUE
  105 CONTINUE
      KB = 0
      DO 111 KBR = 1,NREGKB
      NKBPTS = MSHKB(KBR)
      DO 110 KBNR = 1,NKBPTS
      KB = KB+1
      I = 0
      DO 109 IR = 1,NREGI
      NIPTS = MSHI(IR)
      DO 108 INR = 1,NIPTS
      I = I+1
      J = 0
      NRE = (KBR-1)*NREGI*NREGJ+(IR-1)*NREGJ
      DO 107 JR = 1,NREGJ
      NJPTS = MSHJ(JR)
      NREE = NRE+JR
      DO 106 JNR = 1,NJPTS
      J = J+1
      NRGNE(J,I,KB) = NREE
  106 CONTINUE
  107 CONTINUE
  108 CONTINUE
  109 CONTINUE
  110 CONTINUE
  111 CONTINUE
      IF (ISK) 112,115,112
  112 CONTINUE
      MMAX = 0
      DO 113 NR = 1,LMAX
      MMAX = MAX0(MMAX,NCOMP(NR))
  113 CONTINUE
C
      IF(MMAX .GE. ZDX ) THEN
      WRITE(6,'(A)')
     &'THIS IS MESSAGE FROM MMAX IN SUBROUTIN KOMP.'
      WRITE(6,'(A)')
     &'INSUFFICIENT ZONE ZDX AREA MUMBER.'
      WRITE(6,'(A,I5)')
     &'CURRENT NUMBER FOR ZDX IS ',ZDX
      WRITE(6,'(A)')
     &'COULD YOU PLEASE CHECK YOUR NUMBER IMMEDIATERY.'
      WRITE(6,'(A)')
     &'I AM WILLING TO YOUR QUICK RESPONSE. THANK YOU.'
       STOP
      ENDIF
C
      IF(MMAX .GE. ZNEX) THEN
      WRITE(6,'(A)')
     &'THIS IS MESSAGE FROM MMAX IN SUBROUTIN KOMP.'
      WRITE(6,'(A)')
     &'INSUFFICIENT ZONE ZNEX AREA MUMBER.'
      WRITE(6,'(A,I5)')
     &'CURRENT NUMBER FOR ZNEX IS ',ZNEX
      WRITE(6,'(A)')
     &'COULD YOU PLEASE CHECK YOUR NUMBER IMMEDIATERY.'
      WRITE(6,'(A)')
     &'I AM WILLING TO YOUR QUICK RESPONSE. THANK YOU.'
       STOP
      ENDIF
C
  114 CALL KMOT(ISTEP,NRGNE,NCOMP, IVX,JVX,KBVX,LVX)
  115 CONTINUE
      RETURN
 1000 FORMAT(1H0/1H0,'ZONE INPUT BY REGION')
 1001 FORMAT(1H0,'  PLANE NUMBER',I3)
 1002 FORMAT(24I3)
 1003 FORMAT(1H ,30I4)
 1004 FORMAT(20I4)
      END
