C     THIS ROUTINE IS USED ONLY IN SRAC-CITATION AND NOT USED IN COREBN
C     MOVE ARRAY (A) TO (B)
C
      SUBROUTINE PERC11(A     ,B     ,MAX)
C
      DIMENSION A(MAX),B(MAX)
C
      DO 100 I = 1,MAX
      B(I) = A(I)
  100 CONTINUE
      RETURN
      END
