CTAPE --049 ***CITATION*** PROCESS MICRO. SIGMA TAPE/ CF-IPTM
C
      SUBROUTINE TAPE(NJJR, NNDI1, NNXTRA,MJJR,SS1,SS2,SS3, SS4,SS5,SSC,
     & HOL,ONEOV,XI,HOX,NFO,NNFO,NIC,SIG,KVX,NVX,NSETVX, NRVX,IRSTRT)
C
C     IRSTRT=0-NO RESTART , RESTART OTHERWISE
C
      WRITE(6,6000) 'TAPE'
 6000 FORMAT(10X,'**** ERROR THIS SUBROUTINE IS OMITTED ** ',A4)
      STOP
      END
