CTAPX --050 ***CITATION*** SETS UP NUCLIDE CLASSIFICATION/ CF-IPTM
C
      SUBROUTINE TAPX(NJJR,NVX,NSETVX)
C
      WRITE(6,6000) 'TAPX'
 6000 FORMAT(10X,'**** ERROR THIS SUBROUTINE IS OMITTED ** ',A4)
      STOP
      END
