CWNSS-C-090 ***CITATION*** WRITE START OF CYCLE CONC. ON IO24/ CF-
C
      SUBROUTINE WNSS(CONC,ZONEN,QMI, MVX,NVX,IVO,IO12,IO24,IND)
C
      WRITE(6,6000) 'WNSS'
 6000 FORMAT(10X,'**** ERROR THIS SUBROUTINE IS OMITTED ** ',A4)
      STOP
      END
