COPT1 --007***CITATION*** UPDATE ROUTINE/CF-IPTM
C             SETUP FOR MICROSCOPIC CROSS-SECTION ROUTINES
C
      SUBROUTINE OPT1(A,MEMORY,IQIN,IQUT,IO2,IO3,IO7,IO8,IO30)
C
      WRITE(6,6000) 'OPT1'
 6000 FORMAT(10X,'**** ERROR THIS SUBROUTINE IS OMITTED ** ',A4)
      STOP
      END
