CWFAC --087   WRITE FM FIXED INTERFACE DATA/ CF-WFCC
C
      SUBROUTINE WFAC(HOL,NJJR,MJJR,HOLA,HAL,IDDN, XMAS,MIIR,NIIR,NCOO,
     & NZINF,NIM,NCOMP,RVOL, NVX,NSETVX,NONNN,MVX,IVO,IFIO,LVX)
C
      WRITE(6,6000) 'WFAC'
 6000 FORMAT(10X,'**** ERROR THIS SUBROUTINE IS OMITTED ** ',A4)
      STOP
      END
