      SUBROUTINE PIJ1(RX,RPP,RDP,NPIN,THETA,TY,NREG,IRR,IXR,
     1           MAT,MAR,MATD,MMR,IA)
      COMMON / PIJ1C / NX,NY,NTPIN,NAPIN,NCELL,NM,NGR,NGA,NDPIN,IDIVP,
     1                 BETM,NX1,NY1,LOCAL(3),IXP,IYP,IZP,NDPIN1,
     2                 NDR,NDA,LL,L0,RO1,DRO,FVOL,LOCAL1,LOCAL2,RR,
     3                 ANG,LOCAL3,LOCAL4,SINB,COSB,LOCAL5
      COMMON / PIJ2C / IGT,NZ,NR,NRR,NXR,IBOUND,IDRECT,LCOUNT,IEDPIJ,
     1                 IFORM,NTTAB,NUTAB,SZ,ITYPE,IDUM1( 18)
     2                ,MM,IDUM2(967)
      COMMON /DOUBLE/
     1                 IDB   ,IGEOM ,METHOD,NTRD  ,NRRD  ,NMD
      DIMENSION RX(*),RPP(*),RDP(*),NPIN(*),THETA(*),TY(*)
     1         ,NREG(*),IRR(*),IXR(*)
     2         ,MAT(*),MAR(*),MATD(*),MMR(*),IA(NR)
      COMMON /MAINC/ IAA(2000)
      EQUIVALENCE (IAA(64),NOUT1),(IAA(65),NOUT2)
      CHARACTER*16 COMENT(14)
C
      DATA PI/3.141593/
      DATA COMENT/
     1 'T-REGION NO./SUB',
     2 'R-REGION NO./T  ',
     3 'X-REGION NO./R  ',
     4 'MATERIAL NO./R  ',
     5 'PIN X-POSITION  ',
     6 'PIN Y-POSITION  ',
     7 '                ',
     8 'NO. PINS ON RING',
     9 'R-X DIVISION    ',
     A 'ANG DIVISION    ',
     B 'Y-  DIVISION    ',
     C 'PIN SUB-DIVISION',
     D 'PIN R-POSITION  ',
     E 'PIN ANG-POSITION'/
      DO 300 I=1,NZ
      NREG(I)=I
  300 CONTINUE
      IF(NZ.EQ.NR) GO TO 310
C
      CALL REAM(NREG,NREG,NREG,0,NZ,0)
      WRITE(NOUT2,200) COMENT(1)
      WRITE(NOUT2,210) (NREG(I),I=1,NZ)
  310 DO 315 I=1,NR
      IRR(I)=I
  315 CONTINUE
      IF(NR.EQ.NRR) GO TO 320
C
      CALL REAM(IRR,IRR,IRR,0,NR,0)
      WRITE(NOUT2,200) COMENT(2)
      WRITE(NOUT2,210) (IRR(I),I=1,NR)
  320 DO 325 I=1,NRR
      IXR(I)=I
  325 CONTINUE
      IF(NRR.EQ.NXR) GO TO 330
C
      CALL REAM(IXR,IXR,IXR,0,NRR,0)
      WRITE(NOUT2,200) COMENT(3)
      WRITE(NOUT2,210) (IXR(I),I=1,NRR)
C
C   ** READ MAR : COMPULSORY
  330 CALL REAM(MAR,MAR,MAR,0,NRR,0)
      WRITE(NOUT2,200) COMENT(4)
      WRITE(NOUT2,210) (MAR(I),I=1,NRR)
      IF(IGT.NE.10 .AND. IGT.NE.14) GO TO 345
      IF(NAPIN.EQ.0) GO TO 345
C
      CALL REAM(NPIN,NPIN,NPIN,0,NAPIN,0)
      WRITE(NOUT2,200) COMENT(8)
      WRITE(NOUT2,210) (NPIN(I),I=1,NAPIN)
C   ** READ RX : COMPULSORY
  345 CALL REAM(RX,RX,RX,0,0,NX1)
      WRITE(NOUT2,200) COMENT(9)
      WRITE(NOUT2,220) (RX(I),I=1,NX1)
      IF(IGT.LE.8) GO TO 410
C   ** END INPUT FOR IGT=1-8 GEOMETRY
CKO *** INPUT FOR IGT=9 *********************
      IF(IGT.EQ.9) THEN
        IF(NAPIN.NE.0) THEN
          CALL REAM(RPP,RPP,RPP,0,0,NAPIN)
          WRITE(NOUT2,200) COMENT(13)
          WRITE(NOUT2,220) (RPP(I),I=1,NAPIN)
          WRITE(NOUT2,200) COMENT(12)
C94.5.12 IF(IDIVP.LE.1) THEN
C         CALL REAM(RDP,RDP,RDP,0,0,NDPIN1)
C         WRITE(NOUT2,220) (RDP(I),I=1,NDPIN1)
          NTPIN=(NAPIN*(NAPIN+1))/2
          CALL REAM(RDP,RDP,RDP,0,0,NDPIN1*NTPIN)
          WRITE(NOUT2,220) (RDP(I),I=1,NDPIN1*NTPIN)
C                       ENDIF
        ENDIF
      ENDIF
CKO *** INPUT FOR IGT=10 ********************
      IF(IGT.EQ.10) THEN
        IF(NAPIN.NE.0) THEN
          CALL REAM(RPP,RPP,RPP,0,0,NAPIN)
          WRITE(NOUT2,200) COMENT(13)
          WRITE(NOUT2,220) (RPP(I),I=1,NAPIN)
        ENDIF
        IF(NTPIN.NE.0) THEN
          CALL REAM(THETA,THETA,THETA,0,0,NTPIN)
          WRITE(NOUT2,200) COMENT(14)
          WRITE(NOUT2,220) (THETA(I),I=1,NTPIN)
          DO 700 I=1,NTPIN
            THETA(I)=THETA(I)*PI/180.
  700     CONTINUE
          CALL REAM(RDP,RDP,RDP,0,0,NDPIN1)
          WRITE(NOUT2,200) COMENT(12)
          WRITE(NOUT2,220) (RDP(I),I=1,NDPIN1)
        ENDIF
      ENDIF
CKO *** INPUT FOR IGT=11,12 ********************
      IF(IGT.EQ.11.OR. IGT.EQ.12) THEN
        IF(NY.GT.1) THEN
          CALL REAM(TY,TY,TY,0,0,NY)
          WRITE(NOUT2,200) COMENT(10)
          WRITE(NOUT2,220) (TY(I),I=1,NY)
          DO  720  I = 1,NY
            TY(I) = TY(I)*PI/180
  720     CONTINUE
              IF(TY(1).EQ.0.) THEN
                TY(NY1)=2.*PI
              ELSE
                TY(0)  =TY(NY)-2.*PI
              ENDIF
CKSK MODIFY FOR NY=1 97/12/10
        ELSE
          TY(1)=0.0
          TY(2)=2.0*PI
CKSK
        ENDIF
        IF(NTPIN.NE.0) THEN
          CALL REAM(RPP,RPP,RPP,0,0,NTPIN)
          WRITE(NOUT2,200) COMENT(13)
          WRITE(NOUT2,220) (RPP(I),I=1,NTPIN)
          CALL REAM(THETA,THETA,THETA,0,0,NTPIN)
          WRITE(NOUT2,200) COMENT(14)
          WRITE(NOUT2,220) (THETA(I),I=1,NTPIN)
          DO 725 I=1,NTPIN
            THETA(I)=THETA(I)*PI/180.
  725     CONTINUE
          CALL REAM(RDP,RDP,RDP,0,0,NDPIN1*NTPIN)
          WRITE(NOUT2,200) COMENT(12)
          WRITE(NOUT2,220) (RDP(I),I=1,NDPIN1*NTPIN)
        ENDIF
      ENDIF
CKO *** INPUT FOR IGT=13 ********************
      IF(IGT.EQ.13) THEN
        CALL REAM(TY,TY,TY,0,0,NY1)
        WRITE(NOUT2,200) COMENT(11)
        WRITE(NOUT2,220) (TY(I),I=1,NY1)
        IF(NTPIN.NE.0) THEN
C         **READ NTPX : X POSITION OF PIN ROD IN RX (IXP)
          CALL REAM(NPIN,NPIN,NPIN,0,NTPIN,0)
          WRITE(NOUT2,200) COMENT(5)
          WRITE(NOUT2,210) (NPIN(I),I=1,NTPIN)
          DO 730 I=1,NTPIN
            IF(NPIN(I).EQ.0) WRITE(NOUT1,377)
C           **RPP FOR IGT=13
            RPP(I)=RX(NPIN(I))
  730     CONTINUE
C         **READ NTPY : Y POSITION OF PIN RODS IN TY (IYP)
          CALL REAM(NPIN,NPIN(NTPIN+1),NPIN,0,NTPIN,0)
          WRITE(NOUT2,200) COMENT(6)
          WRITE(NOUT2,210) (NPIN(I+NTPIN),I=1,NTPIN)
          DO 735 I=1,NTPIN
            IF(NPIN(I+NTPIN).EQ.0) WRITE(NOUT1,388)
C           **THETA FOR IGT=13
            THETA(I)=TY(NPIN(I+NTPIN))
  735     CONTINUE
          CALL REAM(RDP,RDP,RDP,0,0,NDPIN1*NTPIN)
          WRITE(NOUT2,200) COMENT(12)
          WRITE(NOUT2,220) (RDP(I),I=1,NDPIN1*NTPIN)
        ENDIF
      ENDIF
CKO *** INPUT FOR IGT=14 ********************
      IF(IGT.EQ.14) THEN
        IF(NAPIN.NE.0) THEN
          CALL REAM(RPP,RPP,RPP,0,0,NAPIN)
          WRITE(NOUT2,200) COMENT(13)
          WRITE(NOUT2,220) (RPP(I),I=1,NAPIN)
          CALL REAM(RDP,RDP,RDP,0,0,NDPIN1)
          WRITE(NOUT2,200) COMENT(12)
          WRITE(NOUT2,220) (RDP(I),I=1,NDPIN1)
C     **  AUTOMATIC SPECIFICATION OF NPIN(I) FOR IGT=14
          IF(NPIN(1).EQ.0) THEN
            IP=2
            NPIN(1)=1
            IF(RPP(1).NE.0.0) IP=1
            IF(NAPIN.GE.IP) THEN
              DO 740 I=IP,NAPIN
                NPIN(I)=6*(I-IP+1)
  740         CONTINUE
              WRITE(NOUT2,200) COMENT(8)
              WRITE(NOUT2,210) (NPIN(I),I=1,NAPIN)
            ENDIF
          ENDIF
        ENDIF
      ENDIF
CKO *** INPUT FOR IGT=15 ********************
      IF(IGT.EQ.15) THEN
        CALL REAM(TY,TY,TY,0,0,NY1)
        WRITE(NOUT2,200) COMENT(11)
        WRITE(NOUT2,220) (TY(I),I=1,NY1)
        IF(NTPIN.NE.0) THEN
C         **READ NTPX : X POSITION OF PIN ROD IN RX (IXP)
          CALL REAM(NPIN,NPIN,NPIN,0,NTPIN,0)
          WRITE(NOUT2,200) COMENT(5)
          WRITE(NOUT2,210) (NPIN(I),I=1,NTPIN)
          DO 750 I=1,NTPIN
            IF(NPIN(I).EQ.NX1) WRITE(NOUT1,378) NX1
  750     CONTINUE
C         **READ NTPY : Y POSITION OF PIN RODS IN TY (IYP)
          CALL REAM(NPIN,NPIN(NTPIN+1),NPIN,0,NTPIN,0)
          WRITE(NOUT2,200) COMENT(6)
          WRITE(NOUT2,210) (NPIN(I+NTPIN),I=1,NTPIN)
          DO 755 I=1,NTPIN
            IF(NPIN(I+NTPIN).EQ.NX1) WRITE(NOUT1,389) NX1
  755     CONTINUE
          CALL REAM(RDP,RDP,RDP,0,0,NDPIN1*NTPIN)
          WRITE(NOUT2,200) COMENT(12)
          WRITE(NOUT2,220) (RDP(I),I=1,NDPIN1*NTPIN)
        ENDIF
      ENDIF
CKO *** INPUT FOR IGT=16 (SAME AS IGT=13) ***
      IF(IGT.EQ.16) THEN
        CALL REAM(TY,TY,TY,0,0,NY1)
        WRITE(NOUT2,200) COMENT(11)
        WRITE(NOUT2,220) (TY(I),I=1,NY1)
        IF(NTPIN.NE.0) THEN
C         **READ NTPX : X POSITION OF PIN ROD IN RX (IXP)
          CALL REAM(NPIN,NPIN,NPIN,0,NTPIN,0)
          WRITE(NOUT2,200) COMENT(5)
          WRITE(NOUT2,210) (NPIN(I),I=1,NTPIN)
          DO 760 I=1,NTPIN
            IF(NPIN(I).EQ.0) WRITE(NOUT1,377)
C           **RPP FOR IGT=16
            RPP(I)=RX(NPIN(I))
  760     CONTINUE
C         **READ NTPY : Y POSITION OF PIN RODS IN TY (IYP)
          CALL REAM(NPIN,NPIN(NTPIN+1),NPIN,0,NTPIN,0)
          WRITE(NOUT2,200) COMENT(6)
          WRITE(NOUT2,210) (NPIN(I+NTPIN),I=1,NTPIN)
          DO 765 I=1,NTPIN
            IF(NPIN(I+NTPIN).EQ.0) WRITE(NOUT1,388)
C           **THETA FOR IGT=16
            THETA(I)=TY(NPIN(I+NTPIN))
  765     CONTINUE
          CALL REAM(RDP,RDP,RDP,0,0,NDPIN1*NTPIN)
          WRITE(NOUT2,200) COMENT(12)
          WRITE(NOUT2,220) (RDP(I),I=1,NDPIN1*NTPIN)
        ENDIF
      ENDIF
CKO *****************************************
C
C     END OF READ
C
  410 IF(NR.EQ.NZ) GO TO 425
      MAXR=0
      DO 420 I=1,NZ
      MAXR=MAX0(NREG(I),MAXR)
  420 CONTINUE
      IF(NR.EQ.MAXR) GO TO 425
      WRITE(NOUT1,1001) NR,MAXR
      STOP
  425 IF(NR.EQ.NRR) GO TO 445
      MAXR=0
      DO 430 I=1,NR
      MAXR=MAX0(IRR(I),MAXR)
  430 CONTINUE
      IF(NRR.EQ.MAXR) GO TO 445
      WRITE(NOUT1,1002) NRR,MAXR
      STOP
  445 IF(NRR.EQ.NXR) GO TO 460
      MAXR=0
      DO 450 I=1,NRR
      MAXR=MAX0(IXR(I),MAXR)
  450 CONTINUE
      IF(NXR.EQ.MAXR) GO TO 460
      WRITE(NOUT1,1003) NXR,MAXR
      STOP
  460 CONTINUE
C   NM NUMBER OF MATERIAL USED IN PIJ ROUTINE
C   MATD(I) MATERIAL NUMBER OF I-TH MATERIAL REGION
C   MMR(I) M-REGION NUMBER OF I-TH R-REGION
C   MAT(I) M-REGION NUMBER OF I-TH T-REGION
C   MAR(I) MATERIAL NUMBER OF I-TH R-REGION (INPUT)
      IIM=0
      NM=0
      DO 475 I=1,NRR
      II=MAR(I)
      IF(I.EQ.1) GO TO 470
      IF(IIM.EQ.II) GO TO 474
      ICO=0
      DO 465 J=1,I-1
      JJ=MAR(J)
      IF(II.NE.JJ) GO TO 465
      ICO=ICO+1
      MMR(I)=MMR(J)
  465 CONTINUE
      IF(ICO.NE.0) GO TO 475
  470 CONTINUE
      NM=NM+1
      IIM=II
C *** NOTE II IS NEGATIVE IF HETEROGENEOUS MATERIAL
      MATD(NM)=II
  474 MMR(I)=NM
  475 CONTINUE
      MM=NM
      DO 480 I=1,NR
      J=IRR(I)
      MAT(I)=MMR(J)
  480 CONTINUE
C
C     SEARCH MAR WHETHER IF NEGATIVE MATERIAL NUMBER AND COUNT
C
      ISHIFT=0
      DO 510 I=1,NRR
      IA(I)=0
      IF(MAR(I).GT.0) GO TO 510
      MAR(I)=-MAR(I)
      IA(I)=1
      ISHIFT=ISHIFT+1
  510 CONTINUE
      NMD = 0
      IF(ISHIFT.EQ.0) RETURN
C     NUMBER OF R-REGIONS MODIFIED : NRRD
      NRRD=NRR+ISHIFT
C     COUNT MODIFIED T-REGIONS
      ISHIFT=0
      DO 520 I=1,NR
      J=IRR(I)
      IF(IA(J).EQ.0) GO TO 520
      ISHIFT=ISHIFT+1
  520 CONTINUE
C     NUMBER OF T-REGIONS MODIFIED : NTRD
      NTRD=NR+ISHIFT
C     NUMBER OF M-REGIONS MODIFIED : NMD
      NMD=NM+1
C
      RETURN
  200 FORMAT(1H0,9X,'===',A16,'===')
  210 FORMAT(10X,10I12)
  220 FORMAT(10X,10E12.5)
  377 FORMAT(' *** IXP MUST BE GREATER THAN 0 *** ')
  378 FORMAT(' *** IXP MUST BE LESS THAN ',I3,' ***')
  388 FORMAT(' *** IYP MUST BE GREATER THAN 0 *** ')
  389 FORMAT(' *** IYP MUST BE LESS THAN ',I3,' ***')
 1001 FORMAT(' *** ILLEGAL T-REGION SPECIFICATION *** NO. OF T-REGION='
     * ,I3,' : MAX T-REGION=',I3)
 1002 FORMAT(' *** ILLEGAL R-REGION SPECIFICATION *** NO. OF R-REGION='
     * ,I3,' : MAX R-REGION=',I3)
 1003 FORMAT(' *** ILLEGAL X-REGION SPECIFICATION *** NO. OF X-REGION='
     * ,I3,' : MAX X-REGION=',I3)
      END
