      SUBROUTINE PREHH(RX,RPP,RDP,NPIN,THETA,V,NTR,NAMEP)
      DIMENSION NPIN(1),RX(1),RDP(1),RPP(1),THETA(1 ),
     1          NTR(1),V(1),NAMEP(2,NDPIN,1)
      COMMON / PIJ1C / NX,NY,NTPIN,NAPIN,NCELL,NM,NGR,NGA,NDPIN,IDIVP,
     1                 BETM,NX1,DUM13(7),NDPIN1,NDR,NDA,
     2                 LL,L0,RO1,DRO,FVOL,I28,FL,DUM30(6),NZP
      COMMON / PIJ2C / IGT,NZ,NR,NRR,NXR,IBOUND,IDRECT,LCOUNT,IEDPIJ,
     1                 IFORM,NTTAB,NUTAB,SZ,NO1(27),
     2                 LCNREG,LCIRR,LCIXR,LCMAR,LCMAT,LCVOL,
     3                 LCVOLR,LCVOLX,LCVOLM,NO2,AA(950)
      COMMON / MAINC / DDM(63),NOUT1,NOUT2,DDM1(37),TITLE(18),DDM2(380)
      COMMON /IGEOM/   DUMMY2( 5),PINR,RANGE,DUMMY3,NPINZ
      DATA PI/3.141593/,SQ3/1.73205/
C  **
C  ** PRR ARE MERGED INTO RX
C  ** TEST TOTAL NUMBER OF PIN RODS
      IF(NAPIN.NE.0)   THEN
      NT=0
      DO 25 I=1,NAPIN
      NT=NT+NPIN(I)
   25 CONTINUE
      IF(NT.NE.NTPIN) THEN
      WRITE(NOUT1,3013) 'NPIN TOTAL',NT,NTPIN
      GO TO 1000
                      ENDIF
                        ENDIF
C **  NTR(I) POSITION IN RX'S OF I-TH PIN ROD RING
C **         PROVIDED IN MERGRX
C
C **  NAMEP(IO,NDPIN,NAPIN) MODERATOR REGION NUMBER OF PIN
      CALL CLEA(NAMEP,2*NDPIN*NAPIN,0)
C
C **  NZA  TOTAL NUMBER OF SUB-REGIONS
      NZA=NX+NDPIN*NAPIN*IDIVP
      IF(IDIVP.EQ.2 .AND. RPP(1).EQ.0.)         NZA=NZA-NDPIN
      IF(IDIVP.EQ.2 .AND. RPP(NAPIN).EQ.RX(NX1))NZA=NZA-NDPIN
   38 CONTINUE
      IF(NZA.NE.NZ) THEN
      WRITE(NOUT1,3013) 'TOT-S-REG',NZ,NZA
      GO TO 1000
                    ENDIF
      NZP=NZA-NX
C     NZP : STARTING REGION NUMBER IN MODERATOR REGIONS
C **  VOLUME OF HEXAGONAL SUB-REGIONS
      DO 40 I=1,NX
      J=I+NZP
      V(J)=2.*SQ3*(RX(I+1)**2-RX(I)**2)
   40 CONTINUE
C **  VOLUME OF MODERATOR SUB-REGIONS
      IF(NAPIN.EQ.0)  GO TO  260
      IF(IDIVP.EQ.0) THEN
      IJ=0
      DO 45 IP=1,NAPIN
      AN=NPIN(IP)
      NNR=NTR(IP)+NZP
      V(NNR)=V(NNR)-       AN*PI*RDP(NDPIN1)**2
C **  VOLUME OF PIN ROD  SUB-REGIONS  IDIVP=0
      RR=0.
      DO 44 ND=1,NDPIN
      IJ=IJ+1
      RP=RDP(ND+1)**2
      V(IJ)=AN*PI*(RP-RR)
      NAMEP(1,ND,IP)=IJ
      NAMEP(2,ND,IP)=IJ
      RR=RP
   44 CONTINUE
   45 CONTINUE
                    ELSE
      IJ=0
      DO 55 IP=1,NAPIN
      AN=FLOAT(NPIN(IP)/2)
      BN=AN-1.
      CN=AN+1.
      NNR=NTR(IP)+NZP-1
      IF(RPP(IP).GT.0.)
     *V(NNR  )=V(NNR  )-BN*PI*RDP(NDPIN1)**2
      IF(RPP(IP).LT.RX(NX1))
     *V(NNR+1)=V(NNR+1)-CN*PI*RDP(NDPIN1)**2
   55 CONTINUE
      IF(IDIVP.EQ.1) THEN
      DO 65 IP=1,NAPIN
      AN=NPIN(IP)
      RR=0.
      DO 64 ND=1,NDPIN
      IJ=IJ+1
      RP=RDP(ND+1)**2
C **  VOLUME OF PIN ROD  SUB-REGIONS  IDIVP=1
      V(IJ)=AN*PI*(RP-RR)
      IF(RPP(IP).GT.0.)
     *         NAMEP(1,ND,IP)=IJ
      IF(RPP(IP).LT.RX(NX1))
     *         NAMEP(2,ND,IP)=IJ
      RR=RP
   64 CONTINUE
C
   65 CONTINUE
                      ELSE
      DO 76 IP=1,NAPIN
      AN=FLOAT(NPIN(IP)/2)
      BN=AN-1.
      IF(RPP(IP).EQ.0.) BN=0.
      CN=AN+1.
      IF(RPP(IP).EQ.RX(NX1))CN=0.
      IF(BN.EQ.0.) GO TO 74
      DO 73 ND=1,NDPIN
      IJ=IJ+1
      NDI=NDPIN1-ND
      V(IJ)=BN*PI*(RDP(NDI+1)**2-RDP(NDI)**2)
      NAMEP(1,NDI,IP)=IJ
   73 CONTINUE
   74 IF(CN.EQ.0.) GO TO 76
      RR=0.
      DO 75 ND=1,NDPIN
      IJ=IJ+1
      RP=RDP(ND+1)**2
      V(IJ)=CN*PI*(RP-RR)
      NAMEP(2,ND,IP)=IJ
      RR=RP
   75 CONTINUE
   76 CONTINUE
                    ENDIF
                        ENDIF
C
C *** PREPARE RPP AND THETA FOR EACH PIN ROD
C
      NTB=NTPIN
      DO 200 IA=1,NAPIN
      IAINV=NAPIN-IA+1
      RR=RPP(IAINV)
      NTB=NTB-NPIN(IAINV)
      NP=NPIN(IAINV)/6
C     IF(NP.EQ.0) GO TO 210
      NT=NTB
      DO 150 I=1,NP
      NT=NT+1
      RPP(NT)=RR*SQRT(1.+(FLOAT(NP+2-2*I)/FLOAT(NP))**2/3.)
      THETA(NT)=PI/6.-ATAN(FLOAT(NP+2-2*I)/FLOAT(NP)/SQ3)
      DO 140 J=1,5
      N=NT+J*NP
      THETA(N)=THETA(NT)+PI/3.*FLOAT(J)
      RPP(N)=RPP(NT)
  140 CONTINUE
  150 CONTINUE
  200 CONTINUE
  220 WRITE(NOUT2,3011) (I,RPP(I)  ,I=1,NTPIN)
      WRITE(NOUT2,3012) (I,THETA(I),I=1,NTPIN)
C
C     ***** CHECK  PIN + PIN OVERLAPPING
C
      DO 250 I=1,NTPIN-1
      DO 240 J=I+1,NTPIN
      D2 = RPP(I)**2 + RPP(J)**2 - 2*RPP(I)*RPP(J)
     *    *COS(THETA(I) - THETA(J) )
      RR = 2.*RDP(NDPIN1)
      IF ( RR .LT. SQRT(D2) ) GO TO 240
      WRITE(6,6060) I,RPP(I),THETA(I),J,RPP(J),THETA(J)
      ISW=ISW+1
  240 CONTINUE
  250 CONTINUE
 6060 FORMAT(1H ,'***** ERROR**** ',I3,'-TH PIN ON (RPP =',E12.5,
     * 'AND THETA ',F8.5,')  ACROSSED BY ',I3,'-TH PIN ON (RPP =',E12.5,
     * 'AND THETA ',F8.5)
C
  260 CONTINUE
C
CXX   SEVERAL QUANTITIES FOR NUMERICAL INTEGRATION
      IF(RPP(1).EQ. 0.) THEN
      NPINZ=1
      PINR=RDP(NDPIN1)
                        ELSE
      NPINZ=0
                        ENDIF
      SZ=4.*SQ3*RX(NX1)
      FL=RX(NX1)
      NDR=NX*NGR
      RANGE=2.0/SQ3*FL
      FVOL=1.0
C     DRO=2./SQ3*FL/FLOAT(NDR)
      IF(BETM.GT.PI/3.+0.001) THEN
      WRITE(NOUT1,3014) BETM
 3014 FORMAT('  *** RANGE FOR ANGULAR INTEGRATION INDICATED AS ',
     * F7.4,' RADIAN EXCEEDS THE PROPER RANGE'/
     * 7X,'THE PROGRAM ASSUMES AS PI/3 RADIAN')
      BETM=PI/3.
                              END IF
      RETURN
*3010 FORMAT(10X'MODIFIED RX''S'  /(10X,I3,1H),1PE11.4,I3,1H),   E11.4
*    1 ,I3,1H),E11.4,I3,1H),E11.4,I3,1H),E11.4,I3,1H),E11.4,I3,1H),E11.4
*    2,I3,1H),E11.4))
 3011 FORMAT(10X,'RADIAL POSITION OF  PIN RODS'/
     1                                (10X,I3,1H),1PE11.4,I3,1H),   E11.
     14,I3,1H),E11.4,I3,1H),E11.4,I3,1H),E11.4,I3,1H),E11.4,I3,1H),E11.4
     2,I3,1H),E11.4))
 3012 FORMAT(10X,'ANGULAR POSITION OF  PIN RODS'/
     1                               (10X,I3,1H),  F11.5,I3,1H),   F11.5
     1 ,I3,1H),F11.5,I3,1H),F11.5,I3,1H),F11.5,I3,1H),F11.5,I3,1H),F11.5
     2,I3,1H),F11.5))
 3013 FORMAT(10X,'** UNMATCH IN ',A,2I5 )
 1000 STOP
      END
