C      PREXY FOR IGT=13   PERIODIC BOUNDARY CONDITION IDIVP=0,1
      SUBROUTINE PREXY(RX,RPP,RDP,NPTX,NPTY,THETA,TY,VMESH,MESHX,
     1  MESHP,NZONE,IXR,MMR,IRR)
      DIMENSION NZONE(1),RX(1),TY(1),MESHX(NX,NY),IXR(1),
     1        VMESH(1),IRR(1),MMR(1),NPTX(NTPIN),RPP(NTPIN),THETA(NTPIN)
     2       ,NPTY(NTPIN),RDP(NDPIN1,NTPIN),MESHP(NDPIN,NX1,NY1)
      COMMON / PIJ1C / NX,NY,NTPIN,NAPIN,NCELL,NM,NGR,NGD,NDPIN,
     1                 IDIVP,BETM,NX1,NY1,DUM(6),NDPIN1,
     2                 NDR,NDA,LL,L0,RO1,DRO,FVOL,IDUM28(8),NMESH
      COMMON / PIJ2C / IGT,NZ,NR,NRR,NXR,IBOUND,IDRECT,ICOUNT,IEDPIJ,
     1                 IFORM,NTTAB,NUTAB,SZ
      COMMON /MAINC/   DUMMY1(63),NOUT1,NOUT2
      COMMON /IGEOM/   DUMMY2( 5),PINR,RANGE,DUMMY3,NPINZ
      DATA PI/3.14159/
C
      IJ=1
      DO 100 J=1,NY
      DO 100 I=1,NX
      MESHX(I,J)=IJ
      VMESH(IJ )=(TY(J+1)-TY(J))*(RX(I+1)-RX(I))
      IF(NTPIN.EQ.0 .OR. IDIVP.NE.0)  IJ=IJ+1
  100 CONTINUE
      IF(NTPIN.NE.0 .AND. IDIVP.EQ.0) THEN
                                      VMESH(1)=TY(NY1)*RX(NX1)
                                      ELSE
                                     IJ=IJ-1
                                     ENDIF
      NMESH=IJ
      IF(NTPIN.EQ.0) GO TO 350
      CALL ICLEA(MESHP,NDPIN*NX1*NY1,0)
      DO 300 N=1,NTPIN
      FACT=0.
      VP=PI*RDP(NDPIN1,N)**2/4.
C
      IF(NPTX(N).GT.1   .AND. NPTY(N).GT.1  ) THEN
      FACT=FACT+0.25
      IJ1=NPTX(N)-1+NX*(NPTY(N)-2)
      IF(IDIVP.EQ.0) IJ1=1
                                              VMESH(IJ1)=VMESH(IJ1)-VP
                                              ENDIF
      IF(NPTX(N).LT.NX1 .AND. NPTY(N).GT.1  ) THEN
      FACT=FACT+0.25
      IJ2=NPTX(N)  +NX*(NPTY(N)-2)
      IF(IDIVP.EQ.0) IJ2=1
                                              VMESH(IJ2)=VMESH(IJ2)-VP
                                              ENDIF
      IF(NPTX(N).GT.1   .AND. NPTY(N).LT.NY1) THEN
      FACT=FACT+0.25
      IJ3=NPTX(N)-1+NX*(NPTY(N)-1)
      IF(IDIVP.EQ.0) IJ3=1
                                              VMESH(IJ3)=VMESH(IJ3)-VP
                                              ENDIF
      IF(NPTX(N).LT.NX1 .AND. NPTY(N).LT.NY1) THEN
      FACT=FACT+0.25
      IJ4=NPTX(N)  +NX*(NPTY(N)-1)
      IF(IDIVP.EQ.0) IJ4=1
                                              VMESH(IJ4)=VMESH(IJ4)-VP
                                              ENDIF
      RR=0.
      DO 210 NP=1,NDPIN
      RP=RDP(NP+1,N)**2
      IJ=IJ+1
      VMESH(IJ)=PI*(RP-RR)*FACT
      RR=RP
  210 MESHP(NP,NPTX(N),NPTY(N))=IJ
  300 CONTINUE
  350 IF(NZ.NE.IJ) THEN
                   WRITE(NOUT1,9100) NZ,IJ
                   STOP
                   ENDIF
C
      NDR=NGR*((NX+NY)/2)
      IF(NDR     .GT. 2000) WRITE(NOUT1,9101)
C     RADIAL INTEGRATION  HALF OF DIAGONAL
      RANGE =SQRT(RX(NX1)**2+TY(NY1)**2)/2.
C     DRO =RANGE/FLOAT(NDR)
      RO1= RANGE
      FVOL=1.0
      SZ=2.*(RX(NX1)+TY(NY1))
      IF(BETM.GT.3.14) THEN
           BETM=PI
C                       ELSE
C          BETM=PI/2.
                         ENDIF
C
      PITCH=RX(NX1)/2.
      DO 70 I=1,NX1
      RX(I)=RX(I)-PITCH
   70 CONTINUE
      PITCH=TY(NY1)/2.
      DO 75 I=1,NY1
      TY(I)=TY(I)-PITCH
   75 CONTINUE
      DO 80 NT=1,NTPIN
      RPP(NT)=RX(NPTX(NT))
      THETA(NT)=TY(NPTY(NT))
   80 CONTINUE
CXQ   FIND WHETHER OR NOT A PIN IS LOCATED AT THE CENTER
CXZ   SCAN WHICH IS THE PIN LOCATED AT THE CENTER
               NPINZ=0
       DO 90  NT=1,NTPIN
          IF(ABS(RPP(NT)).LE. 1.E-4
     & .AND. ABS(THETA(NT)).LE. 1.E-4) THEN
               NPINZ=1
               PINR=RDP(NDPIN1,NT)
                                       ENDIF
   90 CONTINUE
C
C
C * * PRINT MESH NUMBER AND REGION NUMBER
      IF(NTPIN.EQ.0) CALL IPRTX('S-RE','GION',NX,NY,MESHX)
      IF(NTPIN.NE.0) CALL IPRTXP('S-REGION',MESHX,MESHP)
      IF(NR.EQ.NZ) GOTO 141
      IJ=1
      DO 135 J=1,NY
      DO 135 I=1,NX
      IT=NZONE(IJ)
      MESHX(I,J) = IT
      IF(NTPIN.EQ.0 .OR. IDIVP.NE.0)  IJ=IJ+1
  135 CONTINUE
      IF(NTPIN.EQ.0) GO TO 140
      IJ=NMESH
      DO 136 NT=1,NTPIN
      DO 136 ND=1,NDPIN
      IJ=IJ+1
      IT=NZONE(IJ)
      MESHP(ND,NPTX(NT),NPTY(NT))=IT
  136 CONTINUE
C     DO 140 J=1,NY1
C     DO 140 I=1,NX1
C     IF(J.EQ.NY1 .OR. I.EQ.NX1) GO TO 133
C     IJ=MESHX(I,J)
C     MESHX(I,J)=NZONE(IJ)
C 133 IF(NTPIN.EQ.0) GO TO 139
C     DO 135 ND=1,NDPIN
C     IJ=MESHP(ND,I,J)
C     IF(IJ.NE.0) MESHP(ND,I,J)=NZONE(IJ)
C 135 CONTINUE
C 139 CONTINUE
  140 CONTINUE
      IF(NTPIN.EQ.0) CALL IPRTX('S-RE','GION',NX,NY,MESHX)
      IF(NTPIN.NE.0) CALL IPRTXP('T-REGION',MESHX,MESHP)
C
C
C ** CHECK PERIODIC CONDITION FOR PIN ROD REGION ON BOUNDARIES
C
  141 IF(NTPIN.EQ.0) GO TO 450
      IERR=0
      DO 410 I=1,NX1
      DO 410 ND=1,NDPIN
      IF(MESHP(ND,I,1).NE. MESHP(ND,I,NY1)) THEN
      WRITE(NOUT1,9102) ND,I,MESHP(ND,I,1),MESHP(ND,I,NY1)
      IERR=IERR+1
      ENDIF
  410 CONTINUE
 9102 FORMAT (' *** PERIODIC CONDITION NOT SATISFIED FOR PIN RODS ON TOP
     * AND BOTTOM BOUNDARIES'/ '      ILLEGAL REGIONS ON PIN DIV=',I2
     * ,'  COLUMN=',I2,' T-REGIONS =',2I3)
C
      DO 420 J=1,NY1
      DO 420 ND=1,NDPIN
      IF(MESHP(ND,1,J).NE. MESHP(ND,NX1,J))  THEN
      WRITE(NOUT1,9103) ND,J,MESHP(ND,1,J),MESHP(ND,NX1,J)
      IERR=IERR+1
      ENDIF
  420 CONTINUE
 9103 FORMAT (' *** PERIODIC CONDITION NOT SATISFIED FOR PIN RODS ON RIG
     *HT AND LEFT BOUNDARIES'/ '       ILLEGAL REGIONS ON PIN DIV=',I2
     * ,'  LINE=',I2,' T-REGIONS =',2I3)
      IF(IERR.GT.0) STOP
  450 CONTINUE
      IF(NRR.EQ.NR) GOTO 151
      IJ=1
      DO 145 J=1,NY
      DO 145 I=1,NX
      IT=NZONE(IJ)
      MESHX(I,J) = IRR(IT)
      IF(NTPIN.EQ.0 .OR. IDIVP.NE.0)  IJ=IJ+1
  145 CONTINUE
      IF(NTPIN.EQ.0) GO TO 150
      IJ=NMESH
      DO 146 NT=1,NTPIN
      DO 146 ND=1,NDPIN
      IJ=IJ+1
      IT=NZONE(IJ)
      MESHP(ND,NPTX(NT),NPTY(NT))=IRR(IT)
  146 CONTINUE
C     DO 150 J=1,NY1
C     DO 148 I=1,NX1
C     IF(J.EQ.NY1 .OR. I.EQ.NX1) GO TO 143
C     IJ=MESHX(I,J)
C     MESHX(I,J)=IRR(IJ)
C 143 IF(NTPIN.EQ.0) GO TO 148
C     DO 145 ND=1,NDPIN
C     IJ=MESHP(ND,I,J)
C     IF(IJ.NE.0) MESHP(ND,I,J)=IRR(IJ)
C 145 CONTINUE
C 148 CONTINUE
  150 CONTINUE
      IF(NTPIN.EQ.0) CALL IPRTX('R-RE','GION',NX,NY,MESHX)
      IF(NTPIN.NE.0) CALL IPRTXP('R-REGION',MESHX,MESHP)
  151 IF(NXR.LT.2 .OR. NXR.EQ.NRR) GOTO 171
      IJ=1
      DO 155 J=1,NY
      DO 155 I=1,NX
      IT=NZONE(IJ)
      MESHX(I,J) = IXR(IRR(IT))
      IF(NTPIN.EQ.0 .OR. IDIVP.NE.0)  IJ=IJ+1
  155 CONTINUE
      IF(NTPIN.EQ.0) GO TO 170
      IJ=NMESH
      DO 160 NT=1,NTPIN
      DO 160 ND=1,NDPIN
      IJ=IJ+1
      IT=NZONE(IJ)
      MESHP(ND,NPTX(NT),NPTY(NT))=IXR(IRR(IT))
  160 CONTINUE
C     DO 170 J=1,NY1
C     DO 168 I=1,NX1
C     IF(J.EQ.NY1 .OR. I.EQ.NX1) GO TO 163
C     IREG=MESHX(I,J)
C     MESHX(I,J)=IXR(IREG)
C 163 IF(NTPIN.EQ.0) GO TO 168
C     DO 165 ND=1,NDPIN
C     IJ=MESHP(ND,I,J)
C     IF(IJ.NE.0) MESHP(ND,I,J)=IXR(IJ)
C 165 CONTINUE
C 168 CONTINUE
  170 CONTINUE
      IF(NTPIN.EQ.0) CALL IPRTX('X-RE','GION',NX,NY,MESHX)
      IF(NTPIN.NE.0) CALL IPRTXP('X-REGION',MESHX,MESHP)
  171 IF(NM.EQ.NRR) GO TO 9999
      IF(NM.EQ.  1) GO TO 9999
      IJ=1
      DO 180 J=1,NY
      DO 180 I=1,NX
      IREG=NZONE(IJ)
      MESHX(I,J) = MMR(IRR(IREG))
      IF(NTPIN.EQ.0 .OR. IDIVP.NE.0)  IJ=IJ+1
  180 CONTINUE
      IF(NTPIN.EQ.0) GO TO 195
      IJ=NMESH
      DO 190 NT=1,NTPIN
      DO 190 ND=1,NDPIN
      IJ=IJ+1
      IT=NZONE(IJ)
      IR=IRR(IT)
      MESHP(ND,NPTX(NT),NPTY(NT))=MMR(IR)
  190 CONTINUE
      CALL IPRTXP('M-REGION',MESHX,MESHP)
      GO TO 9999
  195 CALL IPRTX('M-RE','GION',NX,NY,MESHX)
 9999 CONTINUE
      RETURN
 9100 FORMAT(' **** UNMATCH IN TOTAL S-REGION NUMBER ***',2I10)
 9101 FORMAT(30H**** TIME CONSUMING CASE       )
      END
