CDCAY --043 ***CITATION*** READS INPUT SECTION 034/ CF-IPTM
C
      SUBROUTINE DCAY(HOL,NJJR,MJJR, NVX,NSETVX)
C
      WRITE(6,6000) 'DCAY'
 6000 FORMAT(10X,'**** ERROR THIS SUBROUTINE IS OMITTED ** ',A4)
      STOP
      END
