CHEAT --141 ***CITATION*** CUMULATIVE HEAT/CF-OUTC
C
      SUBROUTINE HEAT(UTILE,SOURE, IVX,JVX,KBVX)
C
      WRITE(6,6000) 'HEAT'
 6000 FORMAT(10X,'**** ERROR THIS SUBROUTINE IS OMITTED ** ',A4)
      STOP
      END
