C     THIS ROUTINE IS USED ONLY IN SRAC-CITATION AND NOT USED IN COREBN
C     PERTURBATION INPUT CONTROL
C
      SUBROUTINE PERTIN(NOUT2)
C
      COMMON /PERTCM/ P(1),MEMPET,IPERT,ICASE,LSAMPL,LIOPT,LIDOPT,LBKLE,
     &                LXYZ,LBKLGP,LAST,LTERM,LSIG2,LSAC2,LXI2,LBUF,NBUF
C
C     MEMPET : PERTURBATION STORAGE RESERVED
C     IPERT  : PERTURBATION CALCULATION INDICATER IF =0 NON,=1 YES
C     ICASE  : NUMBER OF CASE PERTURBATION CALCULATION
C     LSAMPL : LOCATION OF PERTURBED SAMPLE NAME ON MACOR FILE
C     LIOPT  : LOCATION OF PERTURBED ZONE/REGION SPECIFICATION OPTION
C     LIDOPT : LOCATION OF DIFFUSION COEFFICIENT SELECTION OPTION
C     LBKLE  : LOCATION OF BUCKLING DATA
C     LXYZ   : LOCATION OF PERTURBED REGION SPECIFICATION
C     LBKLGP : LOCATION OF GROUPE DEPENDENT BUCKLING DATA POINTER
C     LAST   : USED MEMORY OF COMMON /PERTCM/
C       FOLLOWING AREA ARE USED COMMON /WORK/ , VARIABLE SETED IN
C        SUBROUTINE CNIO (CITATION)
C     LTERM  : LOCATION FOR UTILTY STORAGE FOR PERTURBATION CALCULATION
C     LSIG2  : LOCATION FOR PERTURBED MACRO CROSS-SECTION
C     LSCAC2 : LOCATION FOR SCATTERING MATRIX OF PERTURBED MATERIAL
C     LXI2   : LOCATION FOR FISSION SPECTRA OF PERTURBED MATERIAL
C     LBUF   : LOCATION OF UTILITY STORAGE FOR PERTURBED MACRO CROSS-
C              SECTION PREPARATION
C     NBUF   : USABLE SIZE OF UTILITY STORAGE PERTURBED MACRO CROSS-
C              SECTION PREPARATION
C
      CALL REAM(DUM,ICASE,DUM,0,1,0)
      WRITE(NOUT2,2000) ICASE
      IF (ICASE.GT.0) GO TO 100
      WRITE(NOUT2,3000)
      STOP
  100 CONTINUE
      LSAMPL = 21
      LIOPT  = LSAMPL + 2*ICASE
      LIDOPT = LIOPT  + ICASE
      LBKLE  = LIDOPT + ICASE
      LXYZ   = LBKLE  + ICASE
      LBKLGP = LXYZ   + 6*ICASE
      LAST   = LBKLGP + ICASE
      IF (LAST-1.LE.MEMPET) GO TO 110
      WRITE(NOUT2,3010) LAST,MEMPET
      STOP
  110 CONTINUE
      CALL PERTI1(P(LSAMPL),P(LIOPT) ,P(LIDOPT),P(LBKLE) ,P(LXYZ)  ,
     1            P(LBKLGP),P(1)     ,P(LXYZ)  ,
     2            ICASE    ,NOUT2    ,MEMPET   ,LAST                )
      RETURN
 2000 FORMAT(6X,'NUMBER OF CASES FOR PERTURBATION CALCULATION',I41     )
 3000 FORMAT('0***ERROR*** NUMBER OF CASES IS NEGETIVE OR ZERO'        )
 3010 FORMAT('0***ERROR*** USED STORAGE =',I7,' ALLOCATED STORAGE =',I7,
     &       '  COMMON /PERTCM/  '                                     )
      END
