CRERT --151 ***CITATION*** PRINT NUCLIDE REACTION RATES/ CF-CALR,OUTC
C
      SUBROUTINE RERT(CONC,NJJR,RATE,SS1,SS2,SS4,SS5,B4,ZONVOL,ZONEN,
     & HOL,RATET,RATAT,NNXTRA,KVX,MVX,NVX,NSETVX,NVO,IO1X16)
C
      WRITE(6,6000) 'PERT'
 6000 FORMAT(10X,'**** ERROR THIS SUBROUTINE IS OMITTED ** ',A4)
      STOP
      END
