CRNSS --091  READ CONC. FROM FUEL MANAGE. INTERFACE I/O
C
      SUBROUTINE RNSS(CONC,ZONEN,QMI, NVX,MVX,IVO,IO12,IO26,IO27,IO29)
C
      WRITE(6,6000) 'RNSS'
 6000 FORMAT(10X,'**** ERROR THIS SUBROUTINE IS OMITTED ** ',A4)
      STOP
      END
