CRODX --94.1 ***CITATION*** CONTROLS ROD MOVEMENT         /CF-CALR
C
      SUBROUTINE RODX(CONC,MJJR,NCOMP,P2,P2E,NRGNE,BBND, NVX,MVX,NSETVX,
     & LVX,JVX,IVX,KBVX,JIVX,KVX)
C
      WRITE(6,6000) 'RODX'
 6000 FORMAT(10X,'**** ERROR THIS SUBROUTINE IS OMITTED ** ',A4)
      STOP
      END
