CCLAS --037 ***CITATION*** READS INPUT SECTION 018/ CF-IPTM
C
      SUBROUTINE CLAS
C
CMSASA
C     CHARACTER*4 SUBN/'CLAS'/
      CHARACTER*4 SUBN
      DATA SUBN /'CLAS'/
      WRITE(6,6000) SUBN
 6000 FORMAT(10X,'**** ERROR THIS SUBROUTINE IS OMITTED ** ',A4)
      STOP
      END
