CCMXS 152.1 ***CITATION*** COLLAPSE AND PUNCH MACRO X-SECT
C     CALLED BY OUTC
      SUBROUTINE CMXS(SIG,SCAC,XI,BAL,SSC,B4,ZONVOL,KVX,MVX)
C
CMSASA
C     CHARACTER*4 SUBN/'CMXS'/
      CHARACTER*4 SUBN
      DATA SUBN/'CMXS'/
      WRITE(6,6000) SUBN
 6000 FORMAT(' *** THE SUBROUTINE ',A4,'IS OMITTED : CHECK NGC5 ** ')
      STOP
      END
