CGEDT --061 ***FUEL MANAGEMENT** CORE ALLOCATION AND START /CF - IPTM
C
      SUBROUTINE GEDT(A,MEMORY,IOS)
C
      WRITE(6,6000) 'GEDT'
 6000 FORMAT(10X,'**** ERROR THIS SUBROUTINE IS OMITTED ** ',A4)
      STOP
      END
