CIPRT --046 ***CITATION*** READS INPUT SECTION 040/ CF-IPTM
C
      SUBROUTINE IPRT(CONC,ZONEN,MJJR,NJJR,HOL, MVX,NVX,NSETVX,NVO,NUO)
C
      WRITE(6,6000) 'IPRT'
 6000 FORMAT(10X,'**** ERROR THIS SUBROUTINE IS OMITTED ** ',A4)
      STOP
      END
