CRSET --94.2 ***CITATION*** REASSIGN MICROSCOPIC CROSS SECTION SETS
C
      SUBROUTINE RSET(NRSET1,NST,NCY,NNDI1,SS1,SS2,SS3,SS4,SS5,SSC, KVX,
     & NVX,NSETVX,NJJR)
C
      WRITE(6,6000) 'RSET'
 6000 FORMAT(10X,'**** ERROR THIS SUBROUTINE IS OMITTED ** ',A4)
      STOP
      END
