CTABL --149 ***CITATION*** PRINT NUCLIDE LOSS TABLE/ CF-CNRA
C
      SUBROUTINE TABL(RATE,MJJR,MVX,NVX,NSETVX,IO1X16)
C
      WRITE(6,6000) 'TABL'
 6000 FORMAT(10X,'**** ERROR THIS SUBROUTINE IS OMITTED ** ',A4)
      STOP
      END
