      SUBROUTINE UGTENV(ENVNAM,ENVVAL)
C=========================================================
C  GET CHARACTERS ALLOCATED TO ENVIROMENTAL PARAMETER
C  ORIGINAL FUNCTION IS "GETENV", BUT IT IS SYSTEM-DEPENDENT
C  EX. SETENV FILE1 /USER/OKUMURA/KEISUKE.DATA
C      INPUT  : ENVNAM = 'FILE1'
C      OUTPUT : ENVVAL = '/USER/OKUMURA/KEISUKE.DATA'
C
C=========================================================
      CHARACTER*(*)  ENVNAM, ENVVAL
      CHARACTER*200  ENVTMP
C
      ENVTMP = ' '
      ENVVAL = ' '
      LEN1 = INDEX(ENVNAM,' ') - 1
      LEN2 = 200
C WE HOPE MAX CHARACTER SIZE OF ENVTMP < 200 (199 + BLANCK)
      CALL GETENV(ENVNAM,LEN1,ENVTMP,LEN2)
      LENG = INDEX(ENVTMP,' ') - 1
      ENVVAL(1:LENG) = ENVTMP(1:LENG)
      RETURN
      END
