      SUBROUTINE UCLCKM(ICPU)
C
C     CLOCKM IS ORIGINALLY A FACOM BUILTIN SERVICE ROUTINE TO RETURN
C     CURRENT CPU TIME(MILI-SEC) IN 4-BYTE INTEGER.
C     ICPU(OUTPUT)  : CURRENT USED CPU TIME (MILI-SEC) IN 4-BYTE INTEGER
C
      CALL UCLOCK(ICPU)
      ICPU = ICPU * 1000
      RETURN
      END
