CKOOP-VP-114 ***CITATION*** PHIBAR,SOURCE,CONVERGENCE FOR 3-D/ CF-KLUX
C
CHH
      SUBROUTINE KOOP( P2E,SOURE,NRGNE,XII,IVX,JVX,KBVX,KVX, LVX,JIVX,
     & XLAMDA,SIG,PVOL,NCOMP,MVX,WKS)
CHH   SUBROUTINE KOOP( P2E,SOURE,NRGNE,XII,IVX,JVX,KBVX,KVX, LVX,JIVX,
CHH  & XLAMDA,SIG,PVOL,NCOMP,MVX)
C
CDEL  INTEGER RGX , MSX , ZNEX , ZDX , WZX
CDEL  PARAMETER ( RGX=100, MSX=211, ZDX=200, ZNEX=1000, WZX=100 )
      INCLUDE  'CITPMINC'
C
      REAL*8 XII,XLAMDA
C
      COMMON/ALSUB/BLSUB(30),TITL1(18),TITL2(18),IMAX,JMAX,KBMAX,KMAX,
     & LMAX,MMAX, NMAX,IMXP1,JMXP1,KBMXP1,NSETMX,NTO,MM1VX,KM1VX,IOIN,
     & IOUT,IOSIG,IOFLX,IO1,IO2,IO3,IO4,IO7,NER(100), IX(200),INNO(100),
     &  NGC(24),IEDG(24),ITMX(24),TIMX(6), GLIM(6),NDPL(24),IEDP1(24),
     & IEDP2(24),IEDP3(24), DPLH(6),NUAC(24),EPI(6),XMIS(6),NSRH(24),
     & XSRH1(6), XTR1(WZX),XTR2(WZX),NXTR1(WZX),NXTR2(WZX),SPARE(200),
     & IXPUT(200),XPUT(200)
      COMMON/AFLUX/BFLUX(30),KXMN8,NIT,NIIT,NIIIT,JXP1,KSCT1,KSCT2,
     & ISTART,IEP, VRGP1,VRGP2,VRGP3,VRG1,VRG2,VRGK1,VRGK2,XABS,PROD,
     & XLEK,RMX,RMN,XKEF1,XKEF2,XKEF3,EXFC1,EXFC2,EXFC3, NI3,IEXTR,
     & IRECV,VRGABS,LO3,LO4,XLAMDB,EPI1,EPI2, BETTA,SUMXI,IX25,IX28,I,J,
     &  KB,K,ITMAX,ITIME, BET(MSX),DEL(MSX)
C
      DIMENSION XII(KVX,MVX)
      DIMENSION SIG(KVX,MVX,10),PVOL(LVX),NCOMP(LVX)
CC    DIMENSION P2E(JIVX ,KBVX,KVX), SOURE(JVX, IVX, KBVX),NRGNE(JVX,
CC   & IVX,KBVX)
      REAL      P2E(JIVX*KBVX,KVX),SOURE(JIVX*KBVX)
      INTEGER   NRGNE(JIVX*KBVX)
CHHHH
      REAL      WKS(JIVX*KBVX)
CHHHH
C
C     IF (IX(24).GT.0) GO TO 106
C     DO 105 KB = 1,KBVX
C     DO 104 I = 1,IVX
C     NN1= (I-1)*JVX
C     DO 103 J = 1,JVX
C     N1= NN1 + J
C     L = NRGNE(J,I,KB)
C     M = NCOMP(L)
C     CKSO = 0.0
C     DO 100 K = 1,KVX
C     T1 = P2E(N1 ,KB,K)
C     CKSO = CKSO + SIG(K,M,4)*T1
C 100 CONTINUE
C     IF (SPARE(98).EQ.0.0) GO TO 102
C     DO 101 K=1,KVX
C     CKSO = CKSO + XLAMDA*SIG(K,M,8)*P2E(N1,KB,K)
C 101 CONTINUE
C 102 CONTINUE
C     SOURE(J,I,KB) = CKSO*PVOL(L)
C 103 CONTINUE
C 104 CONTINUE
C 105 CONTINUE
C     GO TO 111
C 106 CONTINUE
C     DO 110 KB = 1,KBVX
C     DO 109 I = 1,IVX
C     NN1= (I-1)*JVX
C     DO 108 J = 1,JVX
C     N1= NN1 + J
C     CKSO = 0.0
C     DO 107 K = 1,KVX
C     T1 = P2E(N1 ,KB,K)
C     CKSO = CKSO+XII(K)*T1
C 107 CONTINUE
C     SOURE(J,I,KB) = CKSO
C 108 CONTINUE
C 109 CONTINUE
C 110 CONTINUE
C 111 CONTINUE
CC
CC
C
CHH
      JIKBXX=JIVX*KBVX
      DO 200 IH=1,JIKBXX
  200 WKS(IH)=0.0
C
      IF(IX(24).GT.0) THEN
        DO 220 K=1,KVX
        DO 210 IH=1,JIKBXX
        L=NRGNE( IH )
        M=NCOMP( L )
  210   WKS(IH)=XII(K,M)*P2E(IH,K)+WKS(IH)
  220   CONTINUE
        DO 230 IH=1,JIKBXX
  230   SOURE(IH)=WKS(IH)
C
        ELSE IF(SPARE(98).EQ.0.0) THEN
          DO 250 K=1,KVX
          DO 240 IH=1,JIKBXX
  240     WKS(IH)=SIG(K,NCOMP(NRGNE(IH)),4)*P2E(IH,K)+WKS(IH)
  250     CONTINUE
          DO 260 IH=1,JIKBXX
  260     SOURE(IH)=WKS(IH)*PVOL(NRGNE(IH))
C
          ELSE
            DO 280 K=1,KVX
            DO 270 IH=1,JIKBXX
  270       WKS(IH)=SIG(K,NCOMP(NRGNE(IH)),4)*P2E(IH,K)+WKS(IH)
  280       CONTINUE
            DO 300 K=1,KVX
            DO 290 IH=1,JIKBXX
  290       WKS(IH)=XLAMDA*SIG(K,NCOMP(NRGNE(IH)),8)
     &                 *P2E(IH,K)+WKS(IH)
  300       CONTINUE
            DO 310 IH=1,JIKBXX
  310       SOURE(IH)=WKS(IH)*PVOL(NRGNE(IH))
C
      ENDIF
CHH
      RETURN
      END
