      SUBROUTINE GEOMXR(RX,RPP,RDP,THETA,TY,IM,IP,D,DX,DY)
C *** GENERAL X-Y TWO DIMENSIONAL LATTICE CELL OF REFLECTIVE CONDITION
C *** IGT=16, IDIVP=0,1 EXCLUSIVE USE
C *** IDIVP=2 C.F. PREXZ,GEOMXZ
C     AT AXISESC *** X AND Y OUTER BOUND. COND. IS ISO, REFL, AND BLACK
      DIMENSION RX(1),TY(1),D(1),IM(1),IP(1),DX(1),DY(1)
     *         ,RPP(NTPIN),THETA(NTPIN),RDP(NDPIN1,NTPIN)
      COMMON /PIJ1C/ NX,NY,NTPIN,IDUM4(5),NDPIN,IDIVP,BETM,NX1,NY1
     1             ,IDUM14( 3),IXP,IYP,IZP,NDPIN1,IDUM21(2),LL,IDUM24(6)
     *             ,RO,ANG,IDUM32(2),SINB,COSB,IBASE
      COMMON /PIJ2C/ IDUM1(8),IEDPIJ,IDUM2,NTTAB
      COMMON /MAINC/ DUMY1(63),NOUT1,NOUT2,DUMMY2(435)
C     IF(IEDPIJ.GE.3)
C    &WRITE(6,*) ' RO=',RO,' ANG=',ANG,' IBASE=',IBASE
C     IBASE=NX*NY BUT IF(IDIVP.EQ.0 .AND. NTPIN.NE.0) IBASE=1
C     IBASE : LARGEST S-REGION NUMBER OF XY DIVISION
      IDY=1
C     ANGULAR RANGE IS ASSUMED WITHIN (0,90) DEG
C     IF(SINB.LT.0.)IDY=-1
      IDX=1
C     IF(COSB.LT.0.)IDX=-1
C * * CROSS WITH X=RX(I) 2*NX+1 POINTS IN DESCENDING ORDER INTO DX ARRAY
      DXZ=RO*SINB/COSB
      DYZ=-RO*COSB/SINB
      DO 10 I=1,NX
C     I1 POSITION OF POSITIVE RX(I+1)
      I1=I+NX+1
      I2=NX-I+1
C     I2 POSITION OF NEGATIVE RX(I+1)
      DX(I1)=DXZ-RX(I+1)/COSB
      DX(I2)=DXZ+RX(I+1)/COSB
   10 CONTINUE
      DX(NX1)=DXZ
CH    WRITE(6,*) '   DX=',(DX(I),I=1,2*NX+1)
C * * CROSS WITH Y=TY(I) 2*NY1+1 POINTS IN DESCENDING ORDER INTO DY ARR
   11 DO 20 I=1,NY
      I1=I+NY+1
      I2=NY-I+1
      DY(I1)=-TY(I+1)/SINB + DYZ
      DY(I2)= TY(I+1)/SINB + DYZ
   20 CONTINUE
      DY(NY1)=DYZ
CH    WRITE(6,*) '   DY=',(DY(I),I=1,2*NY+1)
C
C * * ARRANGE DX DY IN DESCENDING ORDER INTO D ARRAY WITH S-REG NUMBER
   21 IX=1
      IY=1
      L=1
      IXB=-NX1
      IYB=-NY1
      IXC=IXB
      IYC=IYB
   35 IJK=1
      IF(DX(IX).LT.DY(IY)) IJK=2
      GO TO (40,50),IJK
   40 D(L)=DX(IX)
      IXB=IXB+1
      IF(IXB.EQ.0) IXB=1
      IM(L)=(IABS(IYB)-1)*NX+IABS(IXB)
      IP(L)=IM(L-1)
      IX=IX+1
      IF(IX.GT.2*NX+1) GO TO 60
C     Y POSITION STILL REMAIN AT INITIAL
      IF(IYB.EQ.IYC)GOTO 35
      L=L+1
      GO TO 35
   50 D(L)=DY(IY)
      IYB=IYB+1
      IF(IYB.EQ.0) IYB=1
      IM(L)=(IABS(IYB)-1)*NX+IABS(IXB)
      IP(L)=IM(L-1)
      IY=IY+1
      IF(IY.GT.2*NY+1) GO TO 60
C     X POSITION STILL REMAIN AT INITIAL
      IF(IXB.EQ.IXC) GO TO 35
      L=L+1
      GO TO 35
   60 LL=L
      IF(LL.GT.1 .AND. IEDPIJ.GE.3 ) THEN
      WRITE(6,'(A,I2,A,10I12/(11X,10I12))')
     & '  1LL=',LL-1,'IM=',(IM(L),L=1,LL-1)
      WRITE(6,'(A,10F12.5/(13X,10F12.5))')
     &'        D(L)=',(D(L),L=1,LL)
                                     ENDIF
      IF(NTPIN.EQ.0) GO TO 90
      IF(L.EQ.1) GO TO 90
C     IF(IDIVP.EQ.0) NO XY DIVISION
      IF(IDIVP.NE.0) GO TO 80
      D(2)=D(L)
      IM(1)=1
      IP(2)=1
      LL=2
C
C   SCAN NTPIN RODS IF THE RAY TRACES
   80 DO  86 NT=1,NTPIN
      PA=RPP(NT)
CXR   PA X POSITION OF PIN NT
      PB=THETA(NT)
CXR   PB Y POSITION OF PIN NT
      DO  85 II=1,2
CXR   REPEAT TWICE FOR MIRROR REFLECTIVE GEOMETRY
      DO  83 JJ=1,2
      DAB=ABS(PB*COSB-PA*SINB+RO)
      DMID=-PA*COSB-PB*SINB
         DXX=DXZ-PA/COSB
         DYY=DYZ-PB/SINB
      DO 81 NDP=NDPIN1,2,-1
      RR=RDP(NDP,NT)
      IF(RR.LE.DAB) GO TO  82
      DET=SQRT(RR**2-DAB**2)
      DPA=DMID+DET
      DPB=DMID-DET
      IZN=IBASE+NDP-1+NDPIN*(NT-1)
CXZ
      IF(DXX.GT.DYY)         THEN
        IF(DXX.GT.DPA)     THEN
C         IF(DPB.GT.DYY) THEN
CXZ    PATTERN 2 TO 2
C                        ELSE
CXZ    PATTERN 2 TO 4
C                        ENDIF
                           ELSE
          IF(DPB.GT.DYY) THEN
CXZ    PATTERN 1 TO 2
                         ELSE
CXZ    PATTERN 1 TO 2 TO 4
C           IZN=NDP-1+NSRPIN(LOCP)
            CALL INSERT(DXX,IZN,IZN,DYY,D,IM,IP)
                         ENDIF
                           ENDIF
                               ELSE
        IF(DYY.GT.DPA)     THEN
C         IF(DPB.GT.DXX) THEN
CXZ    PATTERN 3 TO 3
C                        ELSE
CXZ    PATTERN 3 TO 4
C                        ENDIF
                           ELSE
          IF(DPB.GT.DXX) THEN
CXZ    PATTERN 1 TO 3
                         ELSE
CXZ    PATTERN 1 TO 3 TO 4
C           IZN=NDP-1+NSRPIN(LOCP)
C     IZN=IBASE+NDP-1+NDPIN*(NT-1)
            CALL INSERT(DYY,IZN,IZN,DXX,D,IM,IP)
                         ENDIF
                           ENDIF
                             ENDIF
C     IZN=IBASE+NDP-1+NDPIN*(NT-1)
      CALL INSERT(DPA,IZN,IZN,DPB,D,IM,IP)
   81 CONTINUE
   82 IF(ABS(PB).LT.1.E-3) GO TO 84
CXR   IF ON Y-AXIS
      PB=-PB
   83 CONTINUE
   84 IF(ABS(PA).LT.1.E-3) GO TO 86
CXR   IF ON X-AXIS
      PA=-PA
   85 CONTINUE
   86 CONTINUE
   90 LL=LL-1
      IF(IEDPIJ.GE.3) THEN
      WRITE(6,'(A,I2,A,10I12/(11X,10I12))')
     & '  2LL=',LL,'IM=',(IM(L),L=1,LL)
*     WRITE(6,'(A,I2,A,10I12/(11X,10I12))')
*    & '  IJK=',IJK,'IP=',(IP(L),L=2,LL+1)
      WRITE(6,'(A,10F12.5/(13X,10F12.5))')
     &'        D(L)=',(D(L),L=1,LL+1)
                      ENDIF
      IF(LL.EQ.0) RETURN
      DO 100 L=1,LL
      D(L)=D(L)-D(L+1)
  100 CONTINUE
      IF(IEDPIJ.GE.3) THEN
      WRITE(6,'(A,10F12.5/(13X,10F12.5))')
     &'       XD(L)=',(D(L),L=1,LL)
                      ENDIF
      IF(LL.GT.NTTAB) GO TO 300
      GO TO (110,120),IJK
  110 IXP=IXP+1
CXY   RO=RO-SIGN(2.*SINB,SINB*COSB)*RX(NX1)
      RO=RO-     2.*SINB           *RX(NX1)
      RETURN
  120 IYP=IYP+1
CXY   RO=RO+SIGN(2.*COSB,SINB*COSB)*TY(NY1)
      RO=RO+     2.*COSB           *TY(NY1)
      RETURN
  300 WRITE(NOUT1,301) LL,NTTAB
      STOP
  301 FORMAT(1H0,9X,15HTABLE OVERFLOW   ,2I10)
      END
