      SUBROUTINE CHAINP(X1,X2,Y1,Y2,CLG,LAST,CMM)
      XX=X1
      YY=Y1
       CALL PLOT(XX,YY,3)
      DX=X2-X1
      DY=Y2-Y1
      TLENGS=SQRT(DX**2+DY**2)
      TL=CLG-CMM
      TLENG=TLENGS-TL
      IF(TLENG.LT.0.)  GO TO  300
      IF(CMM.EQ.0.)      GO TO 250
      RA=TL/TLENGS
      XX=X1+RA*DX
      YY=Y1+RA*DY
      CALL PLOT(XX,YY,LAST+2)
      LAST=ABS(FLOAT(LAST)-1.6)
  250 CONTINUE
      NC=TLENG/CLG
      IF(NC.EQ.0)  GO TO  46
      DX=X2-XX
      DY=Y2-YY
      LAST1=ABS(FLOAT(LAST)-1.6)
      DX=DX/FLOAT(NC)
      DY=DY/FLOAT(NC)
      DO 45 I=1,NC,2
      XA=XX+DX*FLOAT(I)
      YA=YY+DY*FLOAT(I)
      CALL PLOT(XA,YA,LAST+2)
      IF(I.GE.NC)  GO TO 40
      XB=XX+DX*FLOAT(I+1)
      YB=YY+DY*FLOAT(I+1)
      CALL PLOT(XB,YB,LAST1+2)
      IF(I.NE.NC) GO TO  45
      LAST=ABS(FLOAT(LAST1)-1.6)
      GO TO  45
   40 LAST=ABS(FLOAT(LAST)-1.6)
   45 CONTINUE
   46 CONTINUE
      CMM=AMOD(TLENG,CLG)
      IF(CMM.EQ.0.) GO TO  50
      IF(LAST+2.EQ.3)  GO TO  201
      CALL PLOT(X2,Y2,LAST+2)
  201 CONTINUE
   50 CONTINUE
      RETURN
  300 CONTINUE
      CMM=CMM+TLENGS
      IF(LAST+2.EQ.3)  GO TO  101
      CALL PLOT(X2,Y2,LAST+2)
  101 CONTINUE
      RETURN
      END
