C             EDCALL              LEVEL=1        DATE=81.11.14
      SUBROUTINE EDCALL
C
      COMMON /TW1C/ DD(1),LIM1,IA(210)
      COMMON /WORK/AAA(1),LIM2,AA(130)
      DIMENSION D(212),A(132)
      EQUIVALENCE (D(1),DD(1)),(AAA(1),A(1))
      EQUIVALENCE (D(105),LAST1),(A(52),LAST2),(D(121),LTQS),
     &(D(161),NEXTRA),(D(168),IEDIT(1)),(D(118),LTOXS),(D(162),NEDIT)
C
      DIMENSION ERRMG(4) , IEDIT(2)
C
      EQUIVALENCE (IA(4),IGM),(IA(5),IM),(IA(6),JM),(IA(11),IEVT),
     &(IA(13),MT),(IA(15),MS),(IA(16),IHT),(IA(18),IHM),(IA(31),IEDOPT),
     &(IA(56),IMJM),(IA(57),MM),(IA(58),NM),(IA(60),IP),(IA(61),JP),
     &(IA(64),IT),(IA(65),JT),(IA(66),ITJT),(IA(75),IMJP),(IA(76),IPJM),
     &(IA(77),ITP),(D(171),LIHX),(D(172),LIHY),(A(61),LC),(A(64),LA3),
     &(A(65),LA4),(A(66),LA5),(A(67),LQ),(D(173),LXDF),(D(174),LYDF),
     &(A(76),LFL),(D(181),LDC),(D(184),LDX),(D(186),LDYA),(A(80),LYH),
     &(D(190),LWM),(A(81),LWE),(D(195),LMN),(D(196),LMC),(D(197),LMD),
     &(D(202),LXRA),(D(203),LYRA)
      EQUIVALENCE (IEDIT(1),NZ), (IEDIT(2),NORMZ)
C
C     MATERIAL MESH DEFINITION
C
      EQUIVALENCE (IA(25),IMC),(IA(27),JMC),(D(175),LIHXC),
     &(D(176),LIHYC),(D(177),LDXC),(D(178),LDYC),(D(179),LDYAC),
     &(D(82),MESH)
C
CSASA REAL*8 ERRMG
      CHARACTER*8 ERRMG
C
      DATA ERRMG/'STORAG','E EXCE','EDED O','N EDIT'/
C
      LXFX=NM*ITJT
      CALL REED (NEDIT,0,0.0,0,4)
      CALL REED (NEDIT,0,NEDS,ITEMP,3)
C
C     ASSIGN TEMPORARY STORAGE
C
      LTA3=LA3
      LTA4=LA4
C
C     GENERATE NEW ADRESSES FOR EDIT ARRAYS
C
      LX=LC
      LY=LX+IT
      LC=LY+JT
      LQ=LC+LTOXS
      LFL=LQ+LTQS
      LNED=LFL+ITJT*NM
      LFU=LNED+IMC*JMC
      LFD=LFU+IMC*(JMC+1)
      LFR=LFD+IMC*(JMC+1)
      LFLL=LFR+(IMC+1)*JMC
      LA3=LFLL+(IMC+1)*JMC
      LA4=LA3+ITP*MESH
      LV1=LA4+ITP*MESH
      LV2=LV1+ITP*MM*MESH
      LV3=LV2+ITP*MM*MESH
      LV4=LV3+ITP*MM*MESH
      LMIC=LV4+ITP*MM*MESH
C
C     CHECK STORAGE OVERFLOW
C
      IF ( LMIC .GT. LAST2) CALL ERROR ( 3, ERRMG, 4 )
C
C     STORE ARRAYS TO BE SAVED
C
      CALL REED (NEXTRA,0,0.0,0,4)
CKSK  CALL RITE (NEXTRA,0,A(LYH),JT,3)
CKSK  CALL RITE (NEXTRA,0,A(LA5),IT,3)
      CALL RITE (NEXTRA,0,AAA(LYH),JT,3)
      CALL RITE (NEXTRA,0,AAA(LA5),IT,3)
  100 IF (MESH.EQ.0) GO TO 110
CKSK  CALL RITE (NEXTRA,0,A(LTA3),ITP,3)
CKSK  CALL RITE (NEXTRA,0,A(LTA4),ITP,3)
      CALL RITE (NEXTRA,0,AAA(LTA3),ITP,3)
      CALL RITE (NEXTRA,0,AAA(LTA4),ITP,3)
  110 CONTINUE
C
C     CLEAR STORAGE AREA
C
CKSK  CALL CLEARW(0.0,A(LX ),LMIC)
      CALL CLEARW(0.0,AAA(LX ),LMIC)
C
C     READ REQUIRED ARRAYS INTO NEW STORAGE LOCATIONS
C
      CALL REED (NEXTRA,0,0.0,0,4)
CKSK  CALL REED (NEXTRA,0,A(LY),ITEMP,3)
CKSK  CALL REED (NEXTRA,0,A(LX),ITEMP,3)
      CALL REED (NEXTRA,0,AAA(LY),ITEMP,3)
      CALL REED (NEXTRA,0,AAA(LX),ITEMP,3)
  120 IF (MESH.EQ.0) GO TO 130
CKSK  CALL REED (NEXTRA,0,A(LA3),ITEMP,3)
CKSK  CALL REED (NEXTRA,0,A(LA4),ITEMP,3)
      CALL REED (NEXTRA,0,AAA(LA3),ITEMP,3)
      CALL REED (NEXTRA,0,AAA(LA4),ITEMP,3)
C     GENERATE FLOWS FOR MATERIAL MESH
C
      LH2=LV1+IT*MM
      LH4=LV3+IT*MM
CKSK  CALL GENFLO ( A(LV1),A(LV2),A(LV3),A(LV4),A(LV1),A(LH2),A(LV3),
CKSK &A(LH4),A(LY),A(LA3),A(LA4),D(LWM),A(LWE),A(LFD),A(LFU),A(LFR),
CKSK &A(LFLL),D(LDX),D(LDYA),ITP,IT,MM,IMC,IMC+1,JMC,JMC+1,LV1,LV3 )
      CALL GENFLO ( AAA(LV1),AAA(LV2),AAA(LV3),AAA(LV4),AAA(LV1),
     &AAA(LH2),AAA(LV3),AAA(LH4),AAA(LY),AAA(LA3),AAA(LA4),
     &DD(LWM),AAA(LWE),AAA(LFD),AAA(LFU),AAA(LFR),AAA(LFLL),
     &DD(LDX),DD(LDYA),ITP,IT,MM,IMC,IMC+1,JMC,JMC+1,LV1,LV3 )
  130 CONTINUE
      MN=0
CKSK  IF ((IEDOPT.EQ.2).OR.(IEDOPT.EQ.4)) CALL REED ( NEDIT,0,A(LMIC),
      IF ((IEDOPT.EQ.2).OR.(IEDOPT.EQ.4)) CALL REED ( NEDIT,0,AAA(LMIC),
     &MN,3 )
      IF (NEDS.LE.0) GO TO 150
      DO 140 NN=1,NEDS
      CALL REED (NEDIT,0,IEDIT,ITEMP,3)
      LR=LMIC+MN
      LL=LR+NZ
      LT=LL+NZ
      LB=LT+NZ
      LN=LB+NZ
      LS=LN+NZ
C **** LF TEMPORALY AREA ASSIGNED ***********
      LF=LS+NZ
      LAC=LF+NZ
      LRG=LAC+NZ*IHT
      LLG=LRG+NZ
      LTG=LLG+NZ
      LBG=LTG+NZ
      LNG=LBG+NZ
      LSG=LNG+NZ
      LFG=LSG+NZ
      LACG=LFG+NZ
      LV=LACG+NZ*IHT
      LASTED=LV+ITJT
      ICLEAR=LRG-LR
C
C     CHECK STORAGE OVERFLOW
C
      IF ( LASTED .GT. LAST2) CALL ERROR ( 3, ERRMG, 4 )
C
C     CALL EDIT
C
CKSK  CALL EDITOR ( D(LDC),A(LNED),A(LAC),A(LFR),A(LFLL),A(LFU),A(LFD),
CKSK &A(LFL),A(LQ),A(LACG),A(LV),A(LC),A(LX),A(LY),A(LR),A(LL),A(LT),
CKSK &A(LB),A(LN),A(LS),A(LF),A(LRG),A(LLG),A(LTG),A(LBG),A(LNG),A(LSG),
CKSK &A(LFG),D(LDX),D(LDYA),A(LMIC),D(LMN),D(LMC),D(LMD),IMC,JMC,NZ,IHT,
CKSK &IMC+1,JMC+1,MN,IT,JT,IHM,MT,ICLEAR,NORMZ,NN,D(LXDF),D(LYDF),NM )
      CALL EDITOR ( DD(LDC),AAA(LNED),AAA(LAC),AAA(LFR),AAA(LFLL),
     &AAA(LFU),AAA(LFD),AAA(LFL),AAA(LQ),AAA(LACG),AAA(LV),AAA(LC),
     &AAA(LX),AAA(LY),AAA(LR),AAA(LL),AAA(LT),AAA(LB),AAA(LN),AAA(LS),
     &AAA(LF),AAA(LRG),AAA(LLG),AAA(LTG),AAA(LBG),AAA(LNG),AAA(LSG),
     &AAA(LFG),DD(LDX),DD(LDYA),AAA(LMIC),DD(LMN),DD(LMC),DD(LMD),
     &IMC,JMC,NZ,IHT,IMC+1,JMC+1,MN,IT,JT,IHM,MT,ICLEAR,NORMZ,NN,
     &DD(LXDF),DD(LYDF),NM )
  140 CONTINUE
  150 CONTINUE
      RETURN
      END
