      FUNCTION    FFFF(X)
C
CKSK  COMMON /DOUBLE/ LDOUBL(50),ISWRES(450),C
CDEL  PARAMETER ( MXDBHT =   450 )
      INCLUDE  'DBHETINC'
      COMMON /DOUBLE/ LDOUBL(50),ISWRES(MXDBHT),C
C
      FFFF = X*EXP(-X) - C
C
      RETURN
      END
