C             INPT14              LEVEL=1        DATE=81.11.14
      SUBROUTINE INPT14
C
      COMMON /TW1C/ DD(1),LIM1,IA(210)
      DIMENSION D(212)
      EQUIVALENCE (D(1),DD(1))
C
C     INPUT INTEGERS
C
      EQUIVALENCE (IA(2),ISCT),(IA(3),ISN)
C
C     COMPUTED INTEGERS
C
      EQUIVALENCE (IA(57),MM),(IA(58),NM),(IA(74),ISCP)
C
C     FIRST WORD ADDRESSES
C
      EQUIVALENCE (D(187),LW),(D(188),LCM),(D(189),LCE),(D(190),LWM),
     &(D(191),LP1),(D(192),LP2),(D(193),LP3),(D(194),LP4),
     &(D(198),LF)
C
C    /FWBGN1/ , /FWBGN2/,  /LOCAL/ , /UNITS/
C
      EQUIVALENCE (D(144),ISNT),(D(105),LAST),(D(154),LIMIT),
     &(D(142),NERROR)
C
C     MOST INPUT PLACED SAFELY AWAY.  OBTAIN SN CONSTANTS
C     CHECK FOR INPUT SN CONSTANTS ( ISN .LT. 0 )
C
      IF (ISNT.GT.0) GO TO 100
C
C     READ SN CONSTANTS FROM A STANDARD INTERFACE FILE
C
CKSK  CALL IFINSN (D(LCM),D(LCE),D(LW),ISN,MM)
      CALL IFINSN (DD(LCM),DD(LCE),DD(LW),ISN,MM)
      GO TO 110
CK100 CALL SNCON (D(LCM),D(LCE),D(LW),ISN,MM)
  100 CALL SNCON (DD(LCM),DD(LCE),DD(LW),ISN,MM)
C
C     TEMPORARY STORAGE REQUIREMENTS
C
  110 LTEMP=LF+ISCT+ISCT+1
      LIMIT=LTEMP+MM*ISCP**2
C     CLEAR TEMPORARY STORAGE
CKSK  CALL CLEARW(0.0, D(LF),LIMIT-LF)
      CALL CLEARW(0.0, DD(LF),LIMIT-LF)
      IF ( NERROR .EQ. 2 ) GO TO 120
C     CALCULATE ANISOTROPIC SCATTER COEFFIECIENTS
CKSK  CALL PNGEN (D(LTEMP),D(LP1),D(LCM),D(LCE),D(LWM),D(LF),ISCT,MM,
CKSK &NM,ISCP )
      CALL PNGEN (DD(LTEMP),DD(LP1),DD(LCM),DD(LCE),DD(LWM),DD(LF),
     &ISCT,MM,NM,ISCP )
C     CLEAR STORAGE
  120 CONTINUE
CKSK  IF (LAST.LE.LIM1) CALL CLEARW(0.0, D(LWM),LAST-LWM+1)
      IF (LAST.LE.LIM1) CALL CLEARW(0.0, DD(LWM),LAST-LWM+1)
      RETURN
      END
