      SUBROUTINE PCOIN3(MTNAME,TEMP  ,NISO  ,IDENT ,IRES  ,DN    ,NCOR,
     1                  ISWF  ,MCODE ,NCODEL,SSFEFC,IRCONT,ISWFIS)
C
      CHARACTER*4     TIL,ID,NFILE,IDTMP
C
      COMMON /PCOWK1/ TIL(18),ID(2)
      COMMON /PCOWK2/ KCOMP,KCOMPF,DELBEF,KSREG,KMAT,KNMAX,KRES,NPROB,
     1                NDOUBL,NOUT1,NOUT2,NBB,NBH,MAXN,MAXP,KDAN,
     2                KPIJ1,KPIJ2,ESCAPA,ESCAPF,GUZAI,IPLOT,MAIN(2)
      COMMON /PCOWK3/ A(14500),LOCAM(8)
C
      COMMON /UMC001/ LIBTYP,NEF,ISTART,NG,NOMESH,KFGP,NGMAX,MAXINT,NSET
      COMMON /UMC002/ ENERGY(75),EE(47),NI(46),INTNO(46),
     +                NXG(10),NFI(10),NOIG(10),MST(46),MEND(46)
      COMMON /UMC005/ SIG1D(3,46)
      COMMON /UMCTMP/ NTEMP,TMPSET(40),IDTMP(40)
      COMMON /PDSPDS/ BUFFER(540),IFLSW,NFILE(3),ECODE,TEMPPP
C
CMOD  PARAMETER   ( MXNISO = 110 , MAXNG = 107  , MAXMT3 = 6 )
      INCLUDE  'BMICRINC'
      COMMON   /MICCOM/ EFFMIC(MAXNG,MAXMT3,MXNISO),LENEFF
C
      DIMENSION       NCOR(KCOMP),ISWF(KCOMP),TEMP(KCOMP),NISO(KCOMP),
     1                IRES(KNMAX,KCOMP),DN(KNMAX,KCOMP),
     2                MCODE(KNMAX,KCOMP),ISWFIS(KRES),
     3                SSFEFC(3,NG,KRES,KCOMP),IRCONT(6,KRES)
C
      CHARACTER*8     IDENT(KNMAX,KCOMP),MTNAME(KCOMP),NCODEL(KMAT)
      CHARACTER*8     MEMBER
C
C ----- INITIAL SET
C
      CALL ICLEA ( ISWFIS  , KRES  , 0    )
      CALL ICLEA ( IRCONT  , KRES*6, 0    )
      LENG   = 3*NG*KRES*KCOMP
      CALL  CLEA ( SSFEFC  , LENG  , 1.0  )
CUNIX DNLIMT = 1.0001E-40
      DNLIMT = 1.0001E-35
C
C ---- GET EFFECTIVE MICROSCOPIC X-SECTION IF EXIST
C
      IFLSW   = 1
CKSK  NFILE(1)= 4HMICR
      NFILE(1)= 'MICR'
CKSK  NFILE(2)= 4HEF
      NFILE(2)= 'EF  '
      IST     = ISTART-1
C
      DO 200 LOP = 1 , KCOMP
      L          = NCOR(LOP)
      IF(L.LE.0.OR.L.GT.KCOMPF) GO TO 200
      IF(ISWF(LOP).NE.3)        GO TO 200
      MMK        = NISO(LOP)
      IF(MMK.LE.0)              GO TO 200
C
      MEMBER       = MTNAME(LOP)(1:4)// 'BMIC'
      LENG         = MAXNG*MAXMT3*MMK
      CALL   READ( MEMBER , EFFMIC , LENG )
C
      DO   150   M = 1 , MMK
      IF(IRES(M,LOP).NE.2)          GO TO 150
      IF(DN(M,LOP).LE.DNLIMT)       GO TO 150
      MPOS         = MCODE(M,LOP)
      IF(MPOS.LE.0.OR.MPOS.GT.KRES) GO TO 150
C
      DO 100 I=1,NG
      SSFEFC(1,I,MPOS,LOP) = EFFMIC(IST+I,4,M)
      SSFEFC(2,I,MPOS,LOP) = EFFMIC(IST+I,2,M)
      SSFEFC(3,I,MPOS,LOP) = EFFMIC(IST+I,1,M)
CM    IF(IFISS.EQ.1) SSFEFC(2,I,MPOS,LOP) =A(ISTF)
CM    IF(ICAPT.EQ.1) SSFEFC(3,I,MPOS,LOP) =A(ISTC)
  100 CONTINUE
  150 CONTINUE
  200 CONTINUE
C
C-----GET INFINITE CROSS SECTION FROM USER'S MCROSS
C
      IFLSW=1
CKSK  NFILE(1)=4HUMCR
      NFILE(1)='UMCR'
CKSK  NFILE(2)=4HOSS
      NFILE(2)='OSS '
C
      DO 500 LOP = 1 , KCOMP
      L          = NCOR(LOP)
      IF(L.LE.0.OR.L.GT.KCOMPF) GO TO 500
      IF(ISWF(LOP).NE.3)        GO TO 500
      MMK        = NISO(LOP)
      IF(MMK.LE.0)              GO TO 500
      RTEMP      = TEMP(LOP)
C
      DO 400   M = 1 , MMK
      IF(IRES(M,LOP).NE.2)          GO TO 400
      MPOS       = MCODE(M,LOP)
      DNTEMP     = DN   (M,LOP)
      IF(MPOS.LE.0.OR.MPOS.GT.KRES) GO TO 400
      MEMBER       = NCODEL(MPOS)
      MEMBER (1:1) = 'C'
      MEMBER (5:5) = '0'
C
                   NTPOS     = 0
                   DO 210 NT = 1 , NTEMP
                   SAVE      = RTEMP/TMPSET(NT) - 1.000
                   IF(ABS(SAVE).LT.0.001) NTPOS = NT
  210              CONTINUE
C
      IF(NTPOS.EQ.0) GO TO  1101
CMOD  MEMBER (8:8) = IDTMP(NTPOS) (1:1)
      IF(MEMBER(6:7).EQ.'00')
     @     MEMBER (8:8) = IDTMP(NTPOS) (1:1)
      CALL SEARCH(MEMBER,LENG,ISW)
CWRITE
CDEL  WRITE(NOUT1,FMT='(12H NAME ISW : ,A8,I6)')  MEMBER,ISW
CDEL  WRITE(NOUT2,FMT='(12H NAME ISW : ,A8,I6)')  MEMBER,ISW
CWRITE
      IF(ISW.EQ.1)   GO TO 1201
C
      CALL READ ( MEMBER , IRCONT(1,MPOS) , 5 )
      ISWFIS(MPOS)   = IRCONT(4,MPOS)
      ISAVE          = IRCONT(6,MPOS)
      IF(ISAVE.GT.0.AND.ISAVE.NE.NTPOS) GO TO 1301
C
      IRCONT(6,MPOS) = NTPOS
      IENDUN         = IRCONT(5,MPOS)
      IF(IENDUN.EQ.0) THEN
                      LENG = 3*NG
                      CALL CLEA( SSFEFC(1,1,MPOS,LOP) , LENG , 1.0 )
                      GO TO 400
                      ENDIF
C
      IF(DNTEMP.LE.DNLIMT) THEN
                      LENG = 3*NG
                      CALL CLEA( SSFEFC(1,1,MPOS,LOP) , LENG , 1.0 )
                      GO TO 400
                      ENDIF
C
      MEMBER (1:1) = 'I'
      LENG         = 3*NG
      CALL CLEA ( SIG1D  , LENG  , 0.0  )
      CALL READ ( MEMBER , SIG1D , LENG )
C
      IPOS     = ( IENDUN + KFGP - 1) / KFGP
      LIMIT    = 1
      DO 300 N = 1 , NG
      NSTART   = N
      IF(IPOS.LT.LIMIT) GO TO 301
      LIMIT    = NI(N) + 1
C
*     WRITE(NOUT1,503)  N,(SSFEFC(J,N,MPOS,LOP),J=1,3)
*     WRITE(NOUT1,504)  N,(SIG1D (J,N),J=1,3)
C
      DO 250 J = 1 , 3
      SAVE     = SIG1D(J,N)
      SAVE2    = SSFEFC(J,N,MPOS,LOP)
      IF(SAVE.LE.0.0.OR.SAVE2.LE.0.0) THEN
                      SSFEFC(J,N,MPOS,LOP) = 1.0
                      ELSE
                      SSFEFC(J,N,MPOS,LOP) = SAVE2/SAVE
                      ENDIF
  250 CONTINUE
  300 CONTINUE
      GO TO 400
  301 CONTINUE
*     WRITE(NOUT1,501) LOP,MPOS,IENDUN,IPOS,NSTART,NG,MEMBER
*     WRITE(NOUT1,502) (N,(SSFEFC(J,N,MPOS,LOP),J=1,3),N=1,NSTART-1)
C
      DO 350 N = NSTART , NG
      SSFEFC(1,N,MPOS,LOP) = 1.0
      SSFEFC(2,N,MPOS,LOP) = 1.0
      SSFEFC(3,N,MPOS,LOP) = 1.0
  350 CONTINUE
  400 CONTINUE
  500 CONTINUE
C
  501 FORMAT(1H ,' ## LOP MPOS IENDUN IPOS NSTART NG MEMBER ## ',
     +           6I8,2X,A8)
  502 FORMAT(1H ,' ## NG SSFEFC ## ',I3,1P3E12.5)
  503 FORMAT(1H ,' ## NG FICEF  ## ',I3,1P3E12.5)
  504 FORMAT(1H ,' ## NG SIG1D  ## ',I3,1P3E12.5)
C
C
C
      IF(IPLOT.EQ.0) RETURN
C------ PRINT OUT
      WRITE(NOUT2,601) TIL,ID
      WRITE(NOUT2,602)
      WRITE(NOUT2,603)
      WRITE(NOUT2,602)
      DO 600 I = 1 , KRES
      IPOS     = IRCONT(6,I)
      WRITE(NOUT2,604) I,NCODEL(I),(IRCONT(J,I),J=1,6),TMPSET(IPOS)
  600 CONTINUE
      WRITE(NOUT2,602)
      RETURN
C
  601 FORMAT(1H1/1H ,5X,'*** USER''S MCROSS CONTROL DATA  ***',
     1       18A4,4X,2A4//)
  602 FORMAT(1H ,4X,8(10H----------))
  603 FORMAT(1H ,5X,' NO   NUCLIDE',
     +'     ITAPE   MATNO     IZA   IFISS  IENDUN   NTPOS TEMPERATURE')
  604 FORMAT(1H ,5X,I3,3X,A8,2X,I6,I8,I10,I6,2I8,F9.3,' KELVIN')
C
C-----ERROR STOP
C
 1001 CONTINUE
      WRITE(NOUT1,1002) MEMBER,MEMBER(2:4),MTNAME(LOP)
      WRITE(NOUT2,1002) MEMBER,MEMBER(2:4),MTNAME(LOP)
      STOP
C
 1002 FORMAT(1H ,' EEROR STOP AT SUBR.(PCOIN3) IN READING LIBRARY ]]',
     +  /1H ,' MEMBER(',A8,') IS NOT FOUND IN MICREF LIBRARY.',
     +  /1H ,' PLEASE INPUT IXMICR FOR THIS NUCLIDE(',A3,') OF MIXTURE('
     +      ,A8,') TO BE 1 OR 3 ]] '/)
C
 1101 CONTINUE
      WRITE(NOUT1,1102) MEMBER,RTEMP
      WRITE(NOUT2,1102) MEMBER,RTEMP
      STOP
C
 1102 FORMAT(1H ,' EEROR STOP AT SUBR.(PCOIN3) IN READING LIBRARY ]]',
     +  /1H ,' MEMBER(',A8,') IS NOT FOUND IN USER''S MCORSS LIBRARY.',
     +  /1H ,' BECAUSE TEMPERATURE(',F7.2,') IS NOT FOUND ]] '/)
C
 1201 CONTINUE
      WRITE(NOUT1,1202) MEMBER
      WRITE(NOUT2,1202) MEMBER
      WRITE(NOUT1,1203) NTEMP,RTEMP
      WRITE(NOUT2,1203) NTEMP,RTEMP
      WRITE(NOUT1,1204) (TMPSET(I),I=1,NTEMP)
      WRITE(NOUT2,1204) (TMPSET(I),I=1,NTEMP)
      STOP
C
 1202 FORMAT(1H ,' EEROR STOP AT SUBR.(PCOIN3) IN READING LIBRARY ]]',
     +  /1H ,' MEMBER(',A8,') IS NOT FOUND IN USER''S MCORSS LIBRARY.')
 1203 FORMAT(1H ,' NTEMP & RTEMP IS ',I6,2X,F10.3,' KELVIN .')
 1204 FORMAT(1H ,' TEMP ARRARY : ',10F10.3)
C
 1301 CONTINUE
      WRITE(NOUT1,1302) NCODEL(MPOS),TMPSET(ISAVE),TMPSET(NTPOS)
      WRITE(NOUT2,1302) NCODEL(MPOS),TMPSET(ISAVE),TMPSET(NTPOS)
      STOP
C
 1302 FORMAT(1H ,' EEROR STOP AT SUBR.(PCOIN3) IN READING ',
     +       'USER''S MCROSS LIBRARY  ]]',
     +  /1H ,' NUCLIDE(',A8,') HAS DOUBLE TEMPERATURE DEFINISION . ',
     +  /1H ,' ONE TEMPERATURE IS ',F7.2,' KELVIN AND ANOTHER IS ',
     +   F7.2,'KELVIN.'
     +  /1H ,' PLEASE RESET STATNDARD TEMPERATURE ARRAY BY YOUR INPUT '
     +      ,'DATA(TEMPSET IN II.2 IDENT) ]]'/)
C
      END
