C             CELL                LEVEL=1        DATE=80.09.29
      SUBROUTINE CELL(CT,CS,XNN,B,XND,XNA,M1)
C   *** HOMOGENEOUS - ONE REGION CELL CALCULATION
C       EXECUTION SPECIFIED BY IDAT2 AND 24&
      DIMENSION CT(1),CS(1),XNN(1),B(M1,1),XND(1),XNA(1)
      COMMON /SN1C/
     &              D(1),LIM1,LR,LW,LDSN,LMA,LMZ,LMB,LMC,LXMD,LFIX,LFLT,
     &       LJ5,LRM,LDF,LJ3,LJ4,LIGT,LART,LALFT,
     &LFGP,LFGG,LEND,LV,LAA,LWD,LMR,LPNC,
     &ID,ITH,ISCT,ISN,IGE,IBL,IBR,IZM,IM,IEVT,IGM,IHT,IHS,IHM,MS,MCR,MTP
     &,MT,IDFM,IPVT,IQM,IPM,IPP,IIM,ID1,ID2,ID3,ID4,ICM,IDAT1,IDAT2,IFG,
     &IFLU,IFN,IPRT,IXTR,
     &EV,EVM,EPS,BF,DY,DZ,DFM1,XNF,PV,RYF,XLAL,XLAH,EQL,XNPM,
     &T(12),NIN,NOU,NT1,NT2,NT3,NT4,NT5,NT6,NT7
      COMMON /WORK/ Z(1),LIM2,LXKI,LFD,LXN,LVE,LMTT,LCRX,LQ,LPA,
     &        LXJ,LCH,LCA,LCF,LCT,LCS,LTAB,
     &LXND,LSA,LSAT,LRAV,LRA,LXNN,LXNE,LXNR,LXNA,LSR,LST,LQG,LFG,LSG,
     &LXKE,LXNI,LXNO,LT3,LT5,LDA,LDB,LDC,LDS,LB,IGMP,IGMM,IIGG,NERR,IMJT
     &,IHG,IMP,MP,NDS,NUS,SDG,SCG,AG,XNLGG,XNLG,SNG,ALA,ASR,EAM,EPG,EQ,
     &E1,E2,E3,E4,E5,E6,E7,E8,E9,E10,E11,E12,E13,E14,E15,E16,E17,E18,E19
     &,E20,ESC,ESM,EVP,EVPP,FTP,IC,ICVT,IGP,IG,IHP,IIC,IIG,IP,IZP,I01,
     &I02,I03,I04,I05,I06,I07,I08,I09,I00,JT,LC,MG,MI,ML,MM,NFN,XITR,
     &XLAP,XLAPP,XLAR,XLA,XNIO,XNII,ZZ1,ZZ2,ZZ3,XNB,XKEP,XKIP,IH,I,K,L,
     &M,J,N,NN,ISV
      E1=0.0
      E2=0.0
C   *** COMPUTE REMOVAL COEFFICIENT
      DO 1 I=1,IM
    1 E1=E1 + CT(I)- CS(I)
C   *** COMPUTE SCALAR FLUX. COMPREHENSION OF HTE FOLLOWING COMPLICATED
C      EXPRESSION IS PROBABLY IMPOSSIBLE UNLESS ONE REALIZES THAT ZZ1
C       IS THE TOTAL SOURCE - LESS IN-GROUP SCATTER - FOR GROUP IIG.
      IF(E1.NE.0.0)E2=ZZ1/E1
C   *** STORE FLAT, ISOTROPIC FLUXES IN APPROPRIATE ARRAYS
      DO 2 I=1,IM
    2 XNN(I)=E2
      DO 3 M=1,MM
    3 B(M,IGMP)=E2
      DO 6 I=1,MI
    6 XND(I)=E2
C   *** STORE 0.0 IN CURRENT ARRAY AND IN LEAKAGE TERM
      XNLGG=0.0
      IF(ISCT.EQ.0)GO TO 5
      DO 4 I=1,IMJT
    4 XNA(I)=0.0
    5 RETURN
      END
