C             GRID22              LEVEL=1        DATE=81.11.14
      SUBROUTINE GRID22
C
      COMMON /TW1C/ DD(1),LIM1,IA(210)
      COMMON /WORK/AAA(1),LIM2,AA(130)
      DIMENSION D(212),A(132)
      EQUIVALENCE (D(1),DD(1)),(AAA(1),A(1))
C
C     EQUIVALENCE
C
      EQUIVALENCE (IA(5),IM),(IA(6),JM),(IA(13),MT),(IA(18),IHM),
     &(IA(57),MM),(IA(58),NM),(IA(64),IT),(IA(65),JT),(A( 61),LC),
     &(A(64),LA3),(A(65),LA4),(A(66),LA5),(A(67),LQ),(A(68),LQR1),
     &(A(69),LQR2),(A(70),LQT1),(A(71),LQT2),(D(173),LXDF),(D(174),LYDF)
     &,(A(76),LFL),(A(77),LFIS),(A(78),LFISA),(D(181),LDC),(D(184),LDX),
     &(D(185),LDY),(D(186),LDYA),(A(80),LYH),(D(190),LWM),(A(81),LWE),
     &(A(86),LQQ),(A(92),LABT),(A(95),LQG),(A(96),LFG),(A(97),LSIN),
     &(A(98),LSS),(A(99),LSOUT),(A(105),LABG),(A(108),LCHIA),(A(112),LAA
     &),(A(117),LQB1),(A(118),LQB2),(A(119),LCTOT)
C     BEGIN OUTER ITERATION
C
CKSK  CALL OUTER ( A(LQ),A(LCHIA),A(LFISA),D(LDC),D(LDX),D(LDY),A(LC),
CKSK &A(LFL),A(LQQ),A(LA3),A(LYH),A(LSIN),A(LQG),A(LFG),A(LSS),A(LSOUT),
CKSK &A(LABG),A(LABT),D(LDYA),A(LFIS),NM,IT,JT,IHM,MT,IM,JM,D(LWM),
CKSK &A(LWE),A(LQR1),A(LQR2),A(LQT1),A(LQT2),MM,A(LAA),A(LQB1),A(LQB2),
CKSK &A(LA4),A(LA5),A(LCTOT),D(LXDF),D(LYDF) )
      CALL OUTER ( AAA(LQ),AAA(LCHIA),AAA(LFISA),DD(LDC),DD(LDX),
     &DD(LDY),AAA(LC),AAA(LFL),AAA(LQQ),AAA(LA3),AAA(LYH),AAA(LSIN),
     &AAA(LQG),AAA(LFG),AAA(LSS),AAA(LSOUT),AAA(LABG),AAA(LABT),
     &DD(LDYA),AAA(LFIS),NM,IT,JT,IHM,MT,IM,JM,DD(LWM),AAA(LWE),
     &AAA(LQR1),AAA(LQR2),AAA(LQT1),AAA(LQT2),MM,AAA(LAA),AAA(LQB1),
     &AAA(LQB2),AAA(LA4),AAA(LA5),AAA(LCTOT),DD(LXDF),DD(LYDF) )
      RETURN
      END
