      SUBROUTINE  IRAPRT(MTNAME,IDENT ,SIG0  ,XSECFC,ENBND ,SFCTR ,
     +                   ISWMIC,RTEMP )
C
C      PRINT OUT  EFFECTIVE MICROSCOPIC CROSS SECTION
C
      DOUBLE PRECISION  JNEFST,FNEFST,JNMACR,FNMACR
C
      COMMON  /IRACNL/ IOPT(20),JNEFST,FNEFST,JNMACR,FNMACR,NEF,IGT,
     1                 NMAT,KNMAX,MXMTX,MXTEMP,MXSIG0,LNMAX,IDS,NEF1,
     2                 MXREAC,NOUT1,NOUT2
C
      COMMON  /IRADAT/ ISTART,NEFR,NEFB,NOMTF,NISOM,TCOR,S,NRES,NPSE,
     +                 VOLF,VOLM,KKNMAX,NMP,MATD(50)
      COMMON  /IRACNT/ AMASS,SIGP,ICAPT,IFISS,IIRES,LTOT,IFS,IFTR,IFC,
     +                 IFF,IFE,IFER,NGMIN,NGMAX,NSIG,NTEMP,SIGC0
      COMMON  /IRAWRK/ A(17000),NAMEP(2),LOCAM(11),LOCAF(6)
C
      COMMON  /TMPSET/ STND(35),IDTEMP(61),NTDUMY
C
      COMMON  /PDSPDS/ BUF(540),IFLSW,NFILE(3),ECODE,TEMPRY
C
      DIMENSION  MTNAME(2),IDENT(2),SIG0(NEF,2),XSECFC(NEF,2,2),
     +           ENBND(NEF1),SFCTR(NEF,2,2),IA(41)
C
CKSK 
      CHARACTER*4 NFILE, IDPQM, IDPQF, IDPQC
CKSK  DATA       IDPQM/4H   M/,IDPQF/4H   F/,IDPQC/4H   C/
      DATA       IDPQM/'   M'/,IDPQF/'   F'/,IDPQC/'   C'/
C
C
      IF(IOPT(19).EQ.0) GO TO 150
      WRITE(NOUT2,1001)  MTNAME,IDENT
      WRITE(NOUT2,1002)
      WRITE(NOUT2,1005)
      DO 100 I=ISTART,NEF
      WRITE(NOUT2,1003) I,ENBND(I),ENBND(I+1),XSECFC(I,1,1),
     +                    XSECFC(I,2,1),XSECFC(I,1,2),XSECFC(I,2,2)
      WRITE(NOUT2,1004)   SIG0(I,1),SIG0(I,2),SFCTR(I,1,2),SFCTR(I,2,2),
     +                    SFCTR(I,1,1),SFCTR(I,2,1)
  100 CONTINUE
      WRITE(NOUT2,1005)
C
C ---- EFFECTIVE MICROSCOPIC X-SECTION MODIFY
C
  150 IF(IFS.EQ.0)                    RETURN
      IF(ISWMIC.EQ.1.OR.ISWMIC.EQ.3)  GO TO 101
      RETURN
  101 CONTINUE
      ITMP    =1
      TDIFF   =10000.
      DO 200 I= 1,NTDUMY
      TKEEP   =ABS(RTEMP-STND(I))
      IF(TKEEP.GT.TDIFF)  GO TO 210
      ITMP    =I
  200 TDIFF   =TKEEP
  210 CONTINUE
C
C     NFILE(1)=4HFAST
C     NFILE(2)=4HU
C     NAMEP(1)=IDENT(1)
C     CALL PACK(NAMEP(1),1,IDPQC)
C     NAMEP(2)=4H0000
C     CALL READ(NAMEP,IA,41)
C
C
      CALL  CLEA(A ,17000,0.0)
C
CKSK
      NFILE(1)='MICR'
      NFILE(2)='EF  '
c
      CALL PACK (NAMEP(2),4,IDTEMP(ITMP))
      CALL PACKX(NAMEP(2),3,MTNAME(2),3)
      CALL PACKX(NAMEP(2),2,MTNAME(2),2)
      CALL PACK (NAMEP(2),1,IDPQF)
      CALL PACK (NAMEP(1),1,IDPQC)
C===  READ CONTROL
      CALL READ(NAMEP,IA,41)
      CALL PACK(NAMEP(1),1,IDPQM)
      LENG=IA(4)
C===  READ FULL MATRIX
      CALL READ(NAMEP(1),A,LENG)
C
      ISTC=LOCAM(1)-1
      ISTF=LOCAM(2)-1
      ISTT=LOCAM(5)-1
      DO 220 I=1,NEF
      IF(ICAPT.EQ.1) A(ISTC+I)=XSECFC(I,2,2)
      IF(IFISS.EQ.1) A(ISTF+I)=XSECFC(I,2,1)
      A(ISTT+I)=A(ISTT+I)+XSECFC(I,2,2)+XSECFC(I,2,1)
     +                   -XSECFC(I,1,2)-XSECFC(I,1,1)
  220 CONTINUE
C
      CALL DELETE(NAMEP)
      CALL WRITE(NAMEP,A,LENG)
C ---- MODIFICATION END
      RETURN
C
C 301 CONTINUE
C     WRITE(NOUT1,310) NAMEP
C     RETURN
C
  310 FORMAT(/1H ,10X,'MEMBER(',2A4,') IS NOT FOUND IN USER FAST-LIB.'
     +/1H ,10X,'THEN EFFECTIVE MICROSCOPIC X-SECTION MODIFICATION WAS NO
     +T EXCUTED.(AT SUBR.IRAPRT)')
C
 1001 FORMAT(///1H ,30X,'MATERIAL NAME = ',2A4,5X,'NUCLIDE NAME = ',
     +2A4,'   (IRA-ROUTINE)'//)
 1002 FORMAT(1H ,25X,'GRP.',T32,'E-UPPER',T44,'E-LOWER',T56,'FISS.(NR)',
     +T68,'FISS.(IR)',T80,'CAPT.(NR)',T92,'CAPT.(IR)')
 1004 FORMAT(1H ,28X,2E12.4,4F12.4)
 1003 FORMAT(1H ,25X,I3,1P6E12.4)
 1005 FORMAT(1H ,25X,15(5H-----))
C
      END
