C **********************************************************************
                SUBROUTINE        MACROT
C **********************************************************************
C *** FORM MACROSCOPIC CROSS-SECTION IN THERMAL RANGE ***
C
C     THERMALU DD NAME OF THERMAL USERS LIBRARY
C     MACRO    DD NAME OF MACRO X-SECTION FILE
C     NET      NUMBER OF THERMAL ENERGY GROUPS
C     NMAT     NUMBER OF MATERIALS
C     LCMTNM   LOCATION OF MATERIAL NAMES
C     LCNISO   LOCATION OF NUMBER OF ISOTOPES IN A MATERIAL
C     LCTEMP   LOCATION OF MATERIAL TEMPERATURES
C     LCXL     LOCATION OF MEAN CHORD LENGTH
C     LCXCDC   LOCATION OF DANCOFF CORRECTION FACTOR
C     LCLISO   RELATIVE LOCATION OF QUANTITLES OF MATERIAL
C     LCIRES   RELATIVE LOCATION OF RESONANCE INDICATOR BY ISOTOPE
C     LCIXMC   RELATIVE LOCATION OF EFF_MICRO INDICATOR BY ISOTOPE
C     LCIDNT   LOCATION OF ISOTOP IDENTIFICATIONS(1D)
C     LCDN     LOCATION OF ISOTOPE DENSITIES (ID)
C     IOPT(21) (0,1: UPSCATTERING, NO UPSCATTERING)
C     IOPT(39) ORDER OF ANISOTROPIC SCATTERING =0 IF P0 ONLY
C
      COMMON /MAINC/  IOPT(52)
     3    ,NEFL     ,NETL     ,NEF      ,NET      ,NERF     ,NERT
     4    ,NMAT     ,NEFF     ,BSQ,NIN1,NIN2,NOUT1,NOUT2,DUMMY1(15)
     5    ,LCNEGF   ,LCNEGT   ,LCNECF   ,LCNECT   ,LCMTNM   ,LCNISO
     6    ,LCTEMP   ,LCXL     ,LCXCDC   ,LCLISO   ,LCIDNT   ,LCDN
     7    ,LCIRES   ,LCIXMC   ,DUMMY2(6)
     8    ,CASEID(2),TITLE(18)
     9    ,AA(880)
C
      CALL MACRTR(NMAT,AA(LCMTNM),AA(LCNISO),AA(LCTEMP),AA(LCXL),
     *                 AA(LCXCDC),AA(LCIDNT),AA(LCDN)  ,AA(LCIXMC),
     *                 AA(LCIRES),NEF)
C
      RETURN
      END
