      SUBROUTINE UCLOCK(ICPU)
C
C     CLOCK IS FACOM BUILTIN SERVICE ROUTINE TO RETURN CURRENT CPU TIME.
C     ICPU(OUTPUT)  : CURRENT USED CPU TIME (SEC) IN 4-BYTE INTEGER
C
C     HITACHI SR2201/S3000 SERIES (HI-UX/MPP FORTRAN)
C     ICPU(OUTPUT)  : CURRENT USED CPU TIME 
C     IC1  (INPUT)  : =1-8 (CONTROL FOR CLOCK FUNCTION)
C
C---- START TIMER IF FIRST CALL
      COMMON /WKCLCK/ NCALL
      NCALL = NCALL + 1
      IF(NCALL.EQ.0) CALL CLOCK(IDUMMY,3)
C---- GET CPU TIME FROM FIRST CALL BUT NOT STOP TIMER
      IC1 = 5
      CALL CLOCK(CPU,IC1)
      ICPU = CPU
CDEL  SAVE NCALL
      RETURN
      END
