      SUBROUTINE UCLOCK(ICPU)
C
C     UCLOCK RETURN CURRENT USED CPU TIME (SEC) IN 4-BYTE INTEGER
C     BY USING UCLCKM ROUTINE WHICH RETURN CPU TIME IN MILI-SEC    
C
C     
      CALL UCLCKM(ICPUM)
      ICPU = ICPUM/1000
      RETURN
      END
