      SUBROUTINE PIJ1D(IA,IB,IC,IRR,IXR,MATT,MAR,MATD,MMR,VOLT,VOLR,
     &    VOLM,IRRD,IXRD,MATTD,MARD,MATDD,MMRD,VOLTD,VOLRD,VOLMD)
      COMMON / PIJ2C / IGT,NZ,NR,NRR,NXR,DUM(27),NM
      COMMON /DOUBLE/
     &  IDB   ,IGEOM ,METHOD,NTRD  ,NRRD  ,NMD   ,MDNO  ,DRF   ,DRM   ,
     &  DXL   ,DVF   ,DVM   ,DVCELL,RHO   ,GAMMA
      COMMON /MAINC/ DDM(63),NOUT1,NOUT2
      DIMENSION IA(NRR),IB(NRRD),IC(NR)
      DIMENSION IRR(NR),IXR(NRR),MATT(NR),MAR(NRR),MATD(NM),MMR(NRR)
      DIMENSION VOLT(NR),VOLR(NRR),VOLM(NM)
      DIMENSION IRRD(NTRD),IXRD(NRRD),MATTD(NTRD),MARD(NRRD)
     &         ,MATDD(NMD),MMRD(NRRD)
      DIMENSION VOLTD(NTRD),VOLRD(NRRD),VOLMD(NMD)
      DATA PI/3.14159/
C
C
C ***** READ MICROSCOPIC HETEROGENEITY
      CALL REAM(BB,IDB,DRF,0,3,2)
C     COMMON /DOUBLE/
C    1  IDB   ,IGEOM ,METHOD,NTRD  ,NRRD  ,NMD   ,IDB007,DRF   ,DRM   ,
C    2  DXL   ,DVF   ,DVM   ,DVCELL,RHO   ,GAMMA
      WRITE(NOUT2,100) IDB,IGEOM,METHOD,DRF,DRM
  100 FORMAT('0        === MICROSCOPIC HETEROGENEITY ==='/
     &10X,'ENERGY RANGE(RESONANCE,THERMAL;1,2)             ',I2/
     &10X,'MICRO GEOMETRY(SLAB,CYL,SHERE;1,2,3)            ',I2/
     &10X,'METHOD (TRANS,PMJ,SEGEV;1,2,3)                  ',I2/
     &10X,'RADIUS OF ABSORBER LUMP                         ',E12.5/
     &10X,'RADIUS OF MICROSCOPIC CELL                      ',E12.5)
C
C     RP=1.5*DRF
      DVF=  DRF**IGEOM
      IF(IGEOM.EQ.2) DVF=DVF*PI
      IF(IGEOM.EQ.3) DVF=DVF*1.33333*PI
      DVCELL=  DRM**IGEOM
      IF(IGEOM.EQ.2)DVCELL= PI*DVCELL
      IF(IGEOM.EQ.3)DVCELL= 1.3333*PI*DVCELL
      DXL=2.*DRF
      IF(IGEOM.EQ.3) DXL=1.33333*DRF
      DVM=DVCELL-DVF
      RHO=1./DVCELL
      WRITE(NOUT2,200) DVF,DVM,DVCELL,RHO
 200  FORMAT(1H0,
     &          '           VF    =',E12.4,
     &          '           VM    =',E12.4,
     &          '           VCELL =',E12.4,
     &          '           RHO   =',E12.4)
C
C
C**** MATD : MATDD : MATERIAL NUMBER BY M-REGION
C**** VOLM : VOLMD : VOLUME BY M-REGION
C
      ISHIFT=0
      DO 600 I=1,NM
      MATDD(I+ISHIFT)=MATD(I)
      VOLMD(I+ISHIFT)=VOLM(I)
      IF   (MATD(I).GT.0) GO TO 600
      MDNO=I
      MATD (I)=-MATD(I)
      MATDD(I+ISHIFT  )=MATD(I)-2
      MATDD(I+ISHIFT+1)=MATD(I)-1
      VOLMD(I+ISHIFT  )=VOLM(I)*DVF/DVCELL
      VOLMD(I+ISHIFT+1)=VOLM(I)*DVM/DVCELL
      ISHIFT=ISHIFT+1
  600 CONTINUE
      IF(ISHIFT.GT.1) GO TO 800
C
C
C**** MAR : MARD : MATERIAL NUMBER BY R-REGION
C**** MMR : MMRD : M-REGION NUMBER BY R-REGION
C**** IXR : IXRD : X-REGION NUMBER BY R-REGION
C**** IB  : R-REGION NUMBER BY MODIFIED R-REGION
C**** VOLR: VOLRD: VOLUME BY R-REGION
C
      ISHIFT=0
      DO 500 I=1,NRR
      IB   (I+ISHIFT)=I
      MARD (I+ISHIFT)=MAR(I)
      MMRD (I+ISHIFT)=MMR(I)
      IF(MMR(I).GT.MDNO) MMRD(I+ISHIFT)=MMR(I)+1
      IXRD (I+ISHIFT)=IXR(I)
      VOLRD(I+ISHIFT)=VOLR(I)
      IF   (IA(I).EQ.0) GO TO 500
      IB   (I+ISHIFT+1)=I
      MARD (I+ISHIFT  )=MAR(I)-2
      MARD (I+ISHIFT+1)=MAR(I)-1
      MMRD (I+ISHIFT  )=MMR(I)
      MMRD (I+ISHIFT+1)=MMR(I)+1
      IXRD (I+ISHIFT+1)=IXR(I)
      VOLRD(I+ISHIFT  )=VOLR(I)*DVF/DVCELL
      VOLRD(I+ISHIFT+1)=VOLR(I)*DVM/DVCELL
      ISHIFT=ISHIFT+1
  500 CONTINUE
C
C
C**** MATT : MATTD : MATERIAL NUMBER BY T-REGION
C**** VOLT : VOLTD : VOLUME BY  T-REGION
C
      ISHIFT=0
      DO 700 I=1,NR
      J=IRR(I)
      IC(I)=0
      MATTD(I+ISHIFT)=MMR(J)
      IF(MMR(J).GT.MDNO) MATTD(I+ISHIFT)=MMR(J)+1
      VOLTD(I+ISHIFT)=VOLT(I)
      IF   (IA(J).EQ.0) GO TO 700
      IC(I)=1
      MATTD(I+ISHIFT  )=MMR(J)
      MATTD(I+ISHIFT+1)=MMR(J)+1
      VOLTD(I+ISHIFT  )=VOLT(I)*DVF/DVCELL
      VOLTD(I+ISHIFT+1)=VOLT(I)*DVM/DVCELL
      ISHIFT=ISHIFT+1
  700 CONTINUE
C     NTRD=NR+ISHIFT  :  COUNTED IN PIJ1
C     WRITE(6,*) NR,NTRD,NRR,NRRD,NM,NMD
C     WRITE(6,*) (IA(I),I=1,NRR)
C     WRITE(6,*) (IB(I),I=1,NRRD)
C     WRITE(6,*) (IC(I),I=1,NR)
C     WRITE(6,*) MDNO
C     WRITE(6,*) (MATD(I),I=1,NM)
C     WRITE(6,*) (MATDD(I),I=1,NMD)
C     WRITE(6,*) (MATT(I),I=1,NR)
C     WRITE(6,*) (MATTD(I),I=1,NTRD)
C     WRITE(6,*) (MMR(I),I=1,NRR)
C     WRITE(6,*) (MMRD(I),I=1,NRRD)
C     WRITE(6,*) (VOLM(I),I=1,NM)
C     WRITE(6,*) (VOLMD(I),I=1,NMD)
C
      RETURN
C ERROR STOP BY MORE THAN ONE HETEROGENEOUS MATERIALS
  800 WRITE(NOUT1,810) ISHIFT
  810 FORMAT('0 ***** MORE THAN ONE HETEROGENEOUS MATERIALS ',I2)
      STOP
      END
