C             CSPREP              LEVEL=7        DATE=83.03.15
      SUBROUTINE CSPREP ( CBAR,C,IHM,IGM,MT,MIN,AAJ,MCR,MTP,LMTP,MTPS,
     &NISOXS )
C
C     READS AND PRINTS INPUT CROSS SECTIONS, CHECKS CONSISTENCY,
C     PERFORMS ADJOINT REVERSALS AND STORES
C
      COMMON /TW1C/ DD(1),LIM1,IA(210)
      COMMON /WORK/AAA(1),LIM2,AA(130)
      DIMENSION D(212),A(132)
      EQUIVALENCE (D(1),DD(1)),(AAA(1),A(1))
C
      DIMENSION C(IHM,IGM,MIN), CBAR(IHM,MT), AAJ(1)
      DIMENSION IDCARD(18), E1(4), E2(6)
C
      EQUIVALENCE (IA(1),ITH),(IA(15),MS),(IA(16),IHT),(IA(17),IHS),
     &(IA(43),EPS),(IA(53),IHA),(IA(55),IHNN),(IA(71),ISPANC),
     &(A(61),LC),(D(86),MCRRDS),(A(51),NOSGUP)
       EQUIVALENCE (A(67),LQ)
C
C     /FWBGN1/ , /FWBGN2/ , /UNITS/
C
      EQUIVALENCE (D(115),IPXS),(D(125),I3),(D(119),LTAXS),(D(117),LTXS)
     &           ,(D(157),NOUT),(D(156),NINP),(D(167),ISOTXS)
C
      INTEGER G
C
CSASA REAL*8 E1,E2
      CHARACTER*8 E1,E2
C
      DATA E1/' NO IN','PUT X-','SECTIO','NS    '/
      DATA E2/' NO SI','GMA UP',' ALLOW','ED IN ','FIDO X','-SECT '/
C
      IF ((MCR+MTPS).LE.0) CALL ERROR (2,E1,4)
      WRITE (NOUT,260)
      IF (MCR.EQ.0) GO TO 130
C
C     READ CROSS SECTIONS FROM CARDS
C
C     IF (MCRRDS.LT.0) GO TO 120
C
C     READ STANDARD LASL FORMAT
C
      MP=IHT+1
      DO 110 N=1,MCR
      CALL REAM(IDCARD,IDCARD,IDCARD,18,0,0)
      WRITE (NOUT,280)N,(IDCARD(I),I=1,18)
      IF (IHT+1.EQ.IHS) GO TO 100
      IF (NOSGUP.LT.0) GO TO 100
C
C     CROSS SECTIONS CONTAIN SIGMA UP - REMOVE
C
      READ (NINP,290)((C(I,G,N),I=1,IHT),T,(C(I,G,N),I=MP,IHM),G=1,IGM)
      GO TO 110
C
C     CROSS SECTIONS DO NOT CONTAIN SIGMA UP
C
  100 CALL REAM(C(1,1,N),C(1,1,N),C(1,1,N),0,0,IHM*IGM)
  110 CONTINUE
      GO TO 130
C
C     READ CROSS SECTIONS IN FIDO FORMAT  (NO SIGMA UP ALLOWED )
C
C 120 IF (NOSGUP.LT.0) CALL ERROR (2,E2,6)
C     WRITE (NOUT,300)
C     CALL FIDO ( 6 HX-SEC , 6 HFIDO  , C, C, IHM * IGM * MCR,
C    1NINP, NOUT )
  130 CONTINUE
      IF (MTPS.EQ.0) GO TO 140
C
C     PROCESS INTERFACE FILE FOR LIBRARY X-SECTIONS
C
C     LXSP1 = LMTP+MTPS
      IHMUP = IHM
      IF (IHS.GT.IHT+1) IHMUP=IHMUP+1
      LXSP1 = LQ + IHMUP*IGM*MIN
CKSK FOR DOUBLE PRECISION (95,7/24)
      IF(MOD(LXSP1,2).EQ.0) LXSP1 = LXSP1 + 1
CKSK
      LXSP2 = LXSP1+4*MTPS
      LXSP3 = LXSP2+2*NISOXS
CKSK  CALL IFINXS(C(1,1,MCR+1),IHM,IGM,MTPS,A(LMTP),A(LXSP3),A(LXSP3),
CKSK &            A(LXSP3),A(LXSP1),2,A(LXSP2),MTPS,MCR             )
      CALL IFINXS(C(1,1,MCR+1),IHM,IGM,MTPS,AAA(LMTP),AAA(LXSP3),
     & AAA(LXSP3),AAA(LXSP3),AAA(LXSP1),2,AAA(LXSP2),MTPS,MCR )
C
C     DECIDE WHETHER OR NOT TO PRINT CROSS SECTIONS
C
  140 CONTINUE
      IF (I3.EQ.2) GO TO 160
      IF (I3.EQ.0) GO TO 150
      IF (MS.NE.0) GO TO 160
  150 CONTINUE
      CALL WWRITE(3,2,C,IHM,IGM,MIN,' INPUT',' CROSS',' SECT ',' GROUP')
  160 CONTINUE
      IF (ITH.EQ.0) GO TO 200
C
C     ADJOINT MANIPULATIONS
C
      DO 190 I=1,MIN
      DO 190 JJ=1,IHM
      J=IHM+1-JJ
      IG=1
      K=IGM
      IF (J.LE.IHT) GO TO 180
      JA=J-IHS
      IF (JA.LE.0) GO TO 170
      IG=JA+1
      GO TO 180
  170 CONTINUE
      JA=JA+IGM
      IF (JA.LE.0) GO TO 190
      K=JA
  180 CONTINUE
      IF (K.LE.IG) GO TO 190
      T=C(J,K,I)
      C(J,K,I)=C(J,IG,I)
      C(J,IG,I)=T
      IG=IG+1
      K=K-1
      GO TO 180
  190 CONTINUE
C
C     STORE CROSS SECTIONS AND EFFECTIVE ABSORPTION
C
  200 DO 250 G=1,IGM
      DO 240 M=1,MIN
      IF (C(IHT,1,M).LE.0.0) GO TO 230
C
C     PREPARE EFFECTIVE ABSORPTION
C
      AAJ(M)=C(IHT,G,M)
      JC=IHS-G+1
      JD=1
  210 IF (JC.GT.IHT) GO TO 220
      JC=JC+1
      JD=JD+1
      GO TO 210
  220 AAJ(M)=AAJ(M)-C(JC,JD,M)
      JC=JC+1
      JD=JD+1
      IF ((JC.LE.IHM).AND.(JD.LE.IGM)) GO TO 220
      IF (ITH.NE.0) GO TO 230
C
C     CHECK ABSORPTION
C
C     EFFECTIVE ABSORPTION CORRECTED N2N CROSS-SECTION
C
      AAJ(M)=AAJ(M)+C(IHT-4,G,M)
      IF (AAJ(M).EQ.0.0) T=C(IHA,G,M)-AAJ(M)
      IF (AAJ(M).NE.0.0) T=1.-C(IHA,G,M)/AAJ(M)
      IF (ABS(T).GT.EPS) WRITE (NOUT,310)M,G,C(IHA,G,M),AAJ(M)
C
C     STORE CROSS SECTIONS IN LCM BY GROUP
C
  230 DO 240 L=1,IHM
  240 CBAR(L,M)=C(L,G,M)
CKH
CKH   WRITE(6,666) G,((CBAR(III,JJJ),III=1,IHM),JJJ=1,MIN)
CK666 FORMAT(' G=',I2,' CBAR(I,J)  --- CSPREP'/(11E11.3))
CKH
      CALL RITE (0,IPXS+(G-1)*LTXS,CBAR,LTAXS,1)
  250 CONTINUE
      RETURN
C
C
  260 FORMAT (1H0,50('*'),'INPUT CROSS SECTIONS',40('*'))
  270 FORMAT (18A4)
  280 FORMAT (1H ,3X,I3,20X,'LOADED FROM CARDS',18A4)
  290 FORMAT (6E12.5)
  300 FORMAT (1H ,3X,23X,'FIDO X-SECTIONS, ALL NUCLIDES LOADED AS A ',
     &'BLOCK WITH TERMINATION')
  310 FORMAT ('0IN MATERIAL',I3,',GROUP',I3,' INPUT ABSORPTION (',
     &E12.5,').NE.EFFECTIVE ABSORPTION (',E12.5,')')
      END
