C             EDITOR              LEVEL=1        DATE=81.11.14
      SUBROUTINE EDITOR ( IDCS,NEDZ,EDACT,FR,FL,FU,FD,FLUX,Q,EDACTG,V,C,
     &X,Y,RL,LL,TL,BL,NL,S,F,RLG,LLG,TLG,BLG,NLG,SG,FG,IDX,IDYA,MICID,
     &MIXNUM,MIXCOM,MIXDEN,IM,JM,NZ,IHT,IP,JP,MN,IT,JT,IHM,MT,ICLEAR,
     &NORMZ,NN,XDF,YDF,NM )
C
      COMMON /TW1C/ DD(1),LIM1,IA(210)
      COMMON /WORK/AAA(1),LIM2,AA(130)
      DIMENSION D(212),A(132)
      EQUIVALENCE (D(1),DD(1)),(AAA(1),A(1))
      EQUIVALENCE (D(110),IPFL),(D(112),IPFX),(D(120),IPQS),(D(115),IPXS
     &),(D(111),LTFL),(D(113),LTFX),(D(118),LTOXS),(D(121),LTQS),
     &(D(117),LTXS),(D(114),LXFX),(D(162),NEDIT),(D(161),NEXTRA),
     &(D(157),NOUT)
C
      DIMENSION IDCS(IM,JM),NEDZ(IM,JM),EDACT(IHT,NZ),FR(IP,JM),
     &FL(IP,JM),FU(IM,JP),FD(IM,JP),FLUX(NM,IT,JT),Q(NM,IT,JT),
     &EDACTG(IHT,NZ),V(IT,JT),C(IHM,MT),X(1),Y(1),RL(1),LL(1),TL(1),
     &BL(1),NL(1),S(1),F(1),RLG(1),LLG(1),TLG(1),BLG(1),NLG(1),SG(1),
     &FG(1),IDX(1),IDYA(1),MICID(1),MIXNUM(1),MIXCOM(1),MIXDEN(1),
     &XDF(1),YDF(1)
C
      EQUIVALENCE (IA(4),IGM),(IA(7),IBL),(IA(8),IBR),(IA(9),IBB),
     &(IA(10),IBT),(IA(11),IEVT),(IA(15),MS),(IA(31),IEDOPT),
     &(IA(32),IGEOM),(IA(37),EV),(IA(52),IHF),(IA(56),IMJM),
     &(IA(66),ITJT),(D(171),LIHX),(D(172),LIHY),(A(61),LC),
     &(D(202),LXRA),(D(203),LYRA)
C
      INTEGER G
      REAL LL,LLG,NL,NLG,MIXDEN
C
      IHTNZ=IHT*NZ
      CALL REED (NEXTRA,0,0.0,0,4)
      CALL REED (NEDIT,0,NEDZ,ITEMP,3)
      CALL CLEARW(0.0,RLG,ICLEAR)
C
C     GENERATE VOLUME ELEMENT
C
      DO 100 J=1,JT
      DO 100 I=1,IT
  100 V(I,J)=Y(J)*X(I)
C
C     BEGIN EDIT
C
      DO 350 G=1,IGM
      IF (G.NE.1) GO TO 110
CKSK  CALL EDMAP ( D(LXRA),D(LYRA),FLUX,NEDZ,D(LIHX),D(LIHY),IM,IP,JM,
CKSK &JP,IM*JM,IBL,IBT,IBR,IBB,IGEOM,NN )
      CALL EDMAP ( DD(LXRA),DD(LYRA),FLUX,NEDZ,DD(LIHX),DD(LIHY),
     &IM,IP,JM,JP,IM*JM,IBL,IBT,IBR,IBB,IGEOM,NN )
      WRITE (NOUT,470)NN,G
  110 CONTINUE
CKSK  CALL REED (0,IPXS+(G-1)*LTXS,A(LC),LTOXS,1)
      CALL REED (0,IPXS+(G-1)*LTXS,AAA(LC),LTOXS,1)
      IF (IEVT.EQ.0) CALL REED (0,IPQS+(G-1)*LTQS,Q,LTQS,1)
      CALL REED (0,IPFX+(G-1)*LTFX,FLUX,LXFX,1)
      CALL REED (0,IPFL+(G-1)*LTFL,FU,LTFL,1)
      CALL CLEARW(0.0,RL,ICLEAR)
      DO 190 I=1,IM
      DO 190 J=1,JM
      IZ=NEDZ(I,J)
      IF (J.GT.1) GO TO 120
      BL(IZ)=BL(IZ)+FD(I,1)-FU(I,1)
  120 IF (J.NE.JM) GO TO 130
      TL(IZ)=TL(IZ)+FU(I,JP)-FD(I,JP)
  130 IF (I.GT.1) GO TO 140
      LL(IZ)=LL(IZ)+FL(1,J)-FR(1,J)
  140 IF (I.NE.IM) GO TO 150
      RL(IZ)=RL(IZ)+FR(IP,J)-FL(IP,J)
  150 IF (I.EQ.1) GO TO 160
      IF (IZ.NE.NEDZ(I-1,J)) LL(IZ)=LL(IZ)+FL(I,J)-FR(I,J)
  160 IF (I.EQ.IM) GO TO 170
      IF (IZ.NE.NEDZ(I+1,J)) RL(IZ)=RL(IZ)+FR(I+1,J)-FL(I+1,J)
  170 IF (J.EQ.1) GO TO 180
      IF (IZ.NE.NEDZ(I,J-1)) BL(IZ)=BL(IZ)+FD(I,J)-FU(I,J)
  180 IF (J.EQ.JM) GO TO 190
      IF (IZ.NE.NEDZ(I,J+1)) TL(IZ)=TL(IZ)+FU(I,J+1)-FD(I,J+1)
  190 NL(IZ)=TL(IZ)+BL(IZ)+LL(IZ)+RL(IZ)
      DO 200 IZ=1,NZ
      NLG(IZ)=NLG(IZ)+NL(IZ)
      RLG(IZ)=RLG(IZ)+RL(IZ)
      LLG(IZ)=LLG(IZ)+LL(IZ)
      TLG(IZ)=TLG(IZ)+TL(IZ)
  200 BLG(IZ)=BLG(IZ)+BL(IZ)
      DO 230 J=1,JT
      DO 230 I=1,IT
      IB=IDX(I)
      JB=IDYA(J)
      IC=IABS(IDCS(IB,JB))
      IZ=NEDZ(IB,JB)
      T=FLUX(1,I,J)*V(I,J)
      IF (IEVT.NE.0) GO TO 210
      S(IZ)=S(IZ)+Q(1,I,J)*V(I,J)
  210 F(IZ)=F(IZ)+T
      DO 220 K=1,IHT
  220 EDACT(K,IZ)=EDACT(K,IZ)+T*C(K,IC)*XDF(I)*YDF(J)
  230 CONTINUE
      DO 240 N=1,NZ
      SG(N)=SG(N)+S(N)
      FG(N)=FG(N)+F(N)
      DO 240 K=1,IHT
  240 EDACTG(K,N)=EDACTG(K,N)+EDACT(K,N)
      IF (G.NE.1) WRITE (NOUT,480)NN,G
      WRITE (NOUT,490)(N,RL(N),LL(N),TL(N),BL(N),NL(N),S(N),F(N),N=1,NZ)
      WRITE (NOUT,530)
      CALL WWRITE ( 2,2,EDACT,IHT,NZ,1,'ACT.FO','R XS 1','--IHT ',
     &' ZONE ')
      GO TO (350,250,350,250), IEDOPT
C
C     MICROSOPIC EDIT
C
  250 DO 340 K=1,MN
      CALL CLEARW(0.0,EDACT,IHTNZ)
      KK=MICID(K)
      DO 330 JB=1,JT
      DO 330 IB=1,IT
      I=IDX(IB)
      J=IDYA(JB)
      TA=FLUX(1,IB,JB)*V(IB,JB)
      IC=IABS(IDCS(I,J))
      IZ=NEDZ(I,J)
      T=1.0
      IF (IC.EQ.KK) GO TO 310
      T=0.0
      IF (MS.EQ.0) GO TO 310
      DO 300 M=1,MS
      N=MIXNUM(M)
      L=MIXCOM(M)
      AD=MIXDEN(M)
      IF (IC.NE.N) GO TO 300
      IF (AD.EQ.0.0) GO TO 260
      IF (L.EQ.0) GO TO 280
      IF (L.EQ.KK) GO TO 290
      GO TO 300
  260 IF (L.NE.0) GO TO 270
      GO TO 300
  270 T=T*EV
      GO TO 300
  280 T=T*AD
      GO TO 300
  290 T=T+AD
  300 CONTINUE
  310 DO 320 M=1,IHT
  320 EDACT(M,IZ)=EDACT(M,IZ)+T*TA*C(M,KK)*XDF(I)*YDF(J)
  330 CONTINUE
      WRITE (NOUT,520)KK,G
      CALL WWRITE ( 2,2,EDACT,IHT,NZ,1,'ACT.FO','R XS 1','--IHT ',
     &' ZONE ')
  340 CALL RITE (NEXTRA,0,EDACT,IHTNZ,3)
  350 CONTINUE
      IF (IGM.EQ.1) GO TO 360
      WRITE (NOUT,500)
      WRITE (NOUT,490)
     &(N,RLG(N),LLG(N),TLG(N),BLG(N),NLG(N),SG(N),FG(N),N=1,NZ)
      CALL WWRITE ( 2,2,EDACTG,IHT,NZ,1,'ACT.FO','R XS 1','--IHT ',
     &' ZONE ')
C
C     END OF STANDARD EDIT
C
  360 CONTINUE
      GO TO (460,420,370,370), IEDOPT
  370 CALL CLEARW(0.0,S,NZ)
C
C     RELATIVE POWER DENSITY
C
      ZVOL=0.0
      TVOL=0.0
      DO 380 J=1,JT
      DO 380 I=1,IT
      IB=IDX(I)
      JB=IDYA(J)
      IZ=NEDZ(IB,JB)
      IF (NORMZ.EQ.IZ) ZVOL=ZVOL+V(I,J)
      TVOL=TVOL+V(I,J)
  380 S(IZ)=S(IZ)+V(I,J)
      T=ZVOL/EDACTG(IHF,NORMZ)
      IF (NORMZ.GT.0) GO TO 400
      TPOW=0.0
      DO 390 N=1,NZ
  390 TPOW=TPOW+EDACTG(IHF,N)
      T=TVOL/TPOW
  400 CONTINUE
      DO 410 N=1,NZ
  410 RL(N)=T*EDACTG(IHF,N)/S(N)
      WRITE (NOUT,510)(N,S(N),RL(N),N=1,NZ)
      IF (IEDOPT.EQ.3) GO TO 460
C
C     MICROSCOPIC EDIT--SUM OVER ALL GROUPS
C
  420 IF (IGM.EQ.1) GO TO 460
      DO 450 K=1,MN
      CALL REED (NEXTRA,0,0.0,0,4)
      CALL CLEARW(0.0,EDACTG,IHTNZ)
      DO 440 G=1,IGM
      IREAD=MN
      IF (G.EQ.1) IREAD=K
      DO 430 J=1,IREAD
      CALL REED (NEXTRA,0,EDACT,ITEMP,3)
  430 CONTINUE
      DO 440 I=1,NZ
      DO 440 M=1,IHT
  440 EDACTG(M,I)=EDACTG(M,I)+EDACT(M,I)
      WRITE (NOUT,500)
      WRITE (NOUT,540)K
      CALL WWRITE ( 2,2,EDACTG,IHT,NZ,1,'ACT.FO','R XS 1','--IHT ',
     &' ZONE ')
  450 CONTINUE
C
  460 RETURN
C
  470 FORMAT ('0EDIT NUMBER ',I3,' GROUP NUMBER ',I3//)
  480 FORMAT (//////1H0/'0EDIT NUMBER ',I3,' GROUP NUMBER ',I3//)
  490 FORMAT (' EDIT ZONE',2X,'RIGHT LEAKAGE',3X,'LEFT LEAKAGE',5X,
     &'TOP LEAKAGE',3X,'BOTTOM LEAKAGE',4X,'NET LEAKAGE',8X,'SOURCE',
     &11X,'FLUX'//(1X,I5,4X,1P7E16.7))
  500 FORMAT (///'0SUM OVER ALL GROUPS'///)
  510 FORMAT (//' EDIT ZONE',5X,'VOLUME',5X,'RELATIVE POWER DENSITY'/
     &/(1X,I5,4X,1P2E16.7))
  520 FORMAT (////'0MICROSCOPIC ACTIVITY EDIT FOR MATERIAL ',I5,' GROU',
     &'P',I4)
  530 FORMAT (////'0MACROSCOPIC ACTIVITY EDIT ')
  540 FORMAT ('0MICROSCOPIC ACTIVITY EDIT FOR MATERIAL ',I5)
      END
