C             ERRO                LEVEL=1        DATE=80.09.29
      SUBROUTINE ERRO(A,J)
C   *** ERROR WRITES SAD MESSAGE, SEARCHES FOR 2 CONSECUTIVE T-S, AND
C       CALLS CONTROL IF THEY ARE FOUND.  BECAUSE ERROR, WHICH IS CALLED
C       FORM SUBORDINATE LINK, CALLS CONTROL, WHICH MAY OVERLAY
C       SUBORDINATE LINK, (WHEW) NOFLOW IS SPECIFIED ON IBJOB CARD.
      COMMON /SN1C/
     &       D(78),K(12),NIN,NOU,DUM(4),NT5
      COMMON /MAINC/III(1000)
      EQUIVALENCE (III(64),NOUT1)
CSASA DATA LT/'T   '/
      WRITE (NOUT1,10) A,J
   10 FORMAT('0****** ERROR ',3X,A4,I6)
      WRITE (NOUT1,20) (K(I),I=1,12)
   20 FORMAT(1H0,1X,12A4/'0TERMINATED')
CKSK  CALL CLOCK(NT5)
      CALL UCLOCK(NT5)
      STOP
      END
