C **********************************************************************
                     SUBROUTINE S824
C ***********************1987/5/13**************************************
     1 (SR,Q,MA,MZ,V,FD,CRX,XKE,SA,XN,XNI,XJ,B,XNN,CS,XNA
     1 ,CH,IH1,I1,J1,M1,IGM1,M2,IM1,M3,CT,CA,DF,TAB,J5,SG)
C   ***  S824  COMPUTES TOTAL SOURCE EXCLUSIVE OF IN-GROUP SCATTER
C       FOR EACH INTERVAL (SR=DIST SOURCE + FISS SOURCE + P(0) SCATTER
C       SOURCE    SA=P(L) SCATTER SOURCE)
      DIMENSION    TAB(1),CRX(IH1,IGM1,M3),XN(I1,2),XJ(I1,J1,1),B(M1,1),
     1 XNA(I1,1),CH(I1,1),SA(I1,1),SR(1),MA(1),MZ(1),V(1),FD(1),XKE(1),
     2 XNI(1),XNN(1),CS(1),Q(M2,IM1,1),CT(1),CA(1),DF(1),J5(1),SG(1)
      COMMON /SN1C/
     $              D(1),LIM1,LR,LW,LDSN,LMA,LMZ,LMB,LMC,LXMD,LFIX,LFLT,
     1       LJ5,LRM,LDF,LJ3,LJ4,LIGT,LART,LALFT,
     2LFGP,LFGG,LEND,LV,LAA,LWD,LMR,LPNC,
     BID,ITH,ISCT,ISN,IGE,IBL,IBR,IZM,IM,IEVT,IGM,IHT,IHS,IHM,MS,MCR,MTP
     C,MT,IDFM,IPVT,IQM,IPM,IPP,IIM,ID1,ID2,ID3,ID4,ICM,IDAT1,IDAT2,IFG,
     DIFLU,IFN,IPRT,IXTR,
     EEV,EVM,EPS,BF,DY,DZ,DFM1,XNF,PV,RYF,XLAL,XLAH,EQL,XNPM,
     FT(12),NIN,NOU,NT1,NT2,NT3,NT4,NT5,NT6,NT7
      COMMON /WORK/ Z(1),LIM2,LXKI,LFD,LXN,LVE,LMTT,LCRX,LQ,LPA,
     2       LXJ,LCH,LCA,LCF,LCT,LCS,LTAB,
     3LXND,LSA,LSAT,LRAV,LRA,LXNN,LXNE,LXNR,LXNA,LSR,LST,LQG,LFG,LSG,
     4LXKE,LXNI,LXNO,LT3,LT5,LDA,LDB,LDC,LDS,LB,IGMP,IGMM,IIGG,NERR,IMJT
     5,IHG,IMP,MP,NDS,NUS,SDG,SCG,AG,XNLGG,XNLG,SNG,ALA,ASR,EAM,EPG,EQ,
     6E1,E2,E3,E4,E5,E6,E7,E8,E9,E10,E11,E12,E13,E14,E15,E16,E17,E18,E19
     7,E20,ESC,ESM,EVP,EVPP,FTP,IC,ICVT,IGP,IG,IHP,IIC,IIG,IP,IZP,I01,
     8I02,I03,I04,I05,I06,I07,I08,I09,I00,JT,LC,MG,MI,ML,MM,NFN,XITR,
     9XLAP,XLAPP,XLAR,XLA,XNIO,XNII,ZZ1,ZZ2,ZZ3,XNB,XKEP,XKIP,IH,I,K,L,
     AM,J,N,NN,ISV
      IF(IDAT1.EQ.0)GO TO 824
      READ (NT3) ((CRX(IH,1,M),IH=1,IHP),M=1,MT)
      IF(IEVT.EQ.0)READ (NT3) ((Q(M,I,1),M=1,MP),I=1,IMP)
      IF(IIG.EQ.IGM)REWIND NT3
  824 DO 1 I=1,IM
      E4=V(I)
      IF(IDFM.GT.0)E4=E4*DF(I)
      SR(I)=0.0
      IF(IQM.NE.0)SR(I)=Q(1,I,IIGG)*V(I)
      IF(ITH.EQ.0)GO TO 2
      K=MA(I)
      K=IABS(MZ(K))
      SR(I)=  E4*FD(I)*CRX(IHT-1,IIGG,K) + SR(I)
      GO TO 22
    2 SR(I)=V(I)*FD(I)*XKE(IIG) + SR(I)
   22 DO 13 N=1,JT
   13 SA(I,N)=0.0
    1 CONTINUE
      XITR=0.0
      IH=IHM
   12 K=IIG+IHS-IH
      IF(K.LE.0)GO TO 3
      IF(K.GT.IGM)GO TO 4
C   *** E12 IS USED TO APPLY UPSCATTER SCALE FACTOR TO FLUXES AND
C       CURRENTS
      E12=1.0
      IF(IH.LE.IHS)E12=SG(IIG)
      IF(IDAT1.NE.2)GO TO 5
      IF(IIG-K .NE. 1) GO TO 25
      K=1
      WRITE (NT1) (XNN(I),I=1,IM),(B(M,1),M=1,MM)
      IF(ISCT.NE.0) WRITE (NT1) (XNA(I,1),I=1,IMJT)
      DO 26 I=1,IM
   26 XN(I,1)=XNN(I)
      IF(ISCT.EQ.0)GO TO 5
      DO 27 I=1,IMJT
   27 XJ(I,1,1)=XNA(I,1)
      GO TO 5
   25 K=1
      NTAPE=NT1
      IF(IH.GT.IHS)GO TO 17
      NTAPE = NT2
   17 READ (NTAPE)(XN(I,1),I=1,IM),(XNI(M),M=1,MM)
      IF(ISCT.GT.0)READ (NTAPE)(XJ(I,1,1),I=1,IMJT)
      IF(IH.NE.IHS)GO TO 5
      DO 6 M=1,MM
    6 B(M,1)=XNI(M)*E12
    5 DO 7 I=1,IM
      E4=V(I)
      IF(IDFM.GT.0)E4=E4*DF(I)
      J=MA(I)
      L=IABS(MZ(J))
      IF(IH.NE.IHS)GO TO 8
      XNN(I)=XN(I,K)*E12
C   *** COMPUTE TOTAL UPSCATTER FOR GROUP IIG DUE TO PREVIOUS FLUX  E13
      IF(NUS.NE.0)E13=E13 + CRX(IHP,IIGG,L)*XNN(I)*E4
      CS(I)=CRX(IHS,IIGG,L)*E4
      E1=CRX(IHT,IIGG,L)
      E2=CRX(IHT-2,IIGG,L)
      E99=CRX(IHT-3,IIGG,L)
      E3=0.0
      IF(IDFM.EQ.0)GO TO 18
      E1=E1*DF(I)
      E2=E2*DF(I)
      E99=E99*DF(I)
   18 IF(DY.GT.0.0)E3=3.289868*E99/(DY*E99 + BF)**2
      IF(DZ.GT.0.0)E3=E3 + 3.289868*E99/(DZ*E99 + BF)**2
      E1=E1 + E3
      IF(E1 + TAB(IIG) .GT. 0.0)GO TO 23
      CS(I)=CS(I) - TAB(IIG)*V(I)
      GO TO 24
   23 E1=E1 + TAB(IIG)
   24 CT(I)=E1*V(I)
      XITR=XITR+CS(I)
      CA(I)=(E2+ TAB(IIG) + E3)*V(I)
      GO TO 16
    8 SR(I)=SR(I) +  E4*XN(I,K)*CRX(IH,IIGG,L)*E12
   16 IF(ISCT.EQ.0)GO TO 7
      J=J5(J)
      NLO=1
      DO 9 N=1,ISCT
      L=L+1
      IF(IH.NE.IHS)GO TO 19
      CH(I,N)=0.0
      IF(N.LE.J)CH(I,N)=CRX(IH,IIGG,L)*E4
   19 NHI=NLO + (1-IABS(IGE-2))*(2*N+1)/4
      DO 10 NN=NLO,NHI
      IF(IH.NE.IHS)GO TO 11
      XNA(I,NN)=XJ(I,NN,K)*E12
      GO TO 10
   11 IF(N.GT.J)GO TO 10
      SA(I,NN)=SA(I,NN) +   E4*XJ(I,NN,K)*CRX(IH,IIGG,L)*E12
   10 CONTINUE
      NLO=NHI+1
    9 CONTINUE
    7 CONTINUE
    3 IH=IH-1
      IF(IH.GT.IHT)GO TO 12
    4 DO 20 I=1,IM
   20 ZZ1=ZZ1 + SR(I)
      IF(IDAT1.NE.2)GO TO 14
      IF(IIG.LT.IGM)GO TO 21
      REWIND NT2
      GO TO 14
   21 IF(NUS.EQ.0)GO TO 14
      N=MIN0(NUS,IGM-IIG)
      IF(ISCT.GT.0)N=N+N
      DO 15 I=1,N
   15 BACKSPACE NTAPE
   14 RETURN
      END
