C             SEPTE               LEVEL=7        DATE=84.06.13
      SUBROUTINE  SEPTE(INITAL,WITHX)
C
      REAL BUFFER(1024),ADATE(2)
      INTEGER ATIME
      COMMON /MAINC/  IOPT(500)
CKSK  COMMON /PLTCNT/ JJPLT
C     SEPARATER LINE AND ORIGIN SET
C     DATA JJPLT,WITHXX / 0,0.0 /
      DATA    WITHXX / 0.0 /
C
CKSK  JJPLT=JJPLT+1
CKSK  JJPLT=JJPLT+IOPT(97)
CKSK  IF(JJPLT.EQ.1) CALL PLOTS(BUFFER(1),1024)
CKSK  IOPT(97)=1
CKSK FOR UNIX VERSION(PIFLIB) 2/22/96 BY K.OKUMURA
      IF(IOPT(97).EQ.0) THEN
        CALL PLOTS(0,0)
        IOPT(97)=1
      ELSE
        CALL PLOT(0.0,0.0,666)
      ENDIF
CKSK **********************************
      CALL NEWPEN(1)
      CALL FACTOR( 1.0 )
C     SEPARATER PLOT
CKSK  IF(JJPLT.GT.1) CALL PLOT( 0. ,-2. ,-3)
CKSK  IF(JJPLT.GT.1) CALL NEXTCT( 300. )
CKSK  IF(JJPLT.GT.1) CALL PLOT(0.0,0.0,666)
      CALL PLOT(10. , 2. ,-3 )
C
      WITHXX=WITHX
      RETURN
      END
