C             SIGRD               LEVEL=3        DATE=82.07.05
      SUBROUTINE SIGRD(SIG,NM,NG)
      DIMENSION SIG(NG,1)
      COMMON /MAINC/ DUM(94),IFA,MXDIM,IOPEN,ITYPE,DUM1(402)
C     COMMON /PIJ2C/ DDUM(32),ITYPE,DUM2(967)
      K=IFA
      REWIND K
      IFLAG=0
      DO 10 I=1,NM
      READ(K) (SIG(J,I),J=1,NG)
      DO 5 J=1,NG
      IF(SIG(J,I).LE.0.) IFLAG=I
    5 CONTINUE
      IF(IFLAG.NE.0) GO TO 20
   10 CONTINUE
      RETURN
   20 WRITE(6,30) I,(SIG(J,I),J=1,NG)
   30 FORMAT(//1H ,'   *** MATERIAL ',I2,' CONTAINS NON POSITIVE SIG '
     & ,'TOTAL '/(10X,6E12.5))
      WRITE(6,31)
   31 FORMAT('    *** VERIFY MATERIAL SPECIFICATION WHETHER IF NO NUCLI'
     & ,'DE ASSIGNED TO THE MIXTURE')
      STOP
      END
