C **********************************************************************
                      SUBROUTINE SUMARY
C ********************1987/5/13 TRANSPORT IN BUCKLING CORRECTION *******
     1 (XKI,FD,XN,  VE,W,DSN,MA,MZ,CRX,Q,PA,DF,I2,CA,CF,
     1CT,CS,V,AA,TAB,WD,XND,FXS,FIS,SNN,SFS,OTS,APS,FRT,TXN,DEN,RFL,RCT,
     2RLK,XLL,XLK,XBB,RXN,IG1,I1,IH1,IGM1,M1,IM1)
C   *** SUMARY PRINTS ANGULAR FLUXES AND COMPUTES SUMMARY TABLES
      DIMENSION XKI(1),FD(1),XN(I1,1),     VE(1),W(1),DSN(1),MA(1),MZ(1)
     1,CRX(IH1,IGM1,1),Q(I1,1),PA(M1,IM1,1),DF(1),CA(1),CF(1),CT(1),
     2 CS(1),V(1),AA(1),TAB(1),WD(1),XND(I2,1),FXS(IG1,1),FIS(IG1,1),
     3 SNN(IG1,1),SFS(IG1,1),OTS(IG1,1),APS(IG1,1),XLK(IG1,1),XBB(IG1,1)
     4,RXN(IG1,1),RFL(IG1,1),RCT(IG1,1),RLK(IG1,1),XLL(IG1,1),FRT(IG1,1)
     5,TXN(IG1,1),DEN(IG1,1)
      COMMON /SN1C/
     &              D(1),LIM1,LR,LW,LDSN,LMA,LMZ,LMB,LMC,LXMD,LFIX,LFLT,
     1       LJ5,LRM,LDF,LJ3,LJ4,LIGT,LART,LALFT,
     2LFGP,LFGG,LEND,LV,LAA,LWD,LMR,LPNC,
     BID,ITH,ISCT,ISN,IGE,IBL,IBR,IZM,IM,IEVT,IGM,IHT,IHS,IHM,MS,MCR,MTP
     C,MT,IDFM,IPVT,IQM,IPM,IPP,IIM,ID1,ID2,ID3,ID4,ICM,IDAT1,IDAT2,IFG,
     DIFLU,IFN,IPRT,IXTR,
     EEV,EVM,EPS,BF,DY,DZ,DFM1,XNF,PV,RYF,XLAL,XLAH,EQL,XNPM,
     FT(12),NIN,NOU,NT1,NT2,NT3,NT4,NT5,NT6,NT7
      COMMON /WORK/ Z(1),LIM2,LXKI,LFD,LXN,LVE,LMTT,LCRX,LQ,LPA,
     2       LXJ,LCH,LCA,LCF,LCT,LCS,LTAB,
     3LXND,LSA,LSAT,LRAV,LRA,LXNN,LXNE,LXNR,LXNA,LSR,LST,LQG,LFG,LSG,
     4LXKE,LXNI,LXNO,LT3,LT5,LDA,LDB,LDC,LDS,LB,IGMP,IGMM,IIGG,NERR,IMJT
     5,IHG,IMP,MP,NDS,NUS,SDG,SCG,AG,XNLGG,XNLG,SNG,ALA,ASR,EAM,EPG,EQ,
     6E1,E2,E3,E4,E5,E6,E7,E8,E9,E10,E11,E12,E13,E14,E15,E16,E17,E18,E19
     7,E20,ESC,ESM,EVP,EVPP,FTP,IC,ICVT,IGP,IG,IHP,IIC,IIG,IP,IZP,I01,
     8I02,I03,I04,I05,I06,I07,I08,I09,I00,JT,LC,MG,MI,ML,MM,NFN,XITR,
     9XLAP,XLAPP,XLAR,XLA,XNIO,XNII,ZZ1,ZZ2,ZZ3,XNB,XKEP,XKIP,IH,I,K,L,
     AM,J,N,NN,ISV
      IF(ID1.EQ.0) GO TO 999
C
C     LOOP OF ENERGY GROUP
C
      DO 1 IIG=1,IGM
      IIGG=IIG
      READ (NT4)((XND(I,M),I=1,IP),M=1,MM)
C   *** PRINT ANGULAR FLUX
CADD
      IF(ID1.LT.0)  GO TO    2
CTFREE
      IF(IIG.NE.1)  GO TO 3333
      WRITE (NOU,10)IIG
      GO TO 3334
 3333 CONTINUE
      WRITE(NOU,3335) IIG
 3335 FORMAT(/////,1X,' FLUX BY ANGLE AND POINT FOR GROUP  ',I3)
 3334 CONTINUE
   10 FORMAT(37H1 FLUX BY ANGLE AND POINT FOR GROUP  ,I3)
      CALL WOT(XND,MM,IP,1,'PNT.','ANGL',0)
C
    2 IF(IDAT1.EQ.0)GO TO 3
      IIGG=1
      READ (NT3) ((CRX(IH,1,M),IH=1,IHP),M=1,MT)
      I01=MP*IMP
      IF(IEVT.EQ.0)READ (NT3) (Q(I,1),I=1,I01)
C   *** COMPUTE SUMMARY TABLES
    3 IH=IHM
    4 K=IIG+IHS-IH
      IF(K.LE.0)GO TO 5
      IF(K.GT.IGM)GO TO 6
      IF(IDAT1.NE.2)GO TO 7
      K=1
      READ (NT1) (XN(I,1),I=1,IM)
      IF(ISCT.GT.0)READ (NT1)
    7 DO 8 I=1,IM
      J=MA(I)
      L=IABS(MZ(J))
      J=MIN0(J,IZM)
      E4=V(I)
      IF(IDFM.GT.0)E4=E4*DF(I)
      IF(IH.NE.IHS)GO TO 39
      CS(I)=XN(I,K)
      E1=CRX(IHT,IIGG,L)
      E2=CRX(IHT-2,IIGG,L)
      E3=0.0
C **  TRANSPORT CROSS SECTION
      TR=CRX(IHT-3,IIGG,L)
      IF(IDFM.EQ.0)GO TO 11
      E1=E1*DF(I)
      E2=E2*DF(I)
C   *** TRANSVERSE BUCKLING CORRECTION
   11 IF(DY.GT.0.0) E3=3.289868*TR/(DY*TR +BF)**2
      IF(DZ.GT.0.0) E3=E3 + 3.289868*TR/(DZ*TR + BF)**2
      CT(I)=(E1 + TAB(IIG) + E3)*CS(I) *V(I)
      CA(I)=(E2 + TAB(IIG) + E3)*CS(I) *V(I)
      GO TO 8
C   *** FXS - FIXED SOURCE
C   *** FIS - FISSION SOURCE
C   *** SNN - SCATTER GAINS
C   *** SFS - SELF SCATTER
C   *** OTS - SCATTER LOSSES
C   *** APS - ABSORPTIONS
C   *** XLK - NET LEAKAGE
C   *** XBB - NEUTRON BALANCE  (GAINS/LOSSES)
C   *** RXN - FLUX AT RIGHT BOUNDARY
C   *** RFL - J+ AT RIGHT BOUNDARY
C   *** RCT - J-NET AT RIGHT BOUNDARY
C   *** RLK - RIGHT LEAKAGE
C   *** XLL - LEFT LEAKAGE
C   *** FRT - FISSION RATE
C   *** TXN - TOTAL FLUX
C   *** DEN - DENSITY
   39 SNN(IIG,J)=SNN(IIG,J) + CRX(IH,IIGG,L)*XN(I,K)*E4
    8 CONTINUE
    5 IH=IH-1
      IF(IH.GT.IHT)GO TO 4
    6 IF(IDAT1.NE.2)GO TO 35
      IF(NDS.LT.IIG .AND. IIG.NE.IGM)GO TO 43
      REWIND NT1
      GO TO 35
   43 N=NDS + MIN0(NUS,IGM-IIG)
      IF(ISCT.GT.0)N=N+N
      DO 36 I=1,N
   36 BACKSPACE NT1
   35 E1=EV
      IF(IEVT.NE.1)E1=1.0
      DO 9 I=1,IM
      J=MA(I)
      K=IABS(MZ(J))
      J=MIN0(J,IZM)
      E4=V(I)
      IF(IDFM.GT.0)E4=E4*DF(I)
      IF(ITH.EQ.0)GO TO 41
      FIS(IIG,J)=FIS(IIG,J) + CRX(IHT-1,IIGG,K)*FD(I)*E4
      GO TO 42
   41 FIS(IIG,J)=FIS(IIG,J) + XKI(IIG)*FD(I)*V(I)/E1
   42 SFS(IIG,J)=SFS(IIG,J) + CS(I)*CRX(IHS,IIGG,K) *E4
      OTS(IIG,J)=OTS(IIG,J) + CT(I)
      APS(IIG,J)=APS(IIG,J) + CA(I)
      TXN(IIG,J)=TXN(IIG,J) + CS(I)*V(I)
      IF(IQM.NE.0)FXS(IIG,J)=FXS(IIG,J) + Q(I,IIGG)*V(I)
    9 FRT(IIG,J)=FRT(IIG,J) + CS(I)*CRX(IHT-1,IIGG,K)*E4
      DO 12 J=1,IZM
      DEN(IIG,J)=TXN(IIG,J)/VE(IIG)
   12 OTS(IIG,J)=OTS(IIG,J) - APS(IIG,J) - SFS(IIG,J)
      IF(IPM.EQ.0)GO TO 13
      J=MIN0(IZM,MA(IPP))
      DO 17 I=1,IM
      IF(IPM.GT.1)J=MIN0(MA(I),IZM)
      E4=0.0
      DO 16 M=1,MM
   16 E4=E4 + PA(M,I,IIGG)*ABS(WD(M))
      IF(IPM.EQ.1)GO TO 15
   17 FXS(IIG,J)=FXS(IIG,J) + E4*AA(I+1)
      GO TO 13
   15 FXS(IIG,J)=FXS(IIG,J) + E4*AA(IPP+1)
   13 DO 18 J=1,IZP
      IF(J.NE.IZP .AND. IZM.NE.1)GO TO 24
      I01=1
      I02=IM
      GO TO 25
   24 DO 19 I01=1,IM
      IF(J.EQ.MA(I01))GO TO 21
   19 CONTINUE
   21 I02=IP
   22 I02=I02-1
      IF(J.NE.MA(I02))GO TO 22
   25 DO 23 M=1,MM
      RXN(IIG,J)=RXN(IIG,J) + XND(I02+1,M)*W(M)
      IF(WD(M).GT.0.0)RFL(IIG,J)=RFL(IIG,J) + XND(I02+1,M)*WD(M)
      RCT(IIG,J)=RCT(IIG,J) + XND(I02+1,M)*WD(M)
   23 XLL(IIG,J)=XLL(IIG,J) + XND(I01,M)*WD(M)
      RLK(IIG,J)=RCT(IIG,J)*AA(I02+1)
      XLL(IIG,J)=XLL(IIG,J)*AA(I01)
      XLK(IIG,J)=RLK(IIG,J) - XLL(IIG,J)
   18 CONTINUE
    1 CONTINUE
C
C     END OF ENERGY GROUP
C
      REWIND NT4
      IF(IDAT1.NE.0)REWIND NT3
   37 DO 34 K=1,16
      L=(K-1)*IZP
      M=L+IZP
      DO 26 J=1,IZP
      N=L+J
      DO 27 IIG=1,IGM
      E1=FXS(IIG,N)
      IF(J.EQ.IZP)GO TO 28
      FXS(IGP,N)=FXS(IGP,N) + E1
      IF(K.GT.9)GO TO 27
      FXS(IIG,M)=FXS(IIG,M) + E1
      GO TO 27
   28 FXS(IGP,M)=FXS(IGP,M) + E1
   27 CONTINUE
   26 CONTINUE
   34 CONTINUE
C
      DO 29 J=1,IZP
      DO 29 IIG=1,IGP
      E1=FXS(IIG,J) + FIS(IIG,J) + SNN(IIG,J)
      E2=OTS(IIG,J) + APS(IIG,J) + XLK(IIG,J)
      IF(E1+E2 .EQ. 0.0) GO TO 299
      XBB(IIG,J)=1.0 + (E1-E2)/(E1+E2)
      GO TO 29
  299 XBB(IIG,J)=1.0
   29 CONTINUE
C
      DO 38 J=1,IZP
   32 IF(J.EQ.IZP)GO TO 31
C   *** PRINT SUMMARY TABLES
      WRITE (NOU,20) J,IGP
      GO TO 33
   31 WRITE (NOU,30)
   33 WRITE (NOU,40) (I,FXS(I,J),FIS(I,J),SNN(I,J),SFS(I,J),OTS(I,J),APS
     1(I,J),XLK(I,J),XBB(I,J),I=1,IGP)
      WRITE (NOU,50) (I,RXN(I,J),RFL(I,J),RCT(I,J),RLK(I,J),XLL(I,J),FRT
     1(I,J),TXN(I,J),DEN(I,J),I=1,IGP)
   38 CONTINUE
C
   20 FORMAT(18H1 SUMMARY FOR ZONE,I3,47H BY GROUP INCLUDING SUM FOR ALL
     1 GROUPS IN LINE ,I3)
   30 FORMAT(20H1 SUMMARY FOR SYSTEM)
   40 FORMAT(108H0 GRP.  FIX  SOURCE  FISS SOURCE  IN  SCATTER  SLF SCAT
     1TER  OUT SCATTER   ABSORPTION    LEAKAGE      BALANCE/(I6,1P8E13.5
     2))
   50 FORMAT(108H0 GRP.  RT BDY FLUX   RT BDY J+    RT BDY J     RT LEAK
     1AGE  LFT LEAKAGE   FISS RATE    TOTAL FLUX    DENSITY/(I6,1P8E13.5
     2))
C
      IF(ID.LT.1000000)GO TO 999
      CALL AFACTR(MZ,D(LMB),D(LMC),D(LXMD),MA,V,XN,DF,TAB,IM,IGM)
  999 RETURN
C
      END
