      SUBROUTINE README
C-----------------------------------------------------------------------
C     THIS IS A DUMMY PROGRAM TO SPECIFY CONTENTS OF PDSMDL PROGRAMS.
C     PDSMDL by K.OKUMURA in JAERI
C-----------------------------------------------------------------------
C  ENGEDT   : SUBROUTINE TO EDIT ENERGY GRUOP STRUCTURE
C  ENGWRT   : SUBROUTINE TO WRITE ENERGY GRUOP STRUCTURE
C  FLXEDT   : SUBROUTINE TO EDIT FLUX DATA
C  FLXWRT   : SUBROUTINE TO WRITE FLUX DATA
C  MACEDT   : SUBROUTINE TO EDIT MACRO/MACROWRK XS DATA
C  MACWRT   : SUBROUTINE TO WRITE MACRO/MACROWRK XS DATA
C  BNPEDT   : SUBROUTINE TO EDIT HETEROGENEOS BURNUP TABLE(----BNUP)
C             FROM MACRO/MACROWRK FILE
C  BNPWRT   : SUBROUTINE TO WRITE HETEROGENEOS BURNUP TABLE(----BNUP)
C             IN MACRO/MACROWRK FILE
C  DNTEDT   : SUBROUTINE TO EDIT HOMOGENEOUS BURNUP TABLE(----DN?T)
C             FROM MACRO/MACROWRK FILE
C  DNTWRT   : SUBROUTINE TO WRITE HOMOGENEOUS BURNUP TABLE(----DN?T)
C             IN MACRO/MACROWRK FILE
C  MICEDT   : SUBROUTINE TO EDIT MICRO XS DATA FROM MICREF FILE
C  DLYEDT   : SUBROUTINE TO EDIT NUCLIDE-WISE DELAYED NEUTRON DATA
C             FROM FASTP FILE
C  FASTLB   : SUBROUTINE TO EDIT ENERGY STRUCTURE OF PUBLIC FAST LIB.
C  PDSIN    : SUBROUTINE TO READ/WRITE PDS FILE (ALWAYS NECESSARY)
C             PDSOUT IS INCLUDED AS ENTRY
C  PDSNM    : GIVE FULL FILE NAME TO PDS MEMBER,
C             CALLED FROM PDSIN/PDSOUT
C  PDSSR    : SEARCH PDS MEMBER, CALLED FROM PDSIN/PDSOUT
C  PDSRD    : READ CONTENTS OF PDS, CALLED FROM PDSIN
C  PDSWT    : WRITE CONTENTS OF PDS, CALLED FROM PDSOUT
C  PDSLN    : GIVE DATA LENGTH (WORDS) OF MEMBER
C  PDSRM    : REMOVE A MEMBER IN PDS
C-----------------------------------------------------------------------
      RETURN
      END
