C             AFACTR              LEVEL=2        DATE=82.02.19
      SUBROUTINE  AFACTR (MZ,MB,MC,XMD,MA,V,XN,DF,F,I1,IG1)
      DIMENSION MZ(1),MB(1),MC(1),XMD(1),MA(1),V(1),DF(1),XN(I1,1),
     & F(IG1,1)
      COMMON /SN1C/
     &              D(1),LIM1,LR,LW,LDSN,LMA,LMZ,LMB,LMC,LXMD,LFIX,LFLT,
     &       LJ5,LRM,LDF,LJ3,LJ4,LIGT,LART,LALFT,
     &LFGP,LFGG,LEND,LV,LAA,LWD,LMR,LPNC,
     &ID,ITH,ISCT,ISN,IGE,IBL,IBR,IZM,IM,IEVT,IGM,IHT,IHS,IHM,MS,MCR,MTP
     &,MT,IDFM,IPVT,IQM,IPM,IPP,IIM,ID1,ID2,ID3,ID4,ICM,IDAT1,IDAT2,IFG,
     &IFLU,IFN,IPRT,IXTR,
     &EV,EVM,EPS,BF,DY,DZ,DFM1,XNF,PV,RYF,XLAL,XLAH,EQL,XNPM,
     &T(12),NIN,NOU,NT1,NT2,NT3,NT4,NT5,NT6,NT7
      COMMON /WORK/ Z(1),LIM2,LXKI,LFD,LXN,LVE,LMTT,LCRX,LQ,LPA,
     &       LXJ,LCH,LCA,LCF,LCT,LCS,LTAB,
     &LXND,LSA,LSAT,LRAV,LRA,LXNN,LXNE,LXNR,LXNA,LSR,LST,LQG,LFG,LSG,
     &LXKE,LXNI,LXNO,LT3,LT5,LDA,LDB,LDC,LDS,LB,IGMP,IGMM,IIGG,NERR,IMJT
     &,IHG,IMP,MP,NDS,NUS,SDG,SCG,AG,XNLGG,XNLG,SNG,ALA,ASR,EAM,EPG,EQ,
     &E1,E2,E3,E4,E5,E6,E7,E8,E9,E10,E11,E12,E13,E14,E15,E16,E17,E18,E19
     &,E20,ESC,ESM,EVP,EVPP,FTP,IC,ICVT,IGP,IG,IHP,IIC,IIG,IP,IZP,I01,
     &I02,I03,I04,I05,I06,I07,I08,I09,I00,JT,LC,MG,MI,ML,MM,NFN,XITR,
     &XLAP,XLAPP,XLAR,XLA,XNIO,XNII,ZZ1,ZZ2,ZZ3,XNB,XKEP,XKIP,IH,I,K,L,
     &M,J,N,NN,ISV
      IF(IDAT1.EQ.2)GO TO 999
      WRITE (6,10)
      WRITE(6,20)
   20 FORMAT('0  SET     MAT.')
      NCNT=0
      DO 1 N=1,MT
      DO 2 J=1,IZM
      MAZ=MZ(J)
      IF(MAZ.EQ.N)GO TO 3
      DO 4 M=1,MS
      IF(MB(M).EQ.MAZ .AND. MC(M).EQ.N)GO TO 3
    4 CONTINUE
    2 CONTINUE
      GO TO 1
    3 NCNT=NCNT+1
      WRITE(6,30)NCNT,N
   30 FORMAT(I6,I8)
      DO 5 IG=1,IGM
      XN1=0.0
      XN2=0.0
      XD1=0.0
      XD2=0.0
      DO 6 I=1,IM
      J=MA(I)
      XNUM=0.0
      IF(N.EQ.MZ(J))GO TO 7
      DO 8 M=1,MS
      X=XMD(M)
      IF(MB(M).EQ.MZ(J) .AND. MC(M).EQ.N)GO TO 9
    8 CONTINUE
      GO TO 11
    7 XNUM=1.0
      GO TO 11
    9 XNUM=X
   11 IF(IDFM.NE.0)XNUM=XNUM*DF(I)
      XN1=XN1 + V(I)*XNUM*XN(I,IG)
      XN2=XN2 + V(I)*XNUM
      XD1=XD1 + V(I)*XN(I,IG)
      XD2=XD2 + V(I)
    6 CONTINUE
      F(IG,NCNT)=(XN1/XN2)/(XD1/XD2)
    5 CONTINUE
    1 CONTINUE
      CALL WOT(F,NCNT,IGM,1,'GRP.',' SET',0)
   10 FORMAT('1  ADVANTAGE FACTORS')
  999 RETURN
      END
