C             IFRITE              LEVEL=1        DATE=81.11.14
      SUBROUTINE IFRITE ( AFI,AH1,AH2,AFJ,AV1,AV2,FLUX,FLUXA,WGT,COSMU,
     &COSETA,WGT4,COSMU4,COSET4,NM,MM,IT,ITP,JT,MM4 )
C
C     WRITES INTERFACE OUTPUT SCALAR FLUX, ANGULAR FLUX
C     AND SN CONSTANTS FILES
C
      COMMON /TW1C/ DD(1),LIM1,IA(210)
      COMMON /WORK/AAA(1),LIM2,AA(130)
      DIMENSION D(212),A(132)
      EQUIVALENCE (D(1),DD(1)),(AAA(1),A(1))
      EQUIVALENCE (D(163),IAFLUX),(D(134),IFO),(D(112),IPFX),(D(165),ISN
     &CON),(D(164),ITFLUX),(D(113),LTFX),(D(132),LTHAF),(D(133),LTVAF),
     &(D(114),LXFX),(D(158),NAFLUX),(D(157),NOUT),(A(32),OITNO)
C
      DIMENSION AFI(MM4,ITP),AH1(ITP,MM),AH2(ITP,MM),AFJ(MM4,IT),
     &AV1(IT,MM),AV2(IT,MM),FLUX(NM,IT,JT)
      DIMENSION FLUXA(1),WGT(1),COSMU(1),COSETA(1),WGT4(1),COSMU4(1),
     &COSET4(1)
      DIMENSION IDENT(4), IDENTX(1), ISPEC(8), TAPEID(5)
C
      EQUIVALENCE (ISPEC(7),EVSC), (ISPEC(8),NORMSC)
      EQUIVALENCE (IDENT(4),IDENTX(1))
C
      EQUIVALENCE (IA(1),ITH),(IA(4),IGM),(IA(24),IANG),(IA(37),EV),
     &(IA(48),NORM),(IA(66),ITJT),(IA(78),JTP),(A(32),OTINO),
     &(D(85),IANGPR)
C
      INTEGER OITNO
      REAL NORM,NORMSC
C
CSASA REAL*8 IDENT,TAPEID
      CHARACTER*8 IDENT,TAPEID
C
      DATA IDENT/'      ','TWOTRA','N OUT ','      '/
      DATA TAPEID/'RTFLUX','ATFLUX','RAFLUX','AAFLUX','SNCONS'/
C
      IF (IFO.EQ.0) GO TO 140
C
C     SET LENGTH OF SPECIFICATION VECTOR, IDENTIFICATION VECTOR
C     AND VERSION NUMBER
C
      NSPEC=8
      NDENT=4
      IDENTX(1)=2
C
C     DEFINE SPECIFICATION VECTOR
C
      ISPEC(1)=2
      ISPEC(2)=IGM
      ISPEC(3)=IT
      ISPEC(4)=JT
      ISPEC(5)=1
      ISPEC(6)=OITNO-1
      EVSC=EV
      NORMSC=NORM
C
C     CREATE STANDARD INTERFACE TOTAL FLUX FILE
C
      IF (ITH.NE.0) GO TO 100
      INDEX=1
      NCOUNT=8
      GO TO 110
  100 CONTINUE
      INDEX=2
      NCOUNT=7
  110 CONTINUE
      IDENT(1)=TAPEID(INDEX)
C
C     WRITE FILE IDENTIFICATIONS AND SPECIFICATIONS
C
      CALL REED (ITFLUX,0,0.0,0,4)
C     CALL RITE (ITFLUX,IDENT(4),IDENT,NDENT,9)
C     CALL RITE (ITFLUX,0,ISPEC,NCOUNT,2)
C
C     STORE TOTAL FLUX COMPACTLY AND WRITE ON FILE
C
      DO 130 IG=1,IGM
      CALL REED (0,IPFX+(IG-1)*LTFX,FLUX,LXFX,1)
      IDX=1
      DO 120 J=1,JT
      DO 120 I=1,IT
      FLUXA(IDX)=FLUX(1,I,J)
      IDX=IDX+1
  120 CONTINUE
      CALL RITE (ITFLUX,0,FLUXA,ITJT,2)
  130 CONTINUE
      CALL RITE (ITFLUX,0,0.0,0,4)
  140 CONTINUE
      WRITE ( NOUT, 360 ) IDENT ( 1 ), ITFLUX
      IF (IANG.EQ.0) GO TO 320
      IF (IFO.EQ.0) GO TO 170
C
C     CREATE STANDARD INTERFACE ANGULAR FLUX FILE
C
      IF (ITH.NE.0) GO TO 150
      INDEX=3
      GO TO 160
  150 CONTINUE
      INDEX=4
  160 CONTINUE
      IDENT(1)=TAPEID(INDEX)
      ISPEC(6)=MM4
C
C     WRITE FILE IDENTIFICATIONS AND SPECIFICATIONS
C
      CALL REED (IAFLUX,0,0.0,0,4)
      CALL RITE (IAFLUX,IDENT(4),IDENT,NDENT,9)
      CALL RITE (IAFLUX,0,ISPEC,NCOUNT,2)
C
C     PROCESS HORIZONTAL ANGULAR FLUXES
C
  170 CONTINUE
      CALL REED (NAFLUX,0,0.0,0,4)
      DO 240 IG=1,IGM
      CALL REED (NAFLUX,0,0.0,2*JTP,7)
      DO 230 J=1,JT
      CALL REED (NAFLUX,0,AH1,LTHAF,2)
      MMX1=1
      MMX2=MMX1+MM
      MMX3=MMX2+MM
      MMX4=MMX3+MM
      DO 190 M=1,MM
      DO 180 I=1,ITP
      AFI(MMX1,I)=AH1(I,M)
      AFI(MMX2,I)=AH2(I,M)
  180 CONTINUE
      MMX1=MMX1+1
      MMX2=MMX2+1
  190 CONTINUE
      CALL REED (NAFLUX,0,AH1,LTHAF,2)
      DO 210 M=1,MM
      DO 200 I=1,ITP
      AFI(MMX3,I)=AH1(I,M)
      AFI(MMX4,I)=AH2(I,M)
  200 CONTINUE
      MMX3=MMX3+1
      MMX4=MMX4+1
  210 CONTINUE
      IF (IANGPR.GT.0) GO TO 220
      WRITE (NOUT,340)J,IG
      CALL WWRITE( 2,2,AFI,MM4,ITP,1,'      ','      ','      ','I MESH'
     & )
      IF (IFO.EQ.0) GO TO 230
  220 CONTINUE
      CALL RITE (IAFLUX,0,AFI,MM4*ITP,2)
  230 CONTINUE
  240 CONTINUE
C
C     PROCESS VERTICAL ANGULAR FLUXES
C
      CALL REED (NAFLUX,0,0.0,0,4)
      DO 310 IG=1,IGM
      DO 300 J=1,JTP
      CALL REED (NAFLUX,0,AV1,LTVAF,2)
      MMX1=1
      MMX2=MMX1+MM
      MMX3=MMX2+MM
      MMX4=MMX3+MM
      DO 260 M=1,MM
      DO 250 I=1,IT
      AFJ(MMX1,I)=AV1(I,M)
      AFJ(MMX2,I)=AV2(I,M)
  250 CONTINUE
      MMX1=MMX1+1
      MMX2=MMX2+1
  260 CONTINUE
      CALL REED (NAFLUX,0,AV1,LTVAF,2)
      DO 280 M=1,MM
      DO 270 I=1,IT
      AFJ(MMX3,I)=AV1(I,M)
      AFJ(MMX4,I)=AV2(I,M)
  270 CONTINUE
      MMX3=MMX3+1
      MMX4=MMX4+1
  280 CONTINUE
      IF (IANGPR.GT.0) GO TO 290
      WRITE (NOUT,350)J,IG
      CALL WWRITE( 2,2,AFJ,MM4,IT,1,'       ','      ','      ','I MESH'
     &)
      IF (IFO.EQ.0) GO TO 300
  290 CONTINUE
      CALL RITE (IAFLUX,0,AFJ,MM4*IT,2)
  300 CONTINUE
      CALL REED (NAFLUX,0,0.0,2*JT,7)
  310 CONTINUE
      IF ( IFO .EQ. 0 ) GO TO 311
      CALL RITE ( IAFLUX, 0, 0.0, 0, 4 )
      WRITE ( NOUT, 360 ) IDENT ( 1 ), IAFLUX
  311 CONTINUE
      CALL REED (NAFLUX,0,0.0,0,4)
  320 CONTINUE
      IF (IFO.EQ.0) RETURN
C
C     CREATE STANDARD INTERFACE SN CONSTANTS FILE
C
      INDEX=5
      NCOUNT=4
      ISPEC(2)=MM4
      ISPEC(3)=0
      ISPEC(4)=0
      IDENT(1)=TAPEID(INDEX)
C
C     GENERATE TOTAL ANGULAR ARRAYS
C
      MMX1=1
      MMX2=MMX1+MM
      MMX3=MMX2+MM
      MMX4=MMX3+MM
      DO 330 M=1,MM
      COSET4(MMX1)=-COSETA(M)
      COSET4(MMX2)=-COSETA(M)
      COSET4(MMX3)=COSETA(M)
      COSET4(MMX4)=COSETA(M)
      COSMU4(MMX1)=-COSMU(M)
      COSMU4(MMX2)=COSMU(M)
      COSMU4(MMX3)=-COSMU(M)
      COSMU4(MMX4)=COSMU(M)
      WGT4(MMX1)=WGT(M)
      WGT4(MMX2)=WGT(M)
      WGT4(MMX3)=WGT(M)
      WGT4(MMX4)=WGT(M)
      MMX1=MMX1+1
      MMX2=MMX2+1
      MMX3=MMX3+1
      MMX4=MMX4+1
  330 CONTINUE
C
C     WRITE FILE
C
      CALL REED (ISNCON,0,0.0,0,4)
      CALL RITE (ISNCON,IDENT(4),IDENT,NDENT,9)
      CALL RITE (ISNCON,0,ISPEC,NCOUNT,2)
      CALL RITE (ISNCON,0,WGT4,3*MM4,2)
      CALL RITE (ISNCON,0,0.0,0,4)
      WRITE ( NOUT, 360 ) IDENT ( 1 ), ISNCON
      RETURN
C
  340 FORMAT ('0ANGULAR FLUX AT FIRST DIMENSION BOUNDARIES J = ',I6,
     &' GROUP = ',I3)
  350 FORMAT ('0ANGULAR FLUX AT SECOND DIMENSION BOUNDARIES J = ',I6,
     &' GROUP = ',I3)
  360 FORMAT ('0     INTERFACE FILE ',A6,' HAS BEEN PREPARED ON',
     &' UNIT ',I2)
      END
