C             INITQ               LEVEL=1        DATE=81.11.14
      SUBROUTINE INITQ ( IDX,IDYA,Q,QG,QQG,YH,A4,A5,WMU,WETA,QR1,QR2,
     &QT1,QT2,QB1,QB2,A3,NM,ITJT,IM,JM,IT,JT,MM )
C
      COMMON /TW1C/ DD(1),LIM1,IA(210)
      COMMON /WORK/AAA(1),LIM2,AA(130)
      DIMENSION D(212),A(132)
      EQUIVALENCE (D(1),DD(1)),(AAA(1),A(1))
      EQUIVALENCE (D(120),IPQS),(D(127),I5),(D(121),LTQS),(D(157),NOUT)
C
      DIMENSION IDX(1),IDYA(1),Q(NM,ITJT),QR1(JT,MM),QR2(JT,MM),
     &QT1(IT,MM),QT2(IT,MM),QB1(IT,MM),QB2(IT,MM),QG(1),QQG(IM,JM),
     &YH(1),A4(1),A5(1),WMU(1),WETA(1),A3(1)
      DIMENSION ER(10)
      DIMENSION NXYZ01(3)
C
      EQUIVALENCE (IA(4),IGM),(IA(21),IQB),(IA(32),IGEOM),(IA(33),IQR),
     &(IA(34),IQT),(IA(48),NORM),(IA(56),IMJM),(IA(59),NMQ),
     &(IA(62),IGP),(IA(71),ISPANC),(IA(77),ITP),(A(61),LC)
C
      INTEGER G
      REAL NORM
C
CSASA REAL*8 ER,NXYZ01,XTEMP
      REAL*8           XTEMP
      CHARACTER*8 ER,NXYZ01
C
      DATA ER/'TOTAL ','INHOMO','GENEOU','S SOUR','CE .LE','. ZERO',
     &', CANN','OT BE ','NORMAL','IZED  '/
      DATA NXYZ01/'X MESH','  MESH','R MESH'/
C
C     COMPUTE COARSE MESH AND WHOLE SYSTEM SOURCE DATA
C
      CALL CLEARW(0.0,QQG,IMJM)
      DO 170 G=1,IGM
      CALL REED (0,IPQS+(G-1)*LTQS,Q,LTQS,1)
      DO 100 J=1,JT
      JA=(J-1)*IT
      DO 100 I=1,IT
      IB=IDX(I)
      IC=IDYA(J)
      T=Q(1,JA+I)*A5(I)*YH(J)
      QG(G)=QG(G)+T
  100 QQG(IB,IC)=QQG(IB,IC)+T
      IF (IQR.EQ.0) GO TO 120
      DO 110 J=1,JT
      JA=IDYA(J)
      DO 110 M=1,MM
      T=WMU(M)*YH(J)*(QR1(J,M)+QR2(J,M))*A4(ITP)
      QQG(IM,JA)=QQG(IM,JA)+T
  110 QG(G)=QG(G)+T
  120 IF (IQB.EQ.0) GO TO 140
      DO 130 I=1,IT
      JA=IDX(I)
      DO 130 M=1,MM
      T=WETA(M)*A3(I)*(QB1(I,M)+QB2(I,M))
      QQG(JA,1)=QQG(JA,1)+T
      QG(G)=QG(G)+T
  130 CONTINUE
  140 IF (IQT.EQ.0) GO TO 160
      DO 150 I=1,IT
      JA=IDX(I)
      DO 150 M=1,MM
      T=WETA(M)*A3(I)*(QT1(I,M)+QT2(I,M))
      QQG(JA,JM)=QQG(JA,JM)+T
  150 QG(G)=QG(G)+T
  160 QG(IGP)=QG(IGP)+QG(G)
  170 CONTINUE
      IF (NORM.EQ.0.) GO TO 240
      IF (QG(IGP).GT.0.0) GO TO 180
      CALL ERROR (4,ER,10)
      GO TO 240
C
C     NORMALIZE SOURCES
C
  180 T=NORM/QG(IGP)
      WRITE (NOUT,260)
      DO 230 G=1,IGM
      CALL REED (0,IPQS+(G-1)*LTQS,Q,LTQS,1)
      CALL MPLY (T,Q,LTQS)
      QG(G)=T*QG(G)
      IF (I5.NE.0) GO TO 190
      WRITE (NOUT,270)G
       XTEMP = DFLOAT(NMQ)
       CALL WWRITE(4,2,Q,NM,IT,JT,XTEMP,'      ','      ',
     &NXYZ01(IGEOM))
  190 IF (IQR.EQ.0) GO TO 200
      IF (I5.NE.0) GO TO 200
      WRITE (NOUT,250)G
      CALL WWRITE (2,2,QR1,JT,MM,1,'NORMAL','.RBY1 ','SOURCE','DIRECT')
      CALL WWRITE (2,2,QR2,JT,MM,1,'NORMAL',',RBY2 ','SOURCE','DIRECT')
  200 IF (IQB.EQ.0) GO TO 210
      IF (I5.NE.0) GO TO 210
      WRITE (NOUT,250)G
      CALL WWRITE (2,2,QB1,IT,MM,1,'NORMAL','BTBY1 ','SOURCE','DIRECT')
      CALL WWRITE (2,2,QB2,IT,MM,1,'NORMAL','BTBY2 ','SOURCE','DIRECT')
  210 IF (IQT.EQ.0) GO TO 220
      IF (I5.NE.0) GO TO 220
      WRITE (NOUT,250)G
      CALL WWRITE (2,2,QT1,IT,MM,1,'NORMAL',',TBY1 ','SOURCE','DIRECT')
      CALL WWRITE (2,2,QT2,IT,MM,1,'NORMAL',',TBY2 ','SOURCE','DIRECT')
  220 CONTINUE
      CALL RITE (0,IPQS+(G-1)*LTQS,Q,LTQS,1)
  230 CONTINUE
      QG(IGP)=NORM
      CALL MPLY (T,QQG,IM*JM)
  240 CONTINUE
      RETURN
C
C
  250 FORMAT (//' GROUP ',I3)
  260 FORMAT (1H0/////)
  270 FORMAT (1H0/' NORMALIZED SOURCE FOR GROUP ',I3)
      END
