C             INPT13              LEVEL=1        DATE=81.11.14
      SUBROUTINE INPT13
C
      COMMON /TW1C/ DD(1),LIM1,IA(210)
      COMMON /WORK/AAA(1),LIM2,AA(130)
      DIMENSION D(212),A(132)
      EQUIVALENCE (D(1),DD(1)),(AAA(1),A(1))
      EQUIVALENCE (A(52),LAST2),(D(155),LENCLR)
C
C     INPUT INTEGERS
C
      EQUIVALENCE (IA(4),IGM),(IA(11),IEVT),(IA(12),ISTART),
     &(IA(19),IQOPT)
C
C     COMPUTED INTEGERS
C
      EQUIVALENCE (IA(58),NM),(IA(59),NMQ),(IA(64),IT),(IA(65),JT),
     &(IA(66),ITJT)
C
C     FIRST WORD ADDRESSES
C
      EQUIVALENCE (A(61),LC),(A(67),LQ),(A(72),LBR1),(A(74),LBT1),
     &(A(76),LFL),(A(79),LXH)
C**************
C     EQUIVALENCE (A(107),LCHI),(A(109),LVEL)
C**************
C
C     INPUT FLUX GUESS FROM CARDS----IOP=-4/-3/-2/-1/1/2/3/4. IF IOP IS
C     NEGATIVE ONLY SCALAR COMPONENT DESIRED
C     FISSION GUESS OF UNITY---IOP=0.  NO INPUT REQUIRED
C
      INEG=0
      IF (ISTART) 110,120,100
  100 NC=NM
      GO TO 120
  110 NC=1
      INEG=1
      ISTART=-ISTART
CK120 IF (LAST2.LE.LIM2) CALL CLEARW(0.0,A(LC),LENCLR)
CKSK  CALL READQF ( A(LC),A(LFL),A(LXH),A(LBT1),A(LBR1),1,NM,ISTART,
CKSK &ITJT,IGM,IT,JT,NC,A(LQ),INEG )
  120 IF (LAST2.LE.LIM2) CALL CLEARW(0.0,AAA(LC),LENCLR)
      CALL READQF ( AAA(LC),AAA(LFL),AAA(LXH),AAA(LBT1),AAA(LBR1),
     &1,NM,ISTART,ITJT,IGM,IT,JT,NC,AAA(LQ),INEG )
C
C     READ SOURCES (IF ANY)
C
      IF (IEVT.GT.0) GO TO 130
CKSK  IF (LAST2.LE.LIM2) CALL CLEARW(0.0,A(LC),LENCLR)
CKSK  CALL READQF ( A(LC),A(LQ) ,A(LXH),A(LBT1),A(LBR1),0,NM,IQOPT ,ITJT
CKSK &,IGM,IT,JT,NMQ,A(LFL),INEG )
      IF (LAST2.LE.LIM2) CALL CLEARW(0.0,AAA(LC),LENCLR)
      CALL READQF ( AAA(LC),AAA(LQ) ,AAA(LXH),AAA(LBT1),AAA(LBR1),
     &0,NM,IQOPT,ITJT,IGM,IT,JT,NMQ,AAA(LFL),INEG )
  130 CONTINUE
C**************
C     CALL LOAD(6HFISSIO,6HN SPEC,A(LCHI),A(LCHI),IGM,1)
C     CALL LOAD(6HVELOCI,6HTIES  ,A(LVEL),A(LVEL),IGM,1)
C**************
      RETURN
      END
