      SUBROUTINE  IRAOUT(MTNAME,DELFIS,DELFNU,DELCAP,ENBND ,
     &                   SIGF1 ,SIGF2 ,SIGNU1,SIGNU2,SIGC1 ,
     &                   SIGC2 ,SIGT1 ,SIGT2 )
C
C     PRINT-OUT AND DISK-OUT OF EFFECTIVE MACRO. CROSS SECTION
C
      DOUBLE PRECISION  JNEFST,FNEFST,JNMACR,FNMACR
      CHARACTER*4       MTNAME,NAMEP
C
      COMMON  /IRACNL/ IOPT(20),JNEFST,FNEFST,JNMACR,FNMACR,NEF,IGT,
     &                 NMAT,KNMAX,MXMTX,MXTEMP,MXSIG0,LNMAX,IDS,NEF1,
     &                 MXREAC,NOUT1,NOUT2
C
      COMMON  /IRADAT/ ISTART,NEFR,NEFB,NIMTF,NISOM,TCOR,S,NRES,
     &                 NPSE,VOLF,VOLM,KKNMAX,NMP,MATD(50)
C
      DIMENSION  MTNAME(2),DELFIS(NEF),DELFNU(NEF),DELCAP(NEF),
     &           ENBND(NEF1),SIGF1(NEF),SIGF2(NEF),SIGNU1(NEF),
     &           SIGNU2(NEF),SIGC1(NEF),SIGC2(NEF),SIGT1(NEF),SIGT2(NEF)
C
      COMMON /IRAWRK/ IA(17000),NAMEP(2),LOCAM(11),LOCAF(6)
      DIMENSION   STORE(17000)
      COMMON /PDSPDS/BUFFER(540),IFLSW,NFILE(3),ECODE,TEMP
      EQUIVALENCE (IA(1),STORE(1))
C
C     UPDATE 'NAMEFXX2'
C
      CALL ICLEA(IA,17000,0)
C
      NAMEP(1) = MTNAME(1)
      NAMEP(2) = MTNAME(2)
      CALL SEARCH(NAMEP(1),LENG,ISW)
      IF(ISW.EQ.1)  RETURN
C
      CALL  READ(NAMEP(1),STORE,LENG)
C
      I1       = 0
      DO 100 I = 1,NEF
      LGV      = IA(I1+2)
C     WRITE(NOUT2,2001) I,LGV
C2001 FORMAT(1H ,' **I,LGV** ',2I10)
C     SIGC1 (I)= STORE(I1+3)
      SIGF1 (I)= STORE(I1+4)
      SIGNU1(I)= STORE(I1+5)
      SIGT1 (I)= STORE(I1+6)
      SIGC1(I) = STORE(I1+10)-STORE(I1+4)
      SIGC2 (I)= SIGC1 (I)
      SIGF2 (I)= SIGF1 (I)
      SIGNU2(I)= SIGNU1(I)
      SIGT2 (I)= SIGT1 (I)
      SAVEAB   = STORE(I1+10)
      IF(I.LT.ISTART)  GO TO 90
      SIGF2 (I)= SIGF2 (I)+DELFIS(I)
      SIGNU2(I)= SIGNU2(I)+DELFNU(I)
      SIGC2 (I)= SIGC2 (I)+DELCAP(I)
      SIGT2 (I)= SIGT2 (I)+DELCAP(I)+DELFIS(I)
      SAVEAB   = SAVEAB+DELFIS(I)+DELCAP(I)
   90 CONTINUE
C     STORE(I1+3)= SIGC2 (I)
      STORE(I1+4)= SIGF2 (I)
      STORE(I1+5)= SIGNU2(I)
      STORE(I1+6)= SIGT2 (I)
      SAVET      = SIGT2 (I)
      IF(SAVET.NE.0) SAVET=0.3333333/SAVET
      STORE(I1+8)= SAVET
      STORE(I1+9)= SAVET
      STORE(I1+10)=SAVEAB
      I1        = I1+10+LGV
  100 CONTINUE
C
      CALL  DELETE(NAMEP(1))
      CALL  WRITE(NAMEP(1),STORE,LENG)
C
      IF(IOPT(19).EQ.0) GO TO 201
C
      IPL=0
      WRITE(NOUT2,1000) MTNAME,IPL
      WRITE(NOUT2,1001)
      WRITE(NOUT2,1005)
      DO 200 I=ISTART,NEF
      WRITE(NOUT2,1002) I,ENBND(I),ENBND(I+1),SIGC1(I),SIGC2(I),SIGF1(I)
     &                   ,SIGF2(I),SIGNU1(I),SIGNU2(I),SIGT1(I),SIGT2(I)
  200 CONTINUE
      WRITE(NOUT2,1005)
C
C     UPDATE 'NAMEFXX4'
C
  201 CALL ICLEA(IA,17000,0)
C
      NAMEP(2) (4:4) = '4'
      CALL SEARCH(NAMEP(1),LENG,ISW)
      IF(ISW.EQ.1)  RETURN
C
      CALL  READ(NAMEP(1),STORE,LENG)
C
      I1        = 0
      DO 1100 I = 1,NEF
      LGV       = IA(I1+2)
      SIGF1 (I) = STORE(I1+4)
      SIGNU1(I) = STORE(I1+5)
      SIGT1 (I) = STORE(I1+6)
      SIGSP1    = SIGT1(I)    - 0.3333333/STORE(I1+8)
      SIGC1(I)  = STORE(I1+10)-STORE(I1+4)
      SIGC2 (I) = SIGC1 (I)
      SIGF2 (I) = SIGF1 (I)
      SIGNU2(I) = SIGNU1(I)
      SIGT2 (I) = SIGT1 (I)
      SAVEAB    = STORE(I1+10)
      IF(I.LT.ISTART)  GO TO 1090
      SIGF2 (I) = SIGF2 (I)+DELFIS(I)
      SIGNU2(I) = SIGNU2(I)+DELFNU(I)
      SIGC2 (I) = SIGC2 (I)+DELCAP(I)
      SIGT2 (I) = SIGT2 (I)+DELCAP(I)+DELFIS(I)
      SAVEAB    = SAVEAB   +DELFIS(I)+DELCAP(I)
 1090 CONTINUE
C     STORE(I1+3) = SIGC2 (I)
      STORE(I1+4) = SIGF2 (I)
      STORE(I1+5) = SIGNU2(I)
      STORE(I1+6) = SIGT2 (I)
      SAVET       = SIGT2 (I) - SIGSP1
      IF(SAVET.NE.0) SAVET=0.33333333/SAVET
      STORE(I1+8) = SAVET
      STORE(I1+9) = SAVET
      STORE(I1+10)= SAVEAB
      I1          = I1+10+LGV
 1100 CONTINUE
C
      CALL  DELETE(NAMEP(1))
      CALL  WRITE (NAMEP(1),STORE,LENG)
      RETURN
C
C
 1000 FORMAT(///1H ,30X,'MATERIAL NAME = ',2A4,'  (#',I1,
     &'--0/1:ISOTROPIC/ANISOTROPIC)','   IRA-ROUTINE '/)
 1001 FORMAT(1H ,30X,'EFFECTIVE MACROSCOPIC CROSS SECTION'//1H ,
     &'GRP.',T7,'E-UPPER',T19,'E-LOWER',T31,'CAPT.(NR)',T43,
     &'CAPT.(IR)',T55,'FISS.(NR)',T67,'FISS.(IR)',T79,
     &'NU*FIS(NR)',T92,'NU*FIS(IR)',T104,'TOTAL(NR)',T116,
     &'TOTAL(IR)')
 1002 FORMAT(1H ,I3,1P10E12.5)
 1005 FORMAT(1H ,1X,26('-----'))
C
      END
