C             TESTS               LEVEL=1        DATE=81.11.14
      SUBROUTINE TESTS ( FG,FISSA,FT,CHIA,IDX,IDYA,XH,YH,QQ,QQG,F,QG,
     &FLUX,BT1,BT2,BR1,BR2,BT3,BT4,IT,JT,IM,JM,NM,MM )
C
      COMMON /TW1C/ DD(1),LIM1,IA(210)
      COMMON /WORK/AAA(1),LIM2,AA(130)
      DIMENSION D(212),A(132)
      EQUIVALENCE (D(1),DD(1)),(AAA(1),A(1))
      EQUIVALENCE (D(112),IPFX),(D(128),I6),(D(113),LTFX)
C
      DIMENSION FG(1),FISSA(IT,JT),FT(IM,JM),CHIA(1),IDX(1),IDYA(1),
     &XH(1),YH(1),QQ(IM,JM),QQG(IM,JM),F(IM,JM),QG(1),FLUX(NM,IT,JT),
     &BT1(IT,MM),BT2(IT,MM),BR1(JT,MM),BR2(JT,MM),BT3(IT,MM),BT4(IT,MM)
C
      INTEGER G,OITNO
      REAL NORM
C
      EQUIVALENCE (IA(1),ITH),(IA(4),IGM),(IA(8),IBR),(IA(10),IBT),
     &(IA(11),IEVT),(IA(24),IANG),(IA(26),IITL),(IA(37),EV),
     &(IA(43),EPSO),(IA(46),EPSX),(IA(48),NORM),(IA(51),IUP),
     &(IA(56),IMJM),(IA(60),IP),(IA(61),JP),(IA(62),IGP),(IA(66),ITJT),
     &(IA(73),ISPANF),(A(76),LFL),(A(77),LFIS),(A(78),LFISA),
     &(A(88),LFUT),(A(89),LFDT),(A(90),LFRT),(A(91),LFLT),(A(92),LABT),
     &(A(93),LHA),(A(94),LGA),(A(108),LCHIA),(A(8),JCONV),(A(13),E2),
     &(A(14),E1),(A(18),NGO),(A(19),ALAR),(A(24),NGOTO),(A(25),E3),
     &(A(28),ALA),(A(30),FTP)
      EQUIVALENCE (A(21),TS),(A(32),OITNO),(A(49),IFLAG)
C
C
      IFLAG=0
      IF ((IEVT.EQ.0).AND.(OITNO.GT.2)) IFLAG=1
      E1=1.-ALA
      E2=ABS(E1)
C
C     PERFORM REBALANCE FOR FISSION OR UPSCATTERING
C
      XLA=ALA
      K=0
      T=FG(IGP)
      CALL CLEARW(1.0,F,IMJM)
CKSK  IF (IEVT.EQ.1) EV=A(LCHIA-1)/CHIA(IGP)
      IF (IEVT.EQ.1) EV=AAA(LCHIA-1)/CHIA(IGP)
C
C     ADD SOURCE (IF ANY) AND STORE IN QQ
C
  100 TS=0.0
      DO 110 J=1,JM
      DO 110 I=1,IM
      QQ(I,J)=FT(I,J)*F(I,J)
      IF (IEVT.EQ.0) QQ(I,J)=QQ(I,J)+QQG(I,J)
  110 TS=TS+QQ(I,J)
      IF (JCONV.EQ.0) GO TO 120
C
C     PRINT COARSE MESH BALANCE TABLES AND RETURN FOR FINAL PRINT
C
CKSK  IF (I6.EQ.0) CALL PCMBAL ( QQ,A(LFRT),A(LFLT),A(LFUT),A(LFDT),
CKSK &A(LABT),IM,JM,IP,JP,0 )
      IF (I6.EQ.0) CALL PCMBAL ( QQ,AAA(LFRT),AAA(LFLT),AAA(LFUT),
     &AAA(LFDT),AAA(LABT),IM,JM,IP,JP,0 )
      JCONV=0
      NGOTO=1
      RETURN
C
C     CALCULATE REBALANCE FACTORS
C
CK120 CALL REBAL ( F,A(LFUT),A(LFDT),A(LFLT),A(LFRT),A(LABT),QQ,A(LHA),
CKSK &A(LGA),IM,JM,IP,JP,IBT )
  120 CALL REBAL ( F,AAA(LFUT),AAA(LFDT),AAA(LFLT),AAA(LFRT),AAA(LABT),
     &QQ,AAA(LHA),AAA(LGA),IM,JM,IP,JP,IBT )
      IF (K.GT.0) GO TO 140
C
C     CHECK REBALANCE CONVERGENCE
C
      E3=0.0
      DO 130 J=1,JM
      DO 130 I=1,IM
  130 E3=AMAX1(E3,ABS(1.-F(I,J)))
C
C     IS ENTIRE PROBLEM CONVERGED
C
      IF ((E2.LT.EPSO).AND.(E3.LT.5.0*EPSX)) GO TO 360
C
C     CHECK FOR PURE SOURCE PROBLEM
C
      IF (FG(IGP).EQ.0.0) GO TO 230
      IF (IEVT.EQ.1) EV=1.0
      IF ((IEVT.NE.0).AND.(OITNO.GT.2)) GO TO 230
C
C     CALCULATE EIGENVALUE OR LAMBDA (COARSE MESH)
C
  140 TP=T
      T=0.
      DO 150 J=1,JM
      DO 150 I=1,IM
  150 T=T+F(I,J)*FT(I,J)
      XLAR=XLA
      XLA=(T+QG(IGP))/(TP+QG(IGP))
      K=K+1
      IF (IEVT-1) 200,160,180
C
C     K EFF COARSE MESH
C
  160 TA=1.0/XLA
      DO 170 J=1,JM
      DO 170 I=1,IM
  170 FT(I,J)=TA*FT(I,J)
      T=T*TA
      EV=EV*XLA
      IF (ABS(1.-XLA).GT.EPSX) GO TO 100
      GO TO 210
C
C     SEARCH COARSE MESH
C
  180 IF (NORM.EQ.0.0) GO TO 200
      TA=NORM/T
      DO 190 J=1,JM
      DO 190 I=1,IM
  190 F(I,J)=TA*F(I,J)
      T=TA*T
  200 IF (ABS(1.-XLA/XLAR).GT.EPSX) GO TO 100
C
C     APPLY REBALANCE FACTORS TO ALL FLUXES AND FISSIONS
C
  210 DO 220 J=1,JT
      JA=IDYA(J)
      DO 220 I=1,IT
      IB=IDX(I)
  220 FISSA(I,J)=F(IB,JA)*FISSA(I,J)
  230 DO 310 G=1,IGM
CKSK  CALL REED (0,IPFX+(G-1)*LTFX,A(LFL),LTFX,1)
      CALL REED (0,IPFX+(G-1)*LTFX,AAA(LFL),LTFX,1)
      DO 240 J=1,JT
      JA=IDYA(J)
      DO 240 I=1,IT
      IB=IDX(I)
      DO 240 N=1,NM
  240 FLUX(N,I,J)=F(IB,JA)*FLUX(N,I,J)
      IF (IBT.EQ.0) GO TO 260
      DO 250 I=1,IT
      IB=IDX(I)
      DO 250 M=1,MM
      BT1(I,M)=BT1(I,M)*F(IB,JM)
  250 BT2(I,M)=BT2(I,M)*F(IB,JM)
  260 IF (IBR.EQ.0) GO TO 280
      DO 270 J=1,JT
      JA=IDYA(J)
      DO 270 M=1,MM
      BR1(J,M)=BR1(J,M)*F(IM,JA)
  270 BR2(J,M)=BR2(J,M)*F(IM,JA)
  280 CONTINUE
      IF (IBT.NE.3) GO TO 300
      DO 290 I=1,IT
      IB=IDX(I)
      DO 290 M=1,MM
      BT3(I,M)=BT3(I,M)*F(IB,1)
  290 BT4(I,M)=BT4(I,M)*F(IB,1)
  300 CONTINUE
CKSK  CALL RITE (0,IPFX+(G-1)*LTFX,A(LFL),LTFX,1)
      CALL RITE (0,IPFX+(G-1)*LTFX,AAA(LFL),LTFX,1)
  310 CONTINUE
C
C     NOW, IF IEVT=0, RETURN FOR ANOTHER OUTER
C             IEVT=1, PERFORM KEFF REDUCTIONS
C             IEVT.GT.1, GO TO NEWPAR
C
      IF (IEVT.EQ.0) GO TO 370
      IF (IEVT.GT.1) GO TO 350
      T=1./EV
      DO 320 G=1,IGP
  320 CHIA(G)=T*CHIA(G)
      IF (ITH.EQ.0) GO TO 340
      DO 330 J=1,JT
      DO 330 I=1,IT
  330 FISSA(I,J)=T*FISSA(I,J)
CK340 EV=A(LCHIA-1)/CHIA(IGP)
  340 EV=AAA(LCHIA-1)/CHIA(IGP)
C
C     RETURN FOR ANOTHER OUTER ITERATION
C
      GO TO 370
C
C     EIGENVALUE SEARCH
C
  350 ALA=XLA
      E1=1.0-ALA
      E2=ABS(E1)
      CALL NEWPAR
C     EXIT 1 IS CONVERGED PROBLEM(NOT SET IN NEWPAR)
C     EXIT 2 IS ANOTHER OUTER ITERATION
C     EXIT 3 IS RETURN TO INITAL
      GO TO (360,370,380), NGO
  360 NGOTO=1
      JCONV=1+IANG
      IF (IANG.GT.0) RETURN
      IF (I6.NE.0) JCONV=0
      RETURN
  370 NGOTO=2
      RETURN
  380 NGOTO=3
      RETURN
      END
