C             TITLEP              LEVEL=1        DATE=81.02.23
      SUBROUTINE  TITLEP(WITHX,WITHY,XTITLE,YTITLE,TITLE)
      DIMENSION   XTITLE(1),  YTITLE(1), TITLE(1)
C     TITLE  PLOT
      CALL  SYMBOL (WITHX/4.,-14.5,4.,XTITLE,0.,40 )
      CALL  SYMBOL (-22.,WITHY/4.,5., YTITLE,90.,40 )
      CALL  SYMBOL (WITHX/4., WITHY+11., 5., TITLE,0.,40 )
      RETURN
      END
