C             TSOURW              LEVEL=1        DATE=81.11.14
C             TSOURC              LEVEL=6        DATE=
C     ELEMENT TSOURC
C
C     SUBPROGRAM TO PRODUCE THE SLOWING DOWN SOURCE TO THE THERMAL
C     RANGE
C
C
      SUBROUTINE TSOURW(NR,NRR,MAR,MATNM)
      COMMON /MAINC/ IOPT(36),JNMACR(2),FNMACR(2),DUM(8),JNFLUX(2)
     & ,FNFLUX(2),DUM1(2),NEF,NET,NERF,NERT,NMAT,DUM2(4),NOUT1,NOUT2
     & ,DUM3(6)
     &  ,NEF3,I73,NSOUC,NFIN,NFOUT,ITYPE,I78(23),CASENM(2),DUM5(398)
      COMMON /WORK/ FLUX(25000)
     & ,S(25000),VOLR(5000),IRR(5000)
      DIMENSION MAR(1),MAT(1),IA(1),II(1)
     &   ,MATNM(2,1),AA(7500),NODE(2)
      COMMON /PDSPDS/ BUF(540),IFLSW,FILENM(3),ECODE,TEMPRY
      COMMON /TW1C/ KKKK(500)
      EQUIVALENCE (KKKK(210),IZMESH),(KKKK(209),IVMESH),
     &            (KKKK(166),IFIXSR),(KKKK(164),ITFLUX),(I78(22),ICF)
      INTEGER CASENM
      CHARACTER*4 LETF,LETT,LETA,NUMB2,KZERO,ICF
      EQUIVALENCE (AA(1),II(1))
C
      DATA LETF/'   F'/,LETT/'   T'/,LETA/'   A'/,NUMB2/'   2'/,
     &     KZERO/'0000'/
C === CLEAR S:SOURCE TERM
CKH   REWIND NSOUC
CKH
      IJGT=NR*NET
      IF(IJGT.GT.25000) GO TO 600
CKH
      REWIND IZMESH
      REWIND IVMESH
      READ(IZMESH) (IRR(I),I=1,NR)
      READ(IVMESH) (VOLR(I),I=1,NR)
      REWIND IZMESH
      REWIND IVMESH
      REWIND ITFLUX
      REWIND IFIXSR
      DO 50 K=1,IJGT
      S(K)=0.
   50 CONTINUE
      IJG=NRR*NEF
CJ    READ(JNFLUX.FNFLUX.CASENM.'FAST')(FLUX(K),K=1,IJG)
      IFLSW=1
CCCCC FILENM(1)='FLUX'
      CALL BSHIFT(FILENM(1),'FLUX',0)
CCCCC FILENM(2)='    '
      CALL BSHIFT(FILENM(2),'    ',0)
CCCCC FILENM(3)='    '
      CALL BSHIFT(FILENM(3),'    ',0)
      NODE(1)=CASENM(1)
CCCCC NODE(2)='X00X'
      CALL BSHIFT(NODE(2),'X00X',0)
      CALL PACK (NODE(2),1,LETF)
      CALL PACK(NODE(2),4,NUMB2)
      CALL READ(NODE,FLUX,IJG)
      LTH=0
      MATNP=0
      IRP=0
      DO 500  I=1,NR
      IR=IRR(I)
      IF(IR.EQ.IRP) GO TO 450
      IRP=IR
      MATN=MAR(IR)
      IF(MATN.EQ.MATNP) GO TO 200
      MATNP=MATN
CJ    READ(JNMACR.FNMACR.NODE.'FAST')    LTH,(AA(K),K=1,LTH)
CCCCC FILENM(1)='MACR'
      CALL BSHIFT(FILENM(1),'MACR',0)
CCCCC FILENM(2)='O   '
      CALL BSHIFT(FILENM(2),'O   ',0)
CCCCC IF(ICF.NE.KZERO) FILENM(2)='OWRK'
      IF(ICF.NE.KZERO) CALL BSHIFT(FILENM(2),'OWRK',0)
      NODE(1)=MATNM(1,MATN)
      NODE(2)=MATNM(2,MATN)
      CALL PACK(NODE(2),1,LETF)
      CALL PACK(NODE(2),4,NUMB2)
      CALL GETLEN(NODE,LTH)
      CALL READ(NODE,AA,LTH)
  200 K=0
      DO 400 N=1,NEF
      IJG= NRR*(N-1)+IR
      NG1=N+1
      NG2=N+II(K+2)-1
      IF(NG2.LE.NEF) GO TO 350
      K1=NEF-NG1+3
      DO 300 L=K1,II(K+2)
      ND=L-K1+1
      IJGD= NR*(ND-1)+I
      S(IJGD)=S(IJGD)+FLUX(IJG)*AA(K+L+10)/VOLR(IR)
  300 CONTINUE
  350 K=K+10+II(K+2)
  400 CONTINUE
      GOTO 500
  450 DO 480 N=1,NET
      IJGD=NR*(N-1)+I
      S(IJGD)=S(IJGD-1)
  480 CONTINUE
  500 CONTINUE
C
CKH   WRITE(NSOUC) (S(K),K=1,IJGT)
      KKHH1=0
      KKHH2=0
      DO 520 N=1,NET
      KKHH1=KKHH2+1
      KKHH2=KKHH2+NR
      WRITE(IFIXSR) (S(I),I=KKHH1,KKHH2)
  520 CONTINUE
      REWIND IFIXSR
CKH      IF(ITYPE.EQ.0) GO TO 600
CCCCC FILENM(1)='MACR'
      CALL BSHIFT(FILENM(1),'MACR',0)
CCCCC FILENM(2)='O   '
      CALL BSHIFT(FILENM(2),'O   ',0)
CCCCC IF(ICF.NE.KZERO) FILENM(2)='OWRK'
      IF(ICF.NE.KZERO) CALL BSHIFT(FILENM(2),'OWRK',0)
CCCCC NODE(1)='CONT'
      CALL BSHIFT(NODE(1),'CONT',0)
CCCCC NODE(2)='T002'
      CALL BSHIFT(NODE(2),'T002',0)
      CALL READ(NODE,NGR,1)
      CALL READ(NODE,AA,NGR+1)
      ICO=0
CKH   DO 550 N=1,NGR
CKH   DO 550 I=1,NR
CKH   ICO=ICO+1
CKH   S(ICO)=AA(N+1)
CK550 CONTINUE
CKH   WRITE(NFIN) (S(I),I=1,ICO)
      DO 555 N=1,NET
      DO 550 I=1,NR
  550 S(I)=AA(N+1)
      WRITE(ITFLUX) (S(I),I=1,NR)
  555 CONTINUE
      REWIND ITFLUX
      RETURN
C 600 PRINT 601,IJGT
  600 WRITE(6,601) IJGT
      WRITE(NOUT2,601) IJGT
  601 FORMAT(' *** (SPATIAL MESH)*(NUMBER OF GROUP) EXCEED THE LIMIT',
     &'(25000) IN ''TSOURC''',I6)
      STOP
      END
