      SUBROUTINE UMCONT(ENERGY,MEMBER)
C
      CHARACTER*8     MEMBER
      CHARACTER*4     IDTMP
C
      COMMON /UMCPIN/ ITAPE,MATNO,NPE,NPF,NPC,IZA,ISWUN,AM,ELOW,EHI,
     +                RFTEMP,QVALE,QVALF,QVALC,EULOW,EUHIGH
      COMMON /UMCINT/ NPMAX,IFISS,IENDUN,IDPOS,ISWTMP,MF,MT,NP,IMAX,
     +                NSYSI,NSYSO,RQTEMP,NPRT,IPRINT
      COMMON /UMCTMP/ NTEMP,TMPSET(40),IDTMP(40)
      COMMON /PCOWK3/ IWORK(500)
      COMMON /UMC001/ LIBTYP,NEF,ISTART,NG,NOMESH,KFGP,NGMAX,MAXINT,NSET
      COMMON /UMC005/ SIG1D(3,46)
C
      REAL*4           WORK(500)
      REAL*4           ENERGY(NP)
C
      EQUIVALENCE    (WORK(1),IWORK(1))
C
      IENDUN    = 0
CDEL  WRITE(NSYSO,*) ' *** ISWUN EULOW EUHIGH  ** ',ISWUN,EULOW,EUHIGH
      IF(ISWUN.EQ.1) THEN
                     DO 110 I = 1 , NP-1
                     IF(ENERGY(I).GT.EULOW.AND.ENERGY(I+1).LE.EULOW)
     +               IENDUN   = I
  110                CONTINUE
                     ENDIF
C
CDEL  WRITE(NSYSO,*) ' *** NP IENDUN  ** ',NP,IENDUN
C
      IWORK( 1) =   ITAPE
      IWORK( 2) =   MATNO
      IWORK( 3) =   IZA
      IWORK( 4) =   IFISS
      IWORK( 5) =   IENDUN
       WORK( 6) =   RQTEMP
CKSK  CALL DATE(IWORK(7))
      CALL UDATE(IWORK(7))
      LENG      =    8
C
      MEMBER (1:1) = 'C'
      MEMBER (5:8) = '000' // IDTMP(IDPOS)  (1:1)
C
CDEL  WRITE(NSYSO,101) MEMBER
CDEL  WRITE(NSYSO,102) (IWORK(I),I=1,5)
CDEL  WRITE(NSYSO,104)   WORK(6)
CDEL  WRITE(NSYSO,105) (IWORK(I),I=7,8)
C
CDEL  IF(ISWUN.GT.0) THEN
CDEL            WRITE(NSYSO,106) IENDUN,ENERGY(IENDUN),ENERGY(IENDUN+1)
CDEL                 ENDIF
C
  101 FORMAT(/1H ,10X,' << MEMBER(',A8,') DUMP LISTING >> '/)
  102 FORMAT(1H ,' ## WORK ## ',10I8)
  104 FORMAT(1H ,' ## WORK ## ',10F8.2)
  105 FORMAT(1H ,' ## WORK ## ',10A4)
  106 FORMAT(1H ,' ## IENDUN E1 E2 ## ',I6,1P2E12.5)
C
      IRC  = 0
      CALL SEARCH( MEMBER , LEN   , IRC )
      IF(IRC.EQ.0) CALL DELETE( MEMBER  )
      CALL WRITE( MEMBER  , IWORK , LENG )
C
      IF(IENDUN.LE.0) GO TO 301
C
      MEMBER (1:1) = 'I'
      IRC  = 0
      CALL SEARCH( MEMBER , LEN   , IRC )
      IF(IRC.EQ.0) CALL DELETE( MEMBER  )
      LENG = NG*3
      CALL WRITE( MEMBER  , SIG1D , LENG )
C
  301 CONTINUE
CM    ICNT = 0
CM    CALL EXCPNO('MCROSS  ',ICNT)
CM    WRITE(NSYSO,FMT='(15H I/O (MCROSS) =,I8)') ICNT
CM    ICNT = 0
CM    CALL EXCPNO('UMCROSS ',ICNT)
CM    WRITE(NSYSO,FMT='(15H I/O (UMCROSS)=,I8)') ICNT
C
      RETURN
      END
