      SUBROUTINE UCLCKM(ICPU)
C     for SX3(Monte-4)
C     CLOCKM IS ORIGINALLY A FACOM BUILTIN SERVICE ROUTINE TO RETURN
C     CURRENT CPU TIME(MILI-SEC) IN 4-BYTE INTEGER.
C     ICPU(OUTPUT)  : CURRENT USED CPU TIME (MILI-SEC) IN 4-BYTE INTEGER
C
C     THIS ROUTINE IS REPLACED BY A CLOCK(D) WHICH IS A SX BUILTIN
C     SERVICE ROUTINE.
C
C     D : 8-BYTE REAL (SEC)
C
      REAL*8    TCPU
      INTEGER*4 ICPU
      CALL CLOCK(TCPU)
      TCPU = TCPU*1.0D3
      ICPU = IDINT(TCPU)
      RETURN
      END
