C             AUXTWT              LEVEL=18       DATE=83.11.16
      SUBROUTINE AUXTWT(KXM,KYM,KZORIG,R,Z,KZRDUC,KZRNUM,VOLMA,VOLZON)
      COMMON /MAINC/ KKKK(200)
      COMMON /PDSPDS/ BUF(540),IFLSW,FILENM(3),ECODE,TEMPRY
      COMMON /TW1C/ IA(500)
      COMMON /WORK/ PPPP(30000),AREA(5000),KZBM(5000),VOLBM(5000)
      DIMENSION KXM(1),KYM(1),KZORIG(1),KZRNUM(1),KZRDUC(1),VOLZON(1),
     &          VOLMA(1),R(1),Z(1)
      EQUIVALENCE (IA(7),IM),(IA(8),JM),(IA(15),MT),(IA(34),IGEOM),
     &            (IA(58),IMJM),(IA(68),ITJT),(IA(66),IT),
     &            (IA(210),IZMESH),(IA(170),NMPW),(IA(209),IVMESH),
     &            (IA(27),IMC),(IA(29),JMC),(IA(4),ISCT)
      EQUIVALENCE (KKKK(98),IRANG),(KKKK(99),ICF),(KKKK(101),ICASE),
     &            (KKKK(2),IOPT2),(KKKK(12),IOPT12),(KKKK(65),NOUT2)
CCCCC DIMENSION ICASE(2),NODE(2),LETR(3)
      CHARACTER*4 ICASE(2),NODE(2),LETR(3),FILENM
C
C
C  ASSIGNE ZONE NUMBER TO EACH MESH
C
      REWIND IZMESH
      REWIND IVMESH
      NMESH=0
      DO 30 J=1,JM
      JMESH=KYM(J)
      DO 30 JJ=1,JMESH
      DO 20 I=1,IM
      IMESH=KXM(I)
      DO 20 II=1,IMESH
      NMESH=NMESH+1
      KZBM(NMESH)=(J-1)*IM+I
   20 CONTINUE
   30 CONTINUE
C
      IF(ITJT.EQ.NMESH) GO TO 40
   35 WRITE(6,600) ITJT,NMESH
      WRITE(NOUT2,600) ITJT,NMESH
  600 FORMAT(' ERROR IN SUBROUTINE AUXTWT',5X,'ITJT=',I6,5X,'NMESH=',I6)
      STOP
C
   40 WRITE(IZMESH) (KZBM(I),I=1,ITJT)
      REWIND IZMESH
      WRITE(6,635) IZMESH
      WRITE(NOUT2,635) IZMESH
  635 FORMAT(' ZONE ID BY MESH WAS WRITTEN ON FILE',I3)
CKH   WRITE(6,605) (KZBM(I),I=1,ITJT)
CK605 FORMAT(' ZONE NUMBER BY MESH'/(30I4))
C
C  REARRANGE MATERIAL NUMBER SPECIFICATION
C
      IMJMC = IMC*JMC
      NMPW  = 1
      KZRNUM(1)=ISIGN(1,KZORIG(1))
      KZRDUC(1)=IABS(KZORIG(1))
      IF(IMJMC.EQ.1) GO TO 61
      DO 60 I=2,IMJMC
      MATNO=KZORIG(I)
      I1=I-1
      DO 50 J=1,I1
      IF(IABS(MATNO).NE.IABS(KZORIG(J))) GO TO 50
      KZRNUM(I)=ISIGN(KZRNUM(J),MATNO)
      GO TO 60
   50 CONTINUE
      NMPW=NMPW+1
      KZRDUC(NMPW)=IABS(MATNO)
      KZRNUM(I)=ISIGN(NMPW*(ISCT+1)-ISCT,KZORIG(I))
   60 CONTINUE
   61 CONTINUE
      DO 65 I=1,NMPW
      MAX    =0
      DO 63 J=1,IMJMC
      IMAT   = I*(ISCT+1)-ISCT
      IF (IMAT.NE.IABS(KZRNUM(J))) GO TO 63
      IF (KZRNUM(J).LT.0) MAX = 1
   63 CONTINUE
      IF (MAX.EQ.1) KZRDUC(I) = -KZRDUC(I)
   65 CONTINUE
      WRITE(6,613) NMPW
      IF(NMPW.LE.MT) GO TO 66
      WRITE(6,612) NMPW,MT
      STOP
   66 CONTINUE
      WRITE(6,614) (KZORIG(I),I=1,IMJM)
      WRITE(6,615) (KZRNUM(I),I=1,IMJM)
      WRITE(6,616) (KZRDUC(I),I=1,NMPW)
      WRITE(NOUT2,613) NMPW
      WRITE(NOUT2,614) (KZORIG(I),I=1,IMJM)
      WRITE(NOUT2,615) (KZRNUM(I),I=1,IMJM)
      WRITE(NOUT2,616) (KZRDUC(I),I=1,NMPW)
  612 FORMAT(1X,'ILLEGAL NUMBER OF MATERIALS ',I3,' TO MT',I3)
  613 FORMAT(1X,'NUMBER OF MATERIALS         =',I3)
  614 FORMAT(1X,'MAT.NO BY ZONE (MAT SPEC II.8)'/10X,30I4)
  615 FORMAT(1X,'MAT.REGION BY ZONE (IN SEQ TWTRN INPT FILE)'/10X,30I4)
  616 FORMAT(1X,'MAT. NO. BY MAT.REGION'/10X,30I4)
C
C  VOLUMES FOR EACH MATERIAL AND FOR EACH ZONE
C
   70 CALL CLEARW(0.0,VOLMA,MT)
      C=1.0
      NN=1
C     IF(IGEOM.EQ.2) C=6.2831853
      IF(IGEOM.NE.1) C=6.2831853
      DO 80 J=1,JM
      JJ=(J-1)*IM
      DO 80 I=1,IM
C     N=IABS(KZRNUM(JJ+I))
      N=IABS(KZRNUM(JJ+I))
      N=(N+ISCT)/(ISCT+1)
      TEMP=(R(I+1)-R(I))*(Z(J+1)-Z(J))
      IF(IGEOM.EQ.1) GO TO 75
      TEMP=C*((R(I)+R(I+1))/2.0)*TEMP
   75 VOLZON(NN)=TEMP
      NN=NN+1
   80 VOLMA(N)=VOLMA(N)+TEMP
      WRITE(6,620) (VOLMA(I),I=1,NMPW)
      WRITE(NOUT2,620) (VOLMA(I),I=1,NMPW)
  620 FORMAT(1X,'VOLUME FOR EACH MATERIAL'/(1X,10E13.5))
      WRITE(6,625) (VOLZON(I),I=1,IMJM)
      WRITE(NOUT2,625) (VOLZON(I),I=1,IMJM)
  625 FORMAT(1X,'VOLUME FOR EACH ZONE'/(1X,10E13.5))
C
C ===== WRITE ON PDS FILE ----- FLUX(CASE.AVOL) =====
C
      IFLSW=1
      FILENM(1)='FLUX'
      FILENM(2)='    '
      FILENM(3)='    '
      NODE(1)=ICASE(1)
      IF(IOPT2.EQ.3) GO TO 90
      IF(IOPT12.NE.3) STOP 1575
      NODE(2)='AVOL'
      CALL OVRWRT(NODE,VOLZON,IMJM)
      GO TO 95
   90 NODE(2)='FVOL'
      CALL OVRWRT(NODE,VOLZON,IMJM)
      NODE(2)='TVOL'
      CALL OVRWRT(NODE,VOLZON,IMJM)
C
C   VOLUMES FOR EACH MESH
C
   95 NN=1
      DO 110 I=1,IM
      NNR=KXM(I)
      DELR=(R(I+1)-R(I))/FLOAT(NNR)
      RR=R(I)
      RB=R(I)
      DO 110 II=1,NNR
      RL=RR
      RR=RB+DELR*FLOAT(II)
      TEMP=DELR
      IF(IGEOM.EQ.1) GO TO 100
      TEMP=C*((RL+RR)/2.0)*TEMP
  100 AREA(NN)=TEMP
      NN=NN+1
  110 CONTINUE
C
      NN=1
      DO 120 J=1,JM
      NNZ=KYM(J)
      DELZ=(Z(J+1)-Z(J))/FLOAT(NNZ)
      DO 120 JJ=1,NNZ
      DO 120 I=1,IT
      VOLBM(NN)=AREA(I)*DELZ
      NN=NN+1
  120 CONTINUE
      NMESH=NN-1
      IF(NMESH.NE.ITJT) GO TO 35
      WRITE(IVMESH) (VOLBM(I),I=1,ITJT)
      REWIND IVMESH
CKH   WRITE(6,630) (VOLBM(I),I=1,ITJT)
CK630 FORMAT(1X,'VOLUME BY MESH'/(1X,10E13.5))
C
C  CHANGE EACH OTHER KZORIG(I) AND KZRNUM(I)
C
      DO 130 I=1,IMJMC
      JJJ=KZORIG(I)
      KZORIG(I)=KZRNUM(I)
      KZRNUM(I)=JJJ
  130 CONTINUE
      RETURN
      END
