C             GRID21              LEVEL=1        DATE=81.11.14
      SUBROUTINE GRID21
C
      COMMON /TW1C/ DD(1),LIM1,IA(210)
      COMMON /WORK/AAA(1),LIM2,AA(130)
      DIMENSION D(212),A(132)
      EQUIVALENCE (D(1),DD(1)),(AAA(1),A(1))
      EQUIVALENCE (D(152),JFISC),(D(151),NEXTER)
C
C     FOR CALL TO INITAL
C
      EQUIVALENCE (IA(13),MT),(IA(18),IHM),(IA(57),MM),(IA(58),NM),
     &(IA(64),IT),(IA(65),JT),(IA(66),ITJT),(D(171),LIHX),(D(172),LIHY),
     &(A(61),LC),(A( 62),LA1),(A( 63),LA2),(A( 64),LA3),(A( 65),LA4),
     &(A( 66),LA5),(D(173),LXDF),(D(174),LYDF),(A( 76),LFL),
     &(A( 78),LFISA),(D(181),LDC),(D(182),LXR),(D(183),LYR),
     &(D(184),LDX),(D(185),LDY),(D(186),LDYA),(A( 79),LXH),
     &(A( 80),LYH),(D(187),LW),(D(188),LCM),(D(189),LCE),(D(190),LWM),
     &(A( 81),LWE),(D(191),LP1),(D(192),LP2),(D(193),LP3),(D(194),LP4),
     &(D(195),LMN),(D(196),LMC),(D(197),LMD),(A( 95),LQG),(A( 96),LFG),
     &(A(107),LCHI)
CKH  9(A(107),LCHI),(D(205),LV)
      EQUIVALENCE (A(108),LCHIA),(A(109),LVEL),(D(200),LYM),
     &(D(201),LXM),(D(202),LXRA),(D(203),LYRA),(A(112),LAA),
     &(A(113),LB1),(A(114),LAL1),(A(115),LAL2),(A(119),LCTOT)
C
C     FOR CALL TO FISCAL
C
      EQUIVALENCE (IA(5),IM),(IA(6),JM),(A(85),LAB)
      IF (JFISC.EQ.2) GO TO 100
C
C     CALCULATE INITIALLY REQUIRED FUNCTIONS
C
CKSK  CALL INITAL ( A(LC),D(LW),D(LCM),D(LCE),D(LWM),A(LWE),D(LP1),
CKSK &D(LP2),D(LP3),D(LP4),A(LCHI),A(LCHIA),A(LVEL),D(LMN),D(LMC),
CKSK &D(LMD),D(LXR),D(LYR),D(LDX),D(LDY),D(LDYA),A(LXH),A(LYH),D(LXRA),
CKSK &D(LYRA),A(LA1),A(LA2),A(LA3),A(LA4),A(LA5),A(LFISA),D(LXM),D(LYM),
CKSK &D(LIHX),D(LIHY),A(LQG),A(LFL),D(LDC),A(LFG),A(LAA),A(LAL1),
CKSK &A(LAL2),A(LB1),A(LCTOT),D(LXDF),D(LYDF),IHM,MT,NM,MM,ITJT,IT,JT )
      CALL INITAL ( AAA(LC),DD(LW),DD(LCM),DD(LCE),DD(LWM),AAA(LWE),
     &DD(LP1),DD(LP2),DD(LP3),DD(LP4),AAA(LCHI),AAA(LCHIA),AAA(LVEL),
     &DD(LMN),DD(LMC),DD(LMD),DD(LXR),DD(LYR),DD(LDX),DD(LDY),DD(LDYA),
     &AAA(LXH),AAA(LYH),DD(LXRA),DD(LYRA),AAA(LA1),AAA(LA2),AAA(LA3),
     &AAA(LA4),AAA(LA5),AAA(LFISA),DD(LXM),DD(LYM),DD(LIHX),DD(LIHY),
     &AAA(LQG),AAA(LFL),DD(LDC),
     &AAA(LFG),AAA(LAA),AAA(LAL1),AAA(LAL2),AAA(LB1),AAA(LCTOT),
     &DD(LXDF),DD(LYDF),IHM,MT,NM,MM,ITJT,IT,JT )
C
C     CALCULATE VOLUMES
C
CKH   CALL VOLUMT(A(LV),A(LYH),A(LA5),IT,JT)
      IF (NEXTER.NE.0) GO TO 110
C
C     CALCULATE FISSION SOURCE
C
CK100 CALL FISCAL ( A(LC),A(LFG),A(LFISA),D(LDX),D(LDYA),A(LA5),A(LYH),
CKSK &D(LDC),D(LDY),A(LQG),A(LCHIA),IHM,MT,IT,JT,A(LAB),IM,JM,D(LXDF),
CKSK &D(LYDF) )
  100 CALL FISCAL ( AAA(LC),AAA(LFG),AAA(LFISA),DD(LDX),DD(LDYA),
     &AAA(LA5),AAA(LYH),DD(LDC),DD(LDY),AAA(LQG),AAA(LCHIA),
     &IHM,MT,IT,JT,AAA(LAB),IM,JM,DD(LXDF),DD(LYDF) )
  110 CONTINUE
      RETURN
      END
