C             GUTS                LEVEL=8        DATE=80.10.14
      SUBROUTINE GUTS(XN,VE,MA,MZ,CRX,DF,IGT,CA,CT,CS,V,TAB,XND,XJ,XNN,
     & XNA,SG,B,IH1,IGM1,I1,IMJ1,FG,QG)
C    *** GUTS CONTROLS THE ITERATION LINK WHEREIN LIES THE GUTS OF ANISN
      DIMENSION XN(I1,1),VE(1),MA(1),MZ(1),CRX(IH1,IGM1,1),DF(1),IGT(1),
     & CA(1),CT(1),CS(1),V(1),TAB(1),XND(1),XJ(IMJ1,1),XNN(1),XNA(1),
     & SG(1),B(1),FG(1),QG(1)
      COMMON /SN1C/
     &              D(1),LIM1,LR,LW,LDSN,LMA,LMZ,LMB,LMC,LXMD,LFIX,LFLT,
     &       LJ5,LRM,LDF,LJ3,LJ4,LIGT,LART,LALFT,
     &LFGP,LFGG,LEND,LV,LAA,LWD,LMR,LPNC,
     &ID,ITH,ISCT,ISN,IGE,IBL,IBR,IZM,IM,IEVT,IGM,IHT,IHS,IHM,MS,MCR,MTP
     &,MT,IDFM,IPVT,IQM,IPM,IPP,IIM,ID1,ID2,ID3,ID4,ICM,IDAT1,IDAT2,IFG,
     &IFLU,IFN,IPRT,IXTR,
     &EV,EVM,EPS,BF,DY,DZ,DFM1,XNF,PV,RYF,XLAL,XLAH,EQL,XNPM,
     &T(3),LCMAC,T1(8),NIN,NOU,NT1,NT2,NT3,NT4,NT5,NT6,NT7
      COMMON /WORK/ Z(1),LIM2,LXKI,LFD,LXN,LVE,LMTT,LCRX,LQ,LPA,
     &       LXJ,LCH,LCA,LCF,LCT,LCS,LTAB,
     &LXND,LSA,LSAT,LRAV,LRA,LXNN,LXNE,LXNR,LXNA,LSR,LST,LQG,LFG,LSG,
     &LXKE,LXNI,LXNO,LT3,LT5,LDA,LDB,LDC,LDS,LB,IGMP,IGMM,IIGG,NERR,IMJT
     &,IHG,IMP,MP,NDS,NUS,SDG,SCG,AG,XNLGG,XNLG,SNG,ALA,ASR,EAM,EPG,EQ,
     &E1,E2,E3,E4,E5,E6,E7,E8,E9,E10,E11,E12,E13,E14,E15,E16,E17,E18,E19
     &,E20,ESC,ESM,EVP,EVPP,FTP,IC,ICVT,IGP,IG,IHP,IIC,IIG,IP,IZP,I01,
     &I02,I03,I04,I05,I06,I07,I08,I09,I00,JT,LC,MG,MI,ML,MM,NFN,XITR,
     &XLAP,XLAPP,XLAR,XLA,XNIO,XNII,ZZ1,ZZ2,ZZ3,XNB,XKEP,XKIP,IH,I,K,L,
     &M,J,N,NN,ISV
C
C
      COMMON /DEPLET/ AKEFF (50)
      COMMON  /MAINC/ IOPT(100)
C
      EQUIVALENCE  ( IBURN , IOPT(20) )
      EQUIVALENCE  ( ITYPE , IOPT(77) )
      EQUIVALENCE  ( I79   , IOPT(79) )
C
C *** START OF PROCESS
C
      DO 25 I=1,IGM
   25 SG(I)=1.0
C   *** MIX CROSS SECTIONS
  807 IF(IC.EQ.0 .OR. IEVT.EQ.3)CALL S807(CRX,Z(LQ),D(LMB),D(LMC),
     & D(LXMD),IHP,IGMM)
C   *** COMPUTE GEOMETRIC FUNCTIONS
  810 IF(IC.EQ.0 .OR. IEVT.GE.4)CALL S810(D(LR),Z(LRA),MA,D(LRM),
     & D(LAA),Z(LRAV),Z(LDA),Z(LDB),Z(LDC),Z(LDS),D(LDSN),D(LW),D(LWD),
     & IP,V)
CKSK  CALL CLOCK(NT5)
      CALL UCLOCK(NT5)
      NFN=1
      ITRIG=0
C   *** COMPUTE AND NORMALIZE FISSION SOURCE
  821 CALL S821(Z(LFD),Z(LFG),Z(LQG),Z(LXKE),XN,B,XJ,IM,IMJT,IGMM,MM,
     & CRX,IHP,V,MA,MZ,DF,SG,VE)
      IF(ITRIG.NE.0)GO TO 851
C   *** PRINT ITERATION MONITOR
      IF(IC.EQ.0)WRITE (NOU,10)
   10 FORMAT('1 OUTER INNER ',6X,'NEUT BAL',4X,'UPSCATTER RATIO ',3X,
     &'EIGENVALUE',8X,'LAMBDA1',9X,'LAMBDA2')
   12 WRITE(NOU,20) IC,LC,XNB,E15,EV,XLA,ALA
      IF(IC.EQ.ICM-1)ICVT=1
      IF(IC.EQ.ICM)GO TO 13
      E1=0.0
C   *** COMPUTE  ALPHA/V ABSORPTION
      IF(IEVT.EQ.2)E1=EV
      IF(IPVT.EQ.2)E1=E1+PV
      DO 1 I=1,IGM
      IF(VE(I).EQ.0.0)VE(I)=1.0
    1 TAB(I)=E1/VE(I)
C     ZERO
      SNG=0.0
      AG=0.0
      SDG=0.0
      SCG=0.0
      XNLG=0.0
      E13=0.0
      E14=0.0
      E15=0.0
      IIG=1
      IIGG=1
      IGMP=1
   11 IF(IDAT1.EQ.0)IIGG=IIG
      IF(IDAT1.NE.2)IGMP=IIG
      IIC=0
      ZZ1=0.0
C   *** COMPUTE SCATTERING SOURCE
  824 CALL S824(Z(LSR),Z(LQ),D(LMA),D(LCMAC),D(LV),Z(LFD),Z(LCRX),
     & Z(LXKE),
     & Z(LSA),Z(LXN),Z(LXNI),Z(LXJ),Z(LB),Z(LXNN),Z(LCS),Z(LXNA),Z(LCH),
     & IHP,IM,JT,MM,IGMM,MP,IMP,MT,Z(LCT),Z(LCA),D(LDF),Z(LTAB),D(LJ5),
     & Z(LSG))
      IF(IDAT1.NE.2 .OR. IIG.EQ.IGM)GO TO 27
      IF(NDS.LT.IIG)GO TO 26
      REWIND NT1
      GO TO 27
   26 N=NDS-1
      IF(ISCT.NE.0)N=N+N
      DO 28 I=1,N
   28 BACKSPACE NT1
   27 IF(IPM.GT.0)ZZ1=ZZ1 + QG(IIG)
      IF(IFN+IC .EQ. 0)GO TO 2
      IF(IDAT2.LE.IC)GO TO 3
      IF(IGT(IIG).NE.2)GO TO 33
      CALL CELL(Z(LCT),Z(LCS),Z(LXNN),Z(LB),Z(LXND),Z(LXNA),MM)
      GO TO 841
   33 IF(IGT(IIG).EQ.0)GO TO 3
C   *** SIMPLIFIED S-2 SOLUTION  -  DIFFUSION THEORY
    2 CALL DT(Z(LPA),Z(LSR),D(LAA),Z(LST),Z(LCT),Z(LCS),Z(LSAT),Z(LCH),
     & Z(LXNE),Z(LXND),D(LART),D(LALFT),Z(LXNA),Z(LXNR),MM,IMP,IP,
     & Z(LXNN),D(LWD),Z(LSA))
      GO TO 841
C   *** COMPLICATED S-N, P-L SOLUTION  -  TRANSPORT THEORY
    3 CALL S833(Z(LXN),Z(LXNN),Z(LST),Z(LSR),Z(LCS),D(LMA),D(LJ5),
     & D(LAA),Z(LSAT),Z(LSA),Z(LCH),Z(LXNA),Z(LXNR),D(LPNC),D(LDSN),
     & D(LW),Z(LXNI),Z(LXNO),Z(LB),Z(LDA),Z(LDB),Z(LDC),Z(LDS),D(LV),
     & Z(LXNE),Z(LPA),D(LWD),Z(LCT),Z(LSG),Z(LXND),IM,MM,IP,IMP,D(LMR),
     & D(LART),D(LALFT))
  841 E1=0.0
      E2=0.0
      E3=0.0
      IF(ISCT.EQ.0)GO TO 19
C   *** SAVE CURRENTS (XJ)  AND FLUXES (XN)
      DO 21 I=1,IMJT
   21 XJ(I,IGMP)=XNA(I)
   19 DO 4 I=1,IM
      E4=V(I)
      IF(IDFM.GT.0)E4=E4*DF(I)
      XN(I,IGMP)=XNN(I)
      K=MA(I)
      K=IABS(MZ(K))
C   *** COMPUTE TOTAL UPSCATTER FOR GROUP IIG DUE TO NEW FLUX  E14
      IF(NUS.NE.0)E14=E14 + CRX(IHP,IIGG,K)*XNN(I)*E4
    5 E1=E1 + CT(I)*XNN(I)
      E2=E2 + CS(I)*XNN(I)
    4 E3=E3 + CA(I)*XNN(I)
C   *** COMPUTE ABSORPTIONS (AG), SCATTER LOSSES (SDG), SCATTER GAINS +
C       FIXED SOURCE + FISSION SOURCE (SNG), LEAKAGE (XNLG) FOR NEUTRON
C       BALANCE CALCULATION
   34 AG=AG + E3
      SCG=SCG + E2
      SDG=SDG + E1 - E3 - E2
      XNLG=XNLG + XNLGG
      SNG=SNG + ZZ1
   20 FORMAT(I7,I6,1P5E16.7)
C   *** WRITE ANGULAR FLUX FOR BALANCE TABLES
    7 IF(ICVT.EQ.1) WRITE(NT4)(XND(I),I=1,MI)
      IF(IDAT1.NE.2 .OR. IIG.NE.IGM)GO TO 14
      WRITE (NT1) (XNN(I),I=1,IM),(B(M),M=1,MM)
      IF(ISCT.NE.0)WRITE(NT1) (XNA(I),I=1,IMJT)
      REWIND NT1
   14 IIG=IIG + 1
      IF(IIG.LE.IGM)GO TO 11
      IF(ICVT.NE.1)GO TO 17
      REWIND NT4
      WRITE(NOU,30) NT4
   30 FORMAT('+', T96,'ANG. FLX ON',I3)
   17 IC= IC + 1
      XLAR=XLA
C   *** COMPUTE UPSCATTER SCALE FACTOR BY GROUP  SG(IIG)
      E2=FG(IGP) + QG(IGP)
      IF(E13.EQ.0.0)GO TO 32
      E15=E14/E13
      E1=E2/(E2 + E13 - E14)
      IF(E1.LE.0.0 .OR. E1.GT.10.0)E1=10.0
      DO 31 I=1,IGM
   31 SG(I)=E1
   32 E1=SDG
      IF(IGM.EQ.1)E1=SCG
      E1=E1/E2
C   *** ALA=LAMBDA2     XNB=NEUTRON BALANCE
      IF(ASR.EQ.0.0)GO TO 35
      ALA=E1/ASR
   35 ASR=E1
      XNB=SNG/(AG+SDG+XNLG)
      ITRIG=1
      GO TO 821
  851 CALL S851
      IF(I09-2)12,13,807
CM 13 RETURN
   13 CONTINUE
      IF(IBURN.GT.0.AND.ITYPE.EQ.0) THEN
                                    AKEFF(I79+1) = EV
CMOD                                AKINF(I79+1) = EV
                                    ENDIF
      RETURN
      END
