CC
CCCCCCCCCCC  SUBROUTINES FOR CHARACTER HANDLING  --- BY M.SASAKI (JAIS)
      SUBROUTINE NTEM0(A,II,N)
C ------- SET N'TH CHARACTER OF II TO ' '.
      CHARACTER*4 A,II
      A = II
      A(N:N) = ' '
      RETURN
      END
