      SUBROUTINE PCOPIJ(PIJ   ,QQ    ,DANX  ,DANY  ,SIGWW ,BL    ,
     +                  SIG   ,RATD  ,SIGMA ,DAN   ,NCOR  ,MAR   )
C
CDEL  PARAMETER   (MAXMAT=100)
      INCLUDE  'MATDTINC'
C
      COMMON /PCOWK5/ IBURN,KEEPIJ,IPCNT,NXRB,KCOREK(MAXMAT)
      COMMON /PCOWK2/ KCOMP,KCOMPF,DELBEF,KSREG,KMAT,KNMAX,KRES,NPROB,
     1                NDOUBL,NOUT1,NOUT2,NBB,NBH,MAXN,MAXP,KDAN,
     3                KPIJ1,KPIJ2,ESCAPA,ESCAPF,GUZAI,IPLOT,MAIN(2)
C
      COMMON /MAINC / NNOPT(500)
C
      EQUIVALENCE  (LINTOT,NNOPT(95))
C
      DIMENSION   PIJ(KSREG,KSREG),QQ(KPIJ1,MAXN,MAXP),DANX(MAXN,KDAN),
     1            DANY(MAXN,KDAN),SIG(KCOMP),SIGWW(KPIJ2,KCOMP),
     2            BL(KCOMP),SIGMA(KCOMP),RATD(KCOMP),
     3            DAN(MAXP),NCOR(KCOMP),MAR(KSREG)
C
      REAL*8      XL(11)
      CHARACTER*8 MEMBER
C
      DATA XL/     1.0000000D-5,0.1111111,0.2500000,0.4285714,0.6666667,
     +1.0000000   ,1.5000000,2.3333333,4.0000000,9.0000000,1.000000D+5 /
C
C     START OF PROCESS
C
      DO 50 J=1,KCOMP
   50 SIGMA(J)=SIG(J)
C
      DO 150 M = 1,11
      DO 140 N = 1,MAXN
      DO 110 I = 1,KCOMPF
      NHK      = M
      IF(I.EQ.2) NHK=N
      L        = MAIN(I)
      TMP      = XL(NHK)/BL(L)
      DO 100 J = 1,KCOMP
CKSK  IF(NCOR(J).EQ.I) SIG(J)=SIGMA(J)+RATD(J)*(TMP-SIGMA(L))
      IF(NCOR(J).EQ.I) THEN
        SAVE = SIGMA(J)+RATD(J)*(TMP-SIGMA(L))
        IF(SAVE.LT.1.00E-5) THEN
          SIG(J) = SIGMA(J) + RATD(J)*TMP
        ELSE
          SIG(J) = SAVE
        ENDIF
      ENDIF
CKSK 1998/3/24
  100 CONTINUE
  110 CONTINUE
      III     = M+11*(N-1)
      DO 120 I= 1,KCOMP
  120 SIGWW(III,I)=SIG(I)
  140 CONTINUE
  150 CONTINUE
C
      IF(IBURN .LE.2) GO TO 155
      IF(IPCNT .LE.1) GO TO 155
      IF(KEEPIJ.LE.1) GO TO 155
C
      ISW = MOD(IBURN-1,KEEPIJ)
      WRITE(6,*) ' **  IBURN ISW KEEPIJ : ',IBURN,ISW,KEEPIJ
      IF(ISW.NE.1) THEN
CKSK               MEMBER = 8HPEACOPIJ
                   MEMBER = 'PEACOPIJ'
            CALL   BURNRW ( MEMBER , QQ  , KPIJ1 , MAXN , MAXP ,
     &                      KPIJ1 , MAXN , MAXP  , 'READ')
                   RETURN
                   ENDIF
C
  155 CONTINUE
C
      REWIND LINTOT
      DO 160 JZ = 1,KCOMP
      WRITE(LINTOT) (SIGWW(IZ,JZ),IZ=1,KPIJ2)
  160 CONTINUE
      REWIND LINTOT
C
      IPOPT=4
      CALL PIJ2(KPIJ2,IPOPT)
      LIN  = 21
C
  170 CONTINUE
C
      REWIND LIN
      DO 200 N=1,MAXN
      DO 190 M=1,11
      READ(LIN) ((PIJ(I,J),I=1,KSREG),J=1,KSREG)
      DO 180  I = 1,KSREG
      DO 180  J = 1,I
      IJ        = (I*(I-1))/2+J
  180 QQ(M,N,IJ)= PIJ(I,J)
  190 CONTINUE
  200 CONTINUE
      REWIND LIN
C
      IF(IBURN.GT.0.AND.KEEPIJ.GT.1) THEN
CKSK                  MEMBER = 8HPEACOPIJ
                      MEMBER = 'PEACOPIJ'
               CALL   BURNRW ( MEMBER , QQ  , KPIJ1 , MAXN , MAXP ,
     &                         KPIJ1  , MAXN , MAXP , 'OVER' )
                      ENDIF
C
C     END OF PROCESS
C
      RETURN
CM
CM    DO 16 I=1,KSREG
CM    IM=MAR(I)
CM    IM=NCOR(IM)
CM    DO 16 J=1,I
CM    IJ=(I*(I-1))/2+J
CM    IF(IM.GT.KCOMPF.OR.IM.LE.0) GO TO 17
CM    IF(IM.EQ.2) GO TO 18
CM    DAN(IJ)=(QQ(11,MAXN,IJ)-QQ(10,MAXN,IJ))*9.
CM    GO TO 16
CM 18 DAN(IJ)=(QQ(11,11,IJ)-QQ(11,10,IJ))*9.
CM    GO TO 16
CM 17 DAN(IJ)=0.
CM 16 CONTINUE
CM    IF(MAXN.EQ.1) GO TO 20
CM    DO 21 N=1,10
CM    DO 22 I=1,KSREG
CM    IM=MAR(I)
CM    IM=NCOR(IM)
CM    DO 22 J=1,I
CM    IJ=(I*(I-1))/2+J
CM    IF(IM.NE.1) GO TO 23
CM    DANX(N,IJ)=(QQ(11,N,IJ)-QQ(10,N,IJ))*9.
CM    GO TO 24
CM 23 DANX(N,IJ)=0.
CM 24 IF(IM.NE.2) GO TO 25
CM    DANY(N,IJ)=(QQ(N,11,IJ)-QQ(N,10,IJ))*9.
CM    GO TO 22
CM 25 DANY(N,IJ)=0.
CM 22 CONTINUE
CM 21 CONTINUE
CM
CM    DO 220 N=1,MAXP
CM    WRITE(NOUT1,991) N
CM    WRITE(NOUT1,992) ((QQ(I,J,N),J=1,MAXN),I=1,KPIJ1)
CM    WRITE(NOUT1,993) (DANX(I,N),I=1,MAXN)
CM    WRITE(NOUT1,994) (DANY(I,N),I=1,MAXN)
CM    WRITE(NOUT1,995) DAN(N)
CM220 CONTINUE
CM
CM991 FORMAT(/1H ,10X,' *** CHECK WRITE FROM PCOPIJ ***(CASE=',I3,')'/)
CM992 FORMAT(1H ,' **QQ** ',1P11E11.4)
CM993 FORMAT(1H ,' *DANX* ',1P11E11.4)
CM994 FORMAT(1H ,' *DANY* ',1P11E11.4)
CM995 FORMAT(1H ,' *DAN** ',1P11E11.4)
CM
C
      END
