C             TWTRN1              LEVEL=6        DATE=85.06.06
      SUBROUTINE TWTRN1
      COMMON /TW1C/ DD(1),LIM1,IAA(4000)
      COMMON /MAINC/ KKK(100)
      DIMENSION D(4002)
      EQUIVALENCE (D(1),DD(1))
      EQUIVALENCE (IAA(12),ISTART),(D(156),NINP),(D(157),NOUT),(D(142),N
     &RROR),
     &  (D(171),LIHX),(D(172),LIHY),(D(181),LDC),(D(182),LXR),
     &  (D(183),LYR),(D(205),LZRDUC),(D(206),LZRNUM),(D(207),LVOLMA)
     & ,(D(208),LVOLZO)
      EQUIVALENCE (D(158),NAFLUX),(D(159),NDUMP1),(D(160),NDUMP2),
     &            (D(161),NEXTRA),(D(162),NEDIT),(D(163),LAFLUX),
     &            (D(164),ITFLUX),(D(165),ISNCON),(D(166),IFIXSR),
     &            (D(167),ISOTXS),(D(209),IVMESH),(D(210),IZMESH)
      EQUIVALENCE (KKK(74),NSOUC),(KKK(75),NFIN),(KKK(65),NOUT2)
C     LIM1=3998 /* TRANSFERRED TO MAIN */
CMOD  NINP=5
      NINP=KKK(62)
      NOUT=NOUT2
C
C  ASSIGN SCRATCH, ANGULAR FLUX, AND EDIT UNITS
C
      NEXTRA=4
      NAFLUX=8
      NEDIT=1
C
C  ASSIGN STANDARD INTERFACE TOTAL FLUX, ANGULAR FLUX, SN CONSTANTS,
C  SOURCE, AND CROSS SECTION FILE UNITS
C
      ITFLUX=NFIN
      LAFLUX=9
      ISNCON=11
      IFIXSR=NSOUC
      ISOTXS=10
C
C  ASSIGN PRIMARY AND SECONDARY RESTART DUMP UNITS
C
      NDUMP1=12
      NDUMP2=13
C
C  ASSIGN TEMPORARY UNITS TO SAVE VOLUME BY MESHES, AND ZONE ID BY MESHE
C
      IVMESH=14
      IZMESH=2
C
C
      NERROR=0
      CALL REED (NEDIT,0,0,0,4)
      CALL RITE (NEDIT,0,0,0,4)
      CALL SN1TR
      IF (IABS(ISTART).EQ.6) GO TO 100
      CALL INPT14
  100 CONTINUE
      CALL INPT15
CKSK  CALL AUXTWT(D(LIHX),D(LIHY),D(LDC),D(LXR),D(LYR),
CKSK &            D(LZRDUC),D(LZRNUM),D(LVOLMA),D(LVOLZO))
      CALL AUXTWT(DD(LIHX),DD(LIHY),DD(LDC),DD(LXR),DD(LYR),
     &            DD(LZRDUC),DD(LZRNUM),DD(LVOLMA),DD(LVOLZO))
      RETURN
      END
