CMEDT --162    ***FUEL MANAGEMENT** CORE ALLOCATION AND START/ CF-CALR
C
      SUBROUTINE MEDT(A,MEMORY)
C
      WRITE(6,6000) 'MEDT'
 6000 FORMAT(10X,'**** ERROR THIS SUBROUTINE IS OMITTED ** ',A4)
      STOP
      END
