C     THIS ROUTINE IS USED ONLY IN SRAC-CITATION AND NOT USED IN COREBN
C
      SUBROUTINE CTFLUX(P2,RVOL,PVOL,NRGN,IVX,JVX,LVX,JIVX,KVX,S,
     &                  P2E,NRGNE,KBVX,IGEOM )
C
      CHARACTER*4  NUMB
      CHARACTER*4  IRANGE,FILENM,IDENT,IDCASE,ICF
C
      COMMON /PDSPDS/ BUF(540),IFLSW,FILENM(3),ECODE,TEMPRY
      COMMON /MAINC/  III(1000)
      COMMON /TMPSET/ STND(35),NUMB(61),NTDUMY
C
      EQUIVALENCE (III(101),IDCASE),(III(98),IRANG),(III(99),ICF)
C
      REAL*8    P2(JVX,IVX,KVX)
      DIMENSION RVOL(LVX),PVOL(LVX),IRANGE(3)
      DIMENSION NRGN(JVX,IVX),S(LVX,KVX),IDENT(2)
C
      DIMENSION P2E(JIVX,KBVX,KVX),NRGNE(JVX,IVX,KBVX)
C
      DATA IRANGE/'FAST','THEM','ALL '/
C
C
C
      CALL CLEA ( S , LVX*KVX , 0.0 )
C
      IF(IGEOM.LE.10) THEN
      DO 100 K = 1,KVX
      DO 100 I = 1,IVX
      DO 100 J = 1,JVX
      IRZ      = NRGN(J,I)
CM    S(IRZ,K) = S(IRZ,K) + P2(J,I,K)*PVOL(IRZ)
      IF(IRZ.GT.0) S(IRZ,K) = S(IRZ,K) + P2(J,I,K)*PVOL(IRZ)
CKSK FOR UNIX
      IF(S(IRZ,K).GT.1.0E30) THEN 
        WRITE(6,*) ' CAUTION(CTFLUX):SKIPP TO WRITE FLUX*VOL IN',
     &             ' PDS TO AVOID FLOATING OVERFLOW(>1.0E30)'
        RETURN
      ENDIF
  100 CONTINUE
                      ELSE
C
      DO 160 K = 1,KVX
      DO 160 KB= 1,KBVX
      N2       = 0
      DO 150 I = 1,IVX
      DO 150 J = 1,JVX
      N2       = N2 + 1
      IRZ      = NRGNE(J,I,KB)
      IF(IRZ.GT.0) S(IRZ,K) = S(IRZ,K) + P2E(N2,KB,K)*PVOL(IRZ)
CKSK FOR UNIX
      IF(S(IRZ,K).GT.1.0E30) THEN 
        WRITE(6,*) ' CAUTION(CTFLUX):SKIPP TO WRITE FLUX*VOL IN',
     &             ' PDS TO AVOID FLOATING OVERFLOW(>1.0E30)'
        RETURN
      ENDIF
  150 CONTINUE
  160 CONTINUE
                      ENDIF
C
      IFLSW    = 1
      FILENM(1)= 'FLUX'
      FILENM(2)= '    '
      FILENM(3)= '    '
      IDENT(1) = IDCASE
      IDENT(2) = 'XVOL'
CM    CALL PACKX(IDENT(2),1,IRANGE(IRANG+1),1)
      IDENT(2) (1:1) =  IRANGE(IRANG+1) (1:1)
C
      CALL SEARCH(IDENT,LGT,ISW)
      IF(ISW.EQ.0) CALL DELETE(IDENT)
      CALL WRITE(IDENT,RVOL,LVX)
C
      IDENT(2) ='X00X'
CM    CALL PACKX(IDENT(2),1,IRANGE(IRANG+1),1)
      IDENT(2) (1:1) =  IRANGE(IRANG+1) (1:1)
CM    CALL PACK(IDENT(2),4,ICF)
      IDENT(2) (4:4) =  ICF (4:4)
      IF(III(79).GT.0) IDENT(2) (2:2)  =  NUMB(III(79)) (4:4)
C
      CALL SEARCH(IDENT,IGT,ISW)
      IF(ISW.EQ.0) CALL DELETE(IDENT)
      CALL WRITE(IDENT,S,LVX*KVX)
C
      RETURN
      END
