CYELD --044 ***CITATION*** READS INPUT SECTION 034/ CF-IPTM
C
      SUBROUTINE YELD(HOX,NJJR,MJJR,NFO,NNFO,NVX,NSETVX)
C
      WRITE(6,6000) 'YELD'
 6000 FORMAT(10X,'**** ERROR THIS SUBROUTINE IS OMITTED ** ',A4)
      STOP
      END
