C     ELEMENT BUFFER
C
C     READ WRITE  THE PATH VECTOR ON FNN WITH FIXED LENGTH USING THE
C     BUFFER
C
C  ENTRY  OPNBUF  INITIATE THE BUFFER NN FOR READ/WRITE
C  ENTRY  WRTBUF  STORE THE VECTOR ON BUFFER AND WRITE TO FNN IF FILLED
C  ENTRY  CLSBUF  WRITE TO FNN THE REMAINING  VECTOR
C  ENTRY  RDBUF   TRANSFER THE VECTOR AND READ FROM FNN IF EMPTY
C
C
C ARGUMENT  LGV  LENGTH OF THE PATH
C ARGUMENT  L0   INTEGER PARAMETER
C ARGUMENT  W    FLOATING POINT NUMBER PARAMETERS (3 WORDS).
C ARGUMENT  X(I) THE CUTS OF THE PATH  I=1,LGV
C ARGUMENT  J(I) THE REGION NUMBERS    I=1,LGV
C ARGUMENT  NN   FILE UNIT NUMBER  81,82,83
C
C INTERNAL VARIABLES
C           LBUF MAXIMUM RECORD SIZE FOR BUFFER
C           NBUF(NN) ACTUAL RECORD SIZE OF THE BUFFER NN
C           LGVA     ACTUAL LENGTH OF THE PATH(= 5 + 2*LGV)
C           ABUF     BUFFER
C           IBUF     EQUIVALENT BUFFER FOR INTEGERS
C
      SUBROUTINE OPNBUF(NN)
C
CMOD  PARAMETER    ( MXNTAB = 2000 )
      INCLUDE  'PIJPMINC'
C
      PARAMETER    ( LBUF   = 2 * ( MXNTAB + 40 )   )
C
CM    DIMENSION ABUF(1020,4),IBUF(1020,4),X(1),J(1),NBUF(4),W(3)
      DIMENSION NCOUNT(4)
CM    DIMENSION WORKIO(1020)
      DIMENSION ABUF(LBUF,4),IBUF(LBUF,4),X(1),J(1),NBUF(4),W(3)
      DIMENSION WORKIO(LBUF)
C
      EQUIVALENCE (ABUF(1,1),IBUF(1,1))
C
CM    DATA LBUF/1020/
CADD
      COMMON /BANK/ MAXL0(4),MAXLL(4),LBANK
CEND
C
C *** OPEN BUFFER
C
      NN1        = NN + 80
      IF (NN1.LT.81 .OR. NN1.GT.84) GOTO 20
      NCOUNT(NN) = 0
      NBUF(NN)   = 0
      IBUF(1,NN) = 0
      REWIND NN1
   10 RETURN
C
   20 WRITE(6,30) NN1
      STOP
C
   30 FORMAT(10X,'*** FILE UNIT ASSIGNMENT ERROR ',I5,'***')
C
C *** WRITE BUFFER
C
      ENTRY WRTBUF(LGV,L0,W,X,J,NN)
      NN1   = NN + 80
CADD
      MAXL0(NN)=MAX(L0,MAXL0(NN))
      MAXLL(NN)=MAX(LGV,MAXLL(NN))
      LGVA  = 5  + 2*LGV
CEND
      IF(LGVA.GT.LBUF) GO TO 110
C
      IF (NBUF(NN)+LGVA .GE. LBUF) GO TO 100
   40 IBUF(NBUF(NN)+1,NN) = LGV
      IBUF(NBUF(NN)+2,NN) = L0
      ABUF(NBUF(NN)+3,NN) = W(1)
      ABUF(NBUF(NN)+4,NN) = W(2)
      ABUF(NBUF(NN)+5,NN) = W(3)
      NBUF(NN)            = NBUF(NN) + 5
C
      LOC1    = NBUF(NN)
      LOC2    = NBUF(NN) + LGV
*VOCL LOOP,NOVREC
      DO 50 L = 1,LGV
CM    IBUF(NBUF(NN)+L    ,NN)   = J(L)
CM    ABUF(NBUF(NN)+LGV+L,NN)   = X(L)
      IBUF(LOC1    + L   ,NN)   = J(L)
      ABUF(LOC2    + L   ,NN)   = X(L)
   50 CONTINUE
      NBUF(NN) = NBUF(NN) + 2*LGV
      RETURN
C
  100 IF( NN1.LT.81 .OR. NN1.GT.84) GOTO 20
      IBUF(NBUF(NN)+1,NN) = 0
CMOD  WRITE(NN1) (ABUF(L,NN),L=1,LBUF)
      DO 105  I = 1 , LBUF
      WORKIO(I) = ABUF(I,NN)
  105 CONTINUE
      WRITE(NN1)  WORKIO
CEND
      NCOUNT(NN) = NCOUNT(NN)+1
      NBUF(NN)   = 0
      GO TO 40
C
  110 WRITE(6,*)' *** LRECL OVER IN PATH BUFFER, EXTEND BUFFER SIZE FOR
     * ',LGVA,',  PRESENT BSIZE=',LBUF
      STOP
C
C *** CLOSE BUFFER
C
      ENTRY CLSBUF(NN)
      NN1        = NN + 80
CMOD  WRITE(NN1) (ABUF(L,NN),L=1,LBUF)
      DO 115  I = 1 , LBUF
      WORKIO(I) = ABUF(I,NN)
  115 CONTINUE
      WRITE(NN1)  WORKIO
CEND
      NBUF(NN)   = 0
      NCOUNT(NN) = NCOUNT(NN)+1
      WRITE(6,130) NCOUNT(NN),LBUF,NN1
      END FILE NN1
      REWIND NN1
      RETURN
C
  130 FORMAT(10X,'***',I5,' LOGICAL RECORDS OF THE SIZE ',I5,
     *   ' WRITTEN ON THE FILE UNIT F',I2,' ***')
C
C *** READ BUFFER
C
      ENTRY RDBUF(LGV,L0,W,X,J,NN)
      NN1  = NN + 80
  140 LGV  = IBUF(NBUF(NN)+1,NN)
      IF(LGV.EQ.0) GO TO 200
      L0   = IBUF(NBUF(NN)+2,NN)
      W(1) = ABUF(NBUF(NN)+3,NN)
      W(2) = ABUF(NBUF(NN)+4,NN)
      W(3) = ABUF(NBUF(NN)+5,NN)
      NBUF(NN) = NBUF(NN)+5
C
      LOC1     = NBUF(NN)
      LOC2     = NBUF(NN) + LGV
      DO 150 L = 1,LGV
CM    J(L)     = IBUF(NBUF(NN)+L    ,NN)
CM    X(L)     = ABUF(NBUF(NN)+LGV+L,NN)
      J(L)     = IBUF( LOC1   + L   ,NN)
      X(L)     = ABUF( LOC2   + L   ,NN)
  150 CONTINUE
      NBUF(NN) = NBUF(NN) + 2*LGV
  160 RETURN
C
CM200 READ(NN1,END=160) (ABUF(L,NN),L=1,LBUF)
  200 READ(NN1,END=160)  WORKIO
      DO 210   I = 1 , LBUF
      ABUF(I,NN) = WORKIO(I)
  210 CONTINUE
      NBUF(NN) = 0
      GO TO 140
C
      END
