C     GET DIRECTORY NAME(PDSDIR) OF PDS DEFINED IN SHELL-SCRIPT 
      SUBROUTINE GETDIR(PREFIX,PDSDIR,LENG)
      COMMON  /UNITIO/ NIN1, NOUT1
      CHARACTER*120    PDSDIR
      CHARACTER*30     PREFIX
C
C-----------------------------------------------------------------------
      CALL UGTENV(PREFIX,PDSDIR)
      LENG = INDEX(PDSDIR," ") - 1
C     WRITE(NOUT1,*) PDSDIR(1:LENG)
      IF (LENG.GT.120) THEN
        WRITE(NOUT1,6000) PDSDIR
        STOP 999
      ENDIF
      IF (LENG.LE.0) THEN
        WRITE(NOUT1,6100) PDSDIR
        STOP 999
      ENDIF
 6000 FORMAT(//1H ,'<<<  ERROR STOP (GETDIR)  >>>',/,1X,
     &'PDS FILE ACCESS ERROR, DIRECTORY NAME IS TOO LONG > 120',/1X,
     &'NAME=',A)
 6100 FORMAT(//1H ,'<<<  ERROR STOP (GETDIR)  >>>',/,1X,
     &'PDS FILE ACCESS ERROR, DIRECTORY NAME MAY BE EMPTY')
      RETURN
      END
