C
CMSASA ... ROUTINE TO COPY 1 WORD CHARACTERS ONTO INTEGER.
C       MAYBE ENDIAN-FREE, I HOPE.
C
      SUBROUTINE  CNVC2I( ICH, IBCDA )
      INTEGER  ICH, IBCDA
      ICH = IBCDA
      RETURN
      END
