      SUBROUTINE UEXCP(LIMIT,NOW)
C
C     EXCP IS FACOM BUILTIN SERVICE ROUTINE TO COUNT I/O TIMES.
C     LIMIT(OUTPUT) : MAXIMUM I/O COUNT ALLOWED IN THE SYSTEM
C     NOW(OUTPUT)   : CURRENT I/O COUNT
C
C     IF THERE IS NO RESTRICTION IN YOUR SYSTEM, SET LIKE BELOW.
        LIMIT = 10000
        NOW   = 0
        RETURN
C
C     CALL EXCP(LIMIT,NOW)
C     RETURN
      END
