C             CONTRL              LEVEL=4        DATE=81.03.18
      SUBROUTINE CONTRL
     &   (NMAT,IMX,MTNAME,NGR,NFFL )
C   *** CONTROL CALLS EACH OF THREE LINKS
      COMMON /SN1C/
     &              D(1),LIM1,LR,LW,LDSN,LMA,LMZ,LMB,LMC,LXMD,LFIX,LFLT,
     &       LJ5,LRM,LDF,LJ3,LJ4,LIGT,LART,LALFT,
     &LFGP,LFGG,LEND,LV,LAA,LWD,LMR,LPNC,
     &ID,ITH,ISCT,ISN,IGE,IBL,IBR,IZM,IM,IEVT,IGM,IHT,IHS,IHM,MS,MCR,MTP
     &,MT,IDFM,IPVT,IQM,IPM,IPP,IIM,ID1,ID2,ID3,ID4,ICM,IDAT1,IDAT2,IFG,
     &IFLU,IFN,IPRT,IXTR,
     &EV,EVM,EPS,BF,DY,DZ,DFM1,XNF,PV,RYF,XLAL,XLAH,EQL,XNPM,
     &T(3),LCMAC,T1(8),NIN,NOU,NT1,NT2,NT3,NT4,NT5,NT6,NT7,NT8
      COMMON  /WORK/ Z(1),LIM2,LXKI,LFD,LXN,LVE,LMTT,LCRX,LQ,LPA,
     &       LXJ,LCH,LCA,LCF,LCT,LCS,LTAB,
     &LXND,LSA,LSAT,LRAV,LRA,LXNN,LXNE,LXNR,LXNA,LSR,LST,LQG,LFG,LSG,
     &LXKE,LXNI,LXNO,LT3,LT5,LDA,LDB,LDC,LDS,LB,IGMP,IGMM,IIGG,NERR,IMJT
     &,IHG,IMP,MP,NDS,NUS,SDG,SCG,AG,XNLGG,XNLG,SNG,ALA,ASR,EAM,EPG,EQ,
     &E1,E2,E3,E4,E5,E6,E7,E8,E9,E10,E11,E12,E13,E14,E15,E16,E17,E18,E19
     &,E20,ESC,ESM,EVP,EVPP,FTP,IC,ICVT,IGP,IG,IHP,IIC,IIG,IP,IZP,I01,
     &I02,I03,I04,I05,I06,I07,I08,I09,I00,JT,LC,MG,MI,ML,MM,NFN,XITR,
     &XLAP,XLAPP,XLAR,XLA,XNIO,XNII,ZZ1,ZZ2,ZZ3,XNB,XKEP,XKIP,IH,I,K,L,
     &M,J,N,NN,ISV
      COMMON /MAINC/ DUMMY(1000)
      EQUIVALENCE (DUMMY(64),NOUT1),(DUMMY(65),NOUT2)
      DIMENSION MTNAME(2,NMAT),IMX(1)
      INTEGER ZZ2
CKSK  CALL ITIME(NT5)
      CALL IATIME(NT5)
      NT1=1
      NT2=2
      NT3=3
      NT4=4
      NT6=10
      NT7=10
      NIN=5
      NOU=NOUT2
      NT8=8
C   *** NT1 AND NT2 ARE USED TO STORE FLUX AND CURRENT WHEN IDAT1=2
C   *** NT3 AND NT4  ARE USED TO STORE X-SEC AND SOURCE WHEN IDAT1.NE.0
C   *** NT6 IS LIBRARY TAPE
C   *** NT7 IS FOR SPECIALLY PREPARED GRP. IND. X-SEC.
C   *** NT8 IS WEIGHTED CROSS SECTIONS TAPE
C   *** NIN AND NOU  ARE STANDARD INPUT-OUTPUT TAPES
      REWIND NT4
      CALL PLSNT
     &   (NMAT,IMX,MTNAME,NGR  )
      CALL GUTS(Z(LXN),Z(LVE),D(LMA),D(LCMAC),Z(LCRX),D(LDF),D(LIGT),
     & Z(LCA),Z(LCT),Z(LCS),D(LV),Z(LTAB),Z(LXND),Z(LXJ),Z(LXNN),
     & Z(LXNA),Z(LSG),Z(LB),IHP,IGMM,IM,IMJT,Z(LFG),Z(LQG))
      CALL FINPR1(NFFL)
CKSK  CALL CLOCK(NT5)
      CALL UCLOCK(NT5)
C     READ(NIN,10) E1
   10 FORMAT(A4)
C     IF(NT1.NE.NT2) GO TO 2
C   *** CLEVER TEST ALWAYS GOES TO 2 - PREVENTS NASTY WARNING
      RETURN
      END
