C             FINPR1              LEVEL=5        DATE=81.03.18
      SUBROUTINE FINPR1(NFFL)
C   *** FINPR1 CONTAINS LENGTHY CALL STATEMENTS WHICH SAVES STORAGE IN
C       LINK 0
      COMMON /SN1C/
     &              D(1),LIM1,LR,LW,LDSN,LMA,LMZ,LMB,LMC,LXMD,LFIX,LFLT,
     &       LJ5,LRM,LDF,LJ3,LJ4,LIGT,LART,LALFT,
     &LFGP,LFGG,LEND,LV,LAA,LWD,LMR,LPNC,
     &ID,ITH,ISCT,ISN,IGE,IBL,IBR,IZM,IM,IEVT,IGM,IHT,IHS,IHM,MS,MCR,MTP
     &,MT,IDFM,IPVT,IQM,IPM,IPP,IIM,ID1,ID2,ID3,ID4,ICM,IDAT1,IDAT2,IFG,
     &IFLU,IFN,IPRT,IXTR,
     &EV,EVM,EPS,BF,DY,DZ,DFM1,XNF,PV,RYF,XLAL,XLAH,EQL,XNPM,
     &T(3),LCMAC,T1(8),NIN,NOU,NT1,NT2,NT3,NT4,NT5,NT6,NT7,NT8
      COMMON /WORK/ Z(1),LIM2,LXKI,LFD,LXN,LVE,LMTT,LCRX,LQ,LPA,
     &       LXJ,LCH,LCA,LCF,LCT,LCS,LTAB,
     &LXND,LSA,LSAT,LRAV,LRA,LXNN,LXNE,LXNR,LXNA,LSR,LST,LQG,LFG,LSG,
     &LXKE,LXNI,LXNO,LT3,LT5,LDA,LDB,LDC,LDS,LB,IGMP,IGMM,IIGG,NERR,IMJT
     &,IHG,IMP,MP,NDS,NUS,SDG,SCG,AG,XNLGG,XNLG,SNG,ALA,ASR,EAM,EPG,EQ,
     &E1,E2,E3,E4,E5,E6,E7,E8,E9,E10,E11,E12,E13,E14,E15,E16,E17,E18,E19
     &,E20,ESC,ESM,EVP,EVPP,FTP,IC,ICVT,IGP,IG,IHP,IIC,IIG,IP,IZP,I01,
     &I02,I03,I04,I05,I06,I07,I08,I09,I00,JT,LC,MG,MI,ML,MM,NFN,XITR,
     &XLAP,XLAPP,XLAR,XLA,XNIO,XNII,ZZ1,ZZ2,ZZ3,ICON,IHTF,IHSF,IHMF,IPUN
     &,IGMF,IHST,IHMT,J,N,NN,ISV
      DIMENSION LD(1)
      EQUIVALENCE (D(1),LD(1))
      EQUIVALENCE  (ICON,XCON)
C   *** PRINT FINAL MONITOR
C     WRITE (NOU,20) IC,LC,ICON,E15,EV,XLA,ALA
      WRITE (NOU,20) IC,LC,XCON,E15,EV,XLA,ALA
   20 FORMAT(I7,I6,1P5E16.7,'  FINAL MONITOR')
      IF(IC.EQ.ICM)WRITE (NOU,30)
   30 FORMAT('0 ****** OUTER ITERATION LIMIT REACHED')
CKSK  CALL CLOCK(NT5)
      CALL UCLOCK(NT5)
      ITRIG=ID3
      IF(IDAT1.NE.2)GO TO 2
      I00=NT1
      NT1=NT2
      NT2=I00
C   *** DETERMINE STORAGE FOR ACTIVITIES
    2 LT5=LT3 + ID3*IZP
      LDA=LT5 + ID3*IABS(ID4)*IM
      CALL ADDR(61,63,DUM,DUM)
      IF(LDA.LE.LIM2)GO TO 1
      ID3=ID3-1
      GO TO 2
    1 IF(ITRIG.NE.ID3)WRITE (NOU,10) ITRIG
      IDUM1=LIM2-(IZM*NFFL+IZM)
      IDUM2=IDUM1+IZM
      CALL FINPR(D(LMA),Z(LRA),Z(LRAV),D(LAA),D(LV),Z(LFD),Z(LXN),Z(LQ),
     &Z(LPA),MM,D(LJ3),D(LJ4),Z(LT3),Z(LT5),IM,IZP,IHP,IGMM,D(LDF),D(LMB
     &),D(LMC),D(LXMD),Z(LCRX),Z(LSA ),D(LCMAC),Z(IDUM1),Z(IDUM2),IZM,
     & Z(LXJ),IMJT,NFFL)
   10 FORMAT('0 LOCATIONS FOR COMPLETE ACTIVITY TABLES ARE NOT AVA',
     &'ILABLE'/'   ANISN WILL COMPUTE THE FIRST ',I3,' ACTIVITIES')
      ID3=ITRIG
C   *** COMPUTE SUMMARY TABLES
      IF(IC.NE.0)CALL BT
C     IF(IFG.EQ.0 .OR. IFG.EQ.2)GO TO 3
C   *** DETERMINE STORAGE FOR CROSS SECTION WEIGHTING
C     ICON=LD(LFGP)
C     IHTF=LD(LFGP+1)
C     IHSF=LD(LFGP+2)
C     IHMF=LD(LFGP+3)
C     IPUN=LD(LFGP+4)
C     I01=LFGG+IGM-1
C     IGMF=LD(I01)
C     IHST=IABS(IHSF)
C     IHMT=IHMF + IHST - IABS(IHTF) - 1
C     IF(IHSF.GE.0)IHMT=IHMF
C     I01=LTAB
C     I02=I01 + IGM
C     I03=I02 + IGMF
C     I04=I03 + IZP
C     CALL ADDR(123,126,DUM,DUM)
C     I05=LIM1 + 1 - 200
C     I06=I05-200
C     I07=I06-200
C     I08=I07-200
C     IF(I04.GE.I08) CALL ERRO('FGCR',I08-I04)
C     CALL FEWG(D(I01),D(I04),D(I03),D(I02),D(LFGG),D(LJ5),D(LMB),
C    1D(LMC),D(LMZ),D(I05),D(I06),D(I07),D(I08),D(LEND))
    3 RETURN
      END
