      SUBROUTINE FLUXRD(FLUX  ,FLUXB ,MESH  ,IMESH  ,IGMAX ,
     1                  IXMAX ,IYMAX ,IZMAX ,IBUFF  ,ICODE ,
     2                  IDIM  ,VOLUME,ISTEP ,IRANG  ,VOLB  ,ICF  ,
     3                  LNRGN ,LPVOL ,LMAX                       )
C
C     READ MESH-WISE FLUX DATA
C
      COMMON /MAINC/ IOPTS(100)
      COMMON /WORK/ A(60000)
      COMMON /PIJ2C/ PIJ(50),PAA(950)
      EQUIVALENCE (PIJ(47),LCVOLR)
      COMMON /SN1C/ ANSN(1000)
      EQUIVALENCE (ANSN(24),LVA)
      COMMON /TW1C/ TWTRN(2000)
      EQUIVALENCE (TWTRN(209),IVMESH)
C
      DIMENSION FLUX(IGMAX,IMESH),FLUXB(IBUFF),MESH(3,IMESH),
     *          VOLUME(IMESH),VOLB(IBUFF)
C
      IF (ISTEP .EQ. 1) GO TO 500
      IF(ICODE.GT.2) GO TO 100
   10 FORMAT(I12)
   20 FORMAT(6E12.5)
C----- PIJ AND ANISN
      CALL RAFX1D(FLUXB,FLUX ,MESH ,IXMAX,IGMAX,IMESH,ICODE,PAA(LCVOLR),
     *            VOLUME,ANSN(LVA) ,IRANG,VOLB ,ISTEP,ICF              )
      GO TO 900
  100 CONTINUE
      IF(ICODE.NE.3) GO TO 200
C----- TWOTRAN
      CALL RFLX2D(FLUXB,FLUX ,MESH ,IXMAX,IYMAX,IGMAX,IMESH,VOLUME,
     *            IVMESH,A(1)                                         )
      GO TO 900
  200 CONTINUE
      IF(ICODE.NE.4) GO TO 300
C----- TUD
      CALL RTFX1D(FLUXB,FLUX ,MESH ,IXMAX,IGMAX,IMESH,IXMAX+1,VOLUME,
     *            VOLB                                                )
      GO TO 900
  300 CONTINUE
      IF(IDIM.EQ.3) GO TO 400
      IF(IDIM.EQ.2) GO TO 350
C----- CITATION 1D
      CALL RDFX1D(FLUXB,FLUX ,MESH ,IXMAX,IGMAX,IMESH,VOLUME,
     *            A(LNRGN),A(LPVOL),LMAX                     )
      GO TO 900
C----- CITATION 2D
  350 CALL RDFX2D(FLUXB,FLUX ,MESH ,IXMAX,IYMAX,IGMAX,IMESH,VOLUME,
     *            A(LNRGN),A(LPVOL),LMAX                     )
      GO TO 900
  400 CONTINUE
C----- CITATION 3D
      CALL RFLX3D(FLUXB,FLUX ,MESH ,IXMAX,IYMAX,IZMAX,IXMAX*IYMAX,
     1            IGMAX,IMESH,VOLUME,A(LNRGN),A(LPVOL),LMAX )
      GO TO 900
C
  500 CONTINUE
      CALL RAFX1D(FLUXB,FLUX ,MESH ,IXMAX,IGMAX,IMESH,  1  ,PAA(LCVOLR),
     *            VOLUME,ANSN(LVA),IRANG ,VOLB ,ISTEP,ICF              )
      GO TO 900
  900 CONTINUE
      IF(IOPTS(18).LT.0) THEN
         DO 950 I=1,IMESH
         WRITE(7,10)  I
         WRITE(7,20)  (FLUX(N,I),N=1,IGMAX)
  950    CONTINUE
      END IF
      RETURN
C
      END
