      SUBROUTINE IBCD(J,I)
C
C * * EBCDIC CODE FOR DIGIT
C                            FACOM 230-60
C     BUILTIN SUBROUTINES PACK AND UNPACK
C     UNPACK (I,J,K)CLEAR LOCATION K AND STORE J TH CHARACTER OF LOCATIO
C                                  INTO THE LAST(4TH) CHARACTER OF K
C     PACK(I,J,K)  STORE THE LAST CHARACTER OF K INTO J TH CHARACTER OF
      CHARACTER*4 J
      I = INDEX('0123456789',J(1:1) ) -1
      IF(I.LT.0) I = 10
      RETURN
      END
