C             INPT12              LEVEL=1        DATE=81.11.14
      SUBROUTINE INPT12
C
      COMMON /TW1C/ DD(1),LIM1,IA(210)
      COMMON /WORK/AAA(1),LIM2,AA(130)
      DIMENSION D(212),A(132)
      EQUIVALENCE (D(1),DD(1)),(AAA(1),A(1))
C
C     INPUT INTEGERS
C
      EQUIVALENCE (IA(4),IGM),(IA(11),IEVT),(IA(13),MT),(IA(14),MIN),
     &(IA(18),IHM)
C
C     FIRST WORD ADDRESSES
C
      EQUIVALENCE (A(61),LC),(A(67),LQ),(A(76),LFL),(A(122),LFU),
     &(A(112),LAA)
C
C     /FWBGN1/ , /FWBGN2/ , /LOCAL/
C
      EQUIVALENCE (D(110),IPFL),(D(112),IPFX),(D(120),IPQS),(D(115),IPXS
     &),(D(155),LENCLR),(D(149),LMTP),(D(111),LTFL),(D(113),LTFX),
     &(D(121),LTQS),(D(117),LTXS),(D(145),MCR),(D(146),MTP),(D(147),MTPS
     &),(D(148),NISOXS)
CKSK  CALL CLEARW(0.0,A(LC),LENCLR)
      CALL CLEARW(0.0,AAA(LC),LENCLR)
C
C     CLEAR CROSS SECTIONS, FLUXES AND FLOWS IN ECS
C
CKSK  CALL CLEARW(0.0,A(LC),LTXS)
      CALL CLEARW(0.0,AAA(LC),LTXS)
CKSK  CALL CLEARW(0.0,A(LFL),LTFX)
      CALL CLEARW(0.0,AAA(LFL),LTFX)
CKSK  CALL CLEARW(0.0,A(LFU),LTFL)
      CALL CLEARW(0.0,AAA(LFU),LTFL)
CKSK  IF (IEVT.EQ.0) CALL CLEARW(0.0,A(LQ),LTQS)
      IF (IEVT.EQ.0) CALL CLEARW(0.0,AAA(LQ),LTQS)
      DO 100 IG=1,IGM
CKSK  CALL RITE (0,IPFX+(IG-1)*LTFX,A(LFL),LTFX,1)
      CALL RITE (0,IPFX+(IG-1)*LTFX,AAA(LFL),LTFX,1)
CKSK  CALL RITE (0,IPXS+(IG-1)*LTXS,A(LC),LTXS,1)
      CALL RITE (0,IPXS+(IG-1)*LTXS,AAA(LC),LTXS,1)
CKSK  IF (IEVT.EQ.0) CALL RITE (0,IPQS+(IG-1)*LTQS,A(LQ),LTQS,1)
      IF (IEVT.EQ.0) CALL RITE (0,IPQS+(IG-1)*LTQS,AAA(LQ),LTQS,1)
CKSK  CALL RITE (0,IPFL+(IG-1)*LTFL,A(LFU),LTFL,1)
      CALL RITE (0,IPFL+(IG-1)*LTFL,AAA(LFU),LTFL,1)
  100 CONTINUE
C
C     PREPARE CROSS SECTIONS
C
CKSK  CALL CSPREP ( A(LC),A(LQ),IHM,IGM,MT,MIN,A(LAA),MCR,MTP,LMTP,MTPS,
CKSK &NISOXS )
      CALL CSPREP ( AAA(LC),AAA(LQ),IHM,IGM,MT,MIN,AAA(LAA),
     &MCR,MTP,LMTP,MTPS,NISOXS )
      RETURN
      END
