C             SSOURC              LEVEL=12       DATE=85.06.22
C  ********************************************************************
C                          SSOURC
C  ********************************************************************
C     SUBPROGRAM TO PRODUCE DISTRIBUTED SOURCE INDUCED BY SURFACE SOURCE
C     WRITE  INTO  NSOU(FT32)
C     SURFACE SOURCE IS READ FROM 'FLUX    ' FILE IN PDS ARRANGEMENT
C     BY THE NAME OF 'CASEABS2' OR 'CASEABS0'
C
      SUBROUTINE SSOURC(NR,NG)
C
      COMMON /MAINC/  IOPT(63),NOUT1,NOUT2,DUM66(8)
     *               ,NSOU,NFIN,NFOUT,I77(24),CASENM(2)
      COMMON /PDSPDS/ BUF(540),IFLSW,FILENM(3)
      COMMON /WORK  / WG(107),S(300,107)
      COMMON /TMPSET/ STND(35),NUMB(61),NTDUMY
      CHARACTER *4 NUMB,CASENM,NODE(2),FILENM
C === NR   NO OF REGIONS (MESH)
C === NG   NO OF ENERGY GROUPS
C === ASSUMPTION ON FLUX.... SPATIALLY FLAT,WEIGHTING SPECTRUM WG
C === TEST NR
      IF(NR.GT.300) GOTO 600
C === PDS FILE 'FLUX'
      IFLSW=1
CKSK  FILENM(1)=4HFLUX
      FILENM(1)='FLUX'
CKSK  FILENM(2)=4H
      FILENM(2)='    '
C === READ SURFACE SOURCE
      NODE(1)=CASENM(1)
CKSK  NODE(2)=4HA0S2
      NODE(2)='A0S2'
      IF(IOPT(4).EQ.0)  NODE(2)(1:1)='F'
      IF(IOPT(10).NE.0) NODE(2)(4:4)='0'
C === BURNUP INDICATOR IN MEMBER NAME
      IF(IOPT(20).NE.0 .AND. IOPT(79).NE.0)
     *NODE(2)(2:2)=NUMB(IOPT(79))(4:4)
      CALL SEARCH(NODE,LGT,ISW)
      IF(ISW.NE.0) THEN
C === SUPRESS BURNUP INDICATOR IF NOT PREPARED
      NODE(2)(2:2)='0'
      CALL SEARCH(NODE,LGT,ISW)
      IF(ISW.NE.0) GO TO 610
                   ENDIF
      IF(LGT.NE.NG)  GO TO 620
      CALL READ(NODE,WG,NG)
C
C === READ PROB(SURFACE TO VOLUME REGION)
C
      REWIND 22
      DO 50 N=1,NG
      READ(22) (S(I,N),I=1,NR)
      DO 40 I=1,NR
      S(I,N)=WG(N)*S(I,N)
   40 CONTINUE
   50 CONTINUE
C
C === STORE SOURCE INTO NSOU IN UNIT CM**(-2)SEC**(-1)
C
      REWIND NSOU
      WRITE(NSOU) ((S(I,N),I=1,NR),N=1,NG)
C
C === STORE FLUX GUESS INTO NFIN
C
      REWIND NFIN
      WRITE(NFIN) ((S(I,N),I=1,NR),N=1,NG)
      RETURN
C
C === ERROR STOPS
C
  600 PRINT 601,NR
  601 FORMAT(' *** NUMBER OF SPATIAL MESH EXCEEDS THE LIMIT IN SSOURC '
     * ,I6)
      GO TO 700
  610 PRINT 611,NODE
  611 FORMAT(' *** MEMBER ',2A4,
     *' FOR SURFACE SOURCE NOT FOUND  IN FLUX FILE')
      GO TO 700
  620 PRINT 622,NODE,NG,LGT
  622 FORMAT(' *** INCONSISTENT LENGTHS OF MEMBER ',2A4,' NG=',I5,
     * ' LENGTH=',I5,'*** ENCOUNTERED IN SSOURC')
  700 STOP
      END
