C
      SUBROUTINE STPCOM(LAST,ISTP)
      COMMON /MAINC/ IOPT(63),NOUT1,NOUT2,IT0
      CHARACTER*8 STPCM(28)
CKSK  DATA   STPCM   /8HINPUT 1 ,8HUSER F L,8HUSER T L
CKSK *    ,8HPIJ INPT,8HGEOMINPT,8HINPUT 2 ,8HMACRO F
CKSK *    ,8HMACRO T ,8HGAM P1B1,8HIR APPRO,8HMCROSS
CKSK *    ,8HCELLFAST,8HPEACO   ,8HMIXXFAST,8HCELLTHML
CKSK *    ,8HMIXXTHML,8HHOMOSP  ,8HCOND FIX,8HCONCAT
CKSK *    ,8HMICRO EF,8HBURN FIX,8HEIGN VLE,8HMIXXEIGN
CKSK *    ,8HCONDEIGN,8HMICREF  ,8HBURNEIGN,8HCIT MACR,8HEND CASE/
C
      DATA   STPCM   /'INPUT 1 ','USER F L','USER T L'
     *    ,'PIJ INPT','GEOMINPT','INPUT 2 ','MACRO F '
     *    ,'MACRO T ','GAM P1B1','IR APPRO','MCROSS  '
     *    ,'CELLFAST','PEACO   ','MIXXFAST','CELLTHML'
     *    ,'MIXXTHML','HOMOSP  ','COND FIX','CONCAT  '
     *    ,'MICRO EF','BURN FIX','EIGN VLE','MIXXEIGN'
     *    ,'CONDEIGN','MICREF  ','BURNEIGN','CIT MACR','END CASE'/
  111 FORMAT(1H0,'*** ENTRANCE STEP ',I2,'**',A8,'**',I10,
     *' SEC ELAPSED AFTER STEP',I2,'**')
CKSK *' SEC ELAPSED I/O COUNT=',I6,' WITHIN ',I6,' AFTER STEP',I2,'**')
CKSK  CALL CLOCK(ITIME)
CKSK  CALL EXCP(LIMIT,IONO)
      CALL UCLOCK(ITIME)
CKSK  CALL UEXCP(LIMIT,IONO)
      ITIME=ITIME-IT0
      WRITE(NOUT1,111) ISTP,STPCM(ISTP)
     *  ,ITIME,LAST
CKSK *  ,ITIME,IONO,LIMIT,LAST
      LAST=ISTP
      RETURN
      END
